### ISSUE TITLE
New entry is typed ahead of the older selected option.

### ISSUE THREAD

**Issue by anandphulwani** [orchidjs/tom-select#10]
**Describe the bug**
If an option is already selected in the control, when a new entry is typed, it is typed ahead of the already selected option.
![recording](https://user-images.githubusercontent.com/3785927/104809780-ad4d1680-5815-11eb-93ee-ec0e0caa7d4b.gif)

**To Reproduce**
If an option is already selected in the select box, when we focus on the box and start typing the 
1. Go to https://codepen.io/anandphulwani/pen/JjRwpjM
2. Select "Select a person" box and select any value.
3. Move your focus to 1st component.
4. Click on tab, now focus is back on the select box, start typing any text to filter results in the dropdown.
5. The older value is shown and the new value is typed ahead of the older value.

**Expected behavior**
If an option is already selected in the control, as soon as the control receives focus, the text should be selected, and as soon as new key is pressed (except tab, shift+tab) the selected text should be cleared and new value should be typed.
If a valid value is typed or selected, and focus is moved out the control that value should persist, if an invalid value is typed or half typed, and focus is moved out, the value should revert to older value.

**Additional context**
 - Windows 10
 - Firefox Developer Edition
 - 85.0b7
 - PC

**Comment by oyejorge** [comment]
[Take a look at this example](https://jsfiddle.net/b3mgp7y2/). Does that give you the behavior you're looking for?

**Comment by anandphulwani** [comment]
> 
> 
> [Take a look at this example](https://jsfiddle.net/b3mgp7y2/). Does that give you the behavior you're looking for?

I did have a look and this is not matching my expectations, it has two problems
- On firefox, The focus cycle breaks, i.e. i cannot shift away from the select box using Tab key, i am unsure how it behaves on other browsers.
- The older value gets cleared as soon as the control is focused, and i am unable to make out what i had selected earlier, for that i have to move out from the control to check.

I was looking for a behavior similar to this
https://codepen.io/anandphulwani/pen/YzpzVyM

P.S. i developed a separate plugin for it in selectize.
