### ISSUE TITLE
Unexpected behavior with create and duplicates enabled

### ISSUE THREAD

**Issue by jsicherman** [orchidjs/tom-select#106]
**Describe the bug**
I've created a tom-select with `create: true, duplicates: true`. When removing a duplicate value from this tom-select (by pressing backspace), the deleted element isn't always at the caret position and sometimes deletes multiple copies of the duplicated value (while throwing an error, below).

**To Reproduce**
1. Create a tom-select input with duplicates and create enabled
2. Enter some values including at least some duplicates
3. Delete values using backspace. When removing a value that has multiple copies, the bug will occur.

**Expected behavior**
The element(s) should be deleted.

**Additional context**
Error message as follows (using latest dist):
```
Uncaught TypeError: t.options[s] is undefined
    updateOriginalInput tom-select.ts:2077
    removeItem tom-select.ts:1887
    removeOption tom-select.ts:1646
    removeItem tom-select.ts:1880
    deleteSelection tom-select.ts:2266
    onKeyDown tom-select.ts:691
    setup tom-select.ts:324
    C utils.ts:128
    setup tom-select.ts:324
    R tom-select.ts:157
    <anonymous> initialize.js:5
    jQuery 8
    onopen shinyapp.js:94
    createSocket shinyapp.js:91
    connect shinyapp.js:36
    initShiny init_shiny.js:551
    setTimeout handler* init_shiny.js:583
    jQuery 13
tom-select.ts:2077:4
```

**Comment by oyejorge** [comment]
Hmm, I'm not  seeing any errors. [Do you get them with this example](https://jsfiddle.net/2m8qup51/)?

**Comment by jsicherman** [comment]
I don't get errors with your example. It seems that it's actually a problem with the `autocomplete` option. Removing `autocomplete="off"` from your example causes the error to occur as described.

**Comment by oyejorge** [comment]
Hmm, I just tried without `autocomplete="off"` and I'm still not getting the error.

**Comment by oyejorge** [comment]
Would love to get this fixed. If you have any other steps and/or clues on how to reproduce the error, please let me know.

**Comment by jsicherman** [comment]
Interestingly I can't get the error log to be thrown again for some reason. However, I can still replicate the behaviour of the issue reliably.

Do the following:
1. Type `test,tes,test` (or any string which contains some duplicates and some other values) followed by backspace

I've uploaded an mp4 of this happening to my Dropbox: [here](https://www.dropbox.com/s/k3l0xs43hi68mxd/tom-select.mp4?dl=0).

I'm trying again now and it actually occurs even with `autocomplete="off"` still present... [Example](https://www.dropbox.com/s/jpqthi87gu492iw/tom-select2.mp4?dl=0). For some reason I can't quite isolate what's causing this.

**Comment by oyejorge** [comment]
Awesome, I see what you're talking about now. Thanks!

**Comment by jsicherman** [comment]
Thanks for your quick work! Unfortunately this isn't fully fixed: `Ctrl+A, backspace` (or any other way of selecting multiple elements like `Shift + click` or `Ctrl + click`) still deletes elements in an unexpected manner

**Comment by oyejorge** [comment]
Hmm. 

> still deletes elements in an unexpected manner

Could you describe what you mean by that? I'm not seeing any issues... wondering if your referring to the large gap that can appear between items after an item in the middle was deleted?

**Comment by jsicherman** [comment]
Ah that may be my oversight. Yes upon closer inspection, it seems the elements are actually being deleted correctly, but elements right of the cursor are being pushed off to the right side of the input as you describe. Sorry for my over-eager bug reporting! I appreciate your responsiveness.

**Comment by oyejorge** [comment]
It's all good. The solution for this is the [input_autogrow plugin](https://tom-select.js.org/plugins/input-autogrow/).
