### ISSUE TITLE
Placeholder shows if disabled

### ISSUE THREAD

**Issue by jsicherman** [orchidjs/tom-select#107]
**Describe the bug**
On a multi-input with `hidePlaceholder: true`, placeholders are correctly hidden when there is one option selected and the select input is not focused, but when focused, the placeholder shows again. It seems to me like they should remain hidden whether or not the element has focus.

**To Reproduce**
1. Create a tom-select with `hidePlaceholder: true`
2. Select a value - notice that the placeholder remains
3. Click somewhere else on the page and watch the placeholder disappear

**Expected behavior**
The placeholder should be removed whether or not the element has focus (as long as there is >= 1 option selected)

**Additional context**
Latest Firefox and tom-select dist.

**Comment by oyejorge** [comment]
This was actually the intended behavior. I think it's best to leave as-is for now since the alternative can easily be accomplished with CSS:

```css
.ts-input.has-items > input::placeholder {
   color:transparent;
}
```

I'll update the description for the hidePlaceholder setting to reflect the actual behavior
