### ISSUE TITLE
Unable to submit empty field, add an option to relax `required` attributes

### ISSUE THREAD

**Issue by fmoko** [orchidjs/tom-select#11]
**Is your feature request related to a problem? Please describe.**
My use case is that I have a tag system where users are able to select any combination of tags that they want (including none). When there's a tag selected and you delete the tag from the field, the user is unable to submit the form because tom-select's internal inputs have the `required` input set. Judging from the code, this is intentional, but it breaks this use case and I was wondering whether this could be an additional option?

**Describe the solution you'd like**
A toggleable option to remove the `required` attributes on the inputs.

**Describe alternatives you've considered**
tom-select reapplies the `required` attribute pretty aggressively, so I can't programmatically remove it via hooking into its events, either.

**Comment by oyejorge** [comment]
Thanks! The change above should fix the problem. I'll get a new release out here soon.

**Comment by fmoko** [comment]
Thank you!
