### ISSUE TITLE
allowEmptyOption not working

### ISSUE THREAD

**Issue by acetinick** [orchidjs/tom-select#119]
**Describe the bug**
1.7.3 and 1.7.4 at least are having issues with allowEmptyOption.  Empty option is unable to be selected.

Example
https://jsfiddle.net/ocqzp0ht/

**To Reproduce**
Steps to reproduce the behavior.

set any select with allowEmptyOption

**Expected behavior**

Should be able to select empty option

**Comment by acetinick** [comment]
Btw,  downgrading to 1.7.0 fixes this.

**Comment by oyejorge** [comment]
Dang it. I could have sworn I made sure we had unit tests for that.

**Comment by oyejorge** [comment]
Ok, fixed and we definitely have a test for this now.
