### ISSUE TITLE
Minimum input length on remotely loaded results

### ISSUE THREAD

**Issue by shillem** [orchidjs/tom-select#12]
I would like to prevent searches from being carried out when the string length is lower than a certain value (e.g. 3 chars min).
I can tweak the load function and exit it if the requirement isn't met but then the "no results message" returned by calling the callback without items wouldn't convey the right message.

Maybe the `createFilter` option could be used before `load` is called or there should be a way to change the message returned if the callback has been called due to the query being too short (or any other reason for that matter, e.g. the search returned an error).

**Comment by oyejorge** [comment]
With the above change, you could do [something like this](https://jsfiddle.net/xj0qkhub/3/)

**Comment by shillem** [comment]
> With the above change, you could do [something like this](https://jsfiddle.net/xj0qkhub/3/)

Yes, that's a reasonable solution. I will go with that. Thanks!

**Comment by oyejorge** [comment]
Update. As of v1.2, there's an easier way to do this with the [shouldLoad() callback](https://jsfiddle.net/jy4vhnr5/).

**Comment by shillem** [comment]
That's even better. Thanks!
