### ISSUE TITLE
Close dropdown issue on multiple instances

### ISSUE THREAD

**Issue by rizkimuhammada** [orchidjs/tom-select#126]
Hi guys,

I hope you are well in this covid pandemic condition,

I just found an issue when initiating 2 or more plugin instances. Closing the first select dropdown always triggers the next select dropdown to open. Is it expected behavior?

**To Reproduce**
Steps to reproduce the behavior.
1. Create multiple select elements.

`
<select class="tom-select" id="select-1">
    <option value="1">John Wick 1</option>
    <option value="2">John Wick 2</option>
    <option value="3">John Wick 3</option>
</select>
<select class="tom-select" id="select-2">
    <option value="1">John Wick 1</option>
    <option value="2">John Wick 2</option>
    <option value="3">John Wick 3</option>
</select>
`

2. Initiate the plugin.

`
new TomSelect("#select-1");
new TomSelect("#select-2");
`

3. Try to close the first select dropdown.

**Video**
https://www.youtube.com/watch?v=ulMGgmQ7xWw

**JSFiddle**
https://jsfiddle.net/m96wdths/

**Expected behavior**
Closing the first select dropdown will not trigger the second select dropdown to open.

**Additional context**
 - OS: [Macos Bigsur]
 - Browser [chrome]
 - Version [91.0.4472.101]
 - Device: [Macos]

Thank you

**Comment by oyejorge** [comment]
Weird, but yeah, I'm seeing it too...

**Comment by oyejorge** [comment]
Only seems to be a problem with default.css and bootstrap3.css

**Comment by oyejorge** [comment]
I've narrowed things down a bit and found that adding `align-items:center` to the css fixes the problem. [Could you test this fiddle to confirm](https://jsfiddle.net/wcbtLr1s/)?

**Comment by oyejorge** [comment]
Dug a little further and I have another possible solution. [Could you test this jsfiddle as well to confirm the fix](https://jsfiddle.net/o29t75eh/)?

**Comment by rizkimuhammada** [comment]
@oyejorge Thank you for your reply! :)

I just did a re-styling of tom-select and realized it's a CSS problem.

But I'm not sure which part is causing the issue.

I've also tried the jsfiddle link above and it solved the problem.

Really thanks for your help, I will close this issue.
