### ISSUE TITLE
dropdown_input plugin avoid to focus on select using tab

### ISSUE THREAD

**Issue by eusonlito** [orchidjs/tom-select#138]
With dropdown_input enabled, I can not open de select with using tab to select inputs.

```html
<select id="app-tags" name="tags[]" class="tom-select" multiple="multiple">
    <option value="1" selected>Social</option>
</select>
```

Using tab key to focus select and create or select an option is working fine without `dropdown_input` plugin, no mouse needed:

```js
new TomSelect(this, {
    create: true,
    plugins: ['remove_button']
});
```

![without-dropdown-input](https://user-images.githubusercontent.com/644551/124445527-ec4d3500-dd7f-11eb-909b-6326dcc27c63.gif)

When `dropdown_input` plugin is set, I need to click with the mouse to expand selector and write, tab focus does not expand selector:

```js
new TomSelect(this, {
    create: true,
    plugins: ['dropdown_input', 'remove_button']
});
```
![with-dropdown-input gif](https://user-images.githubusercontent.com/644551/124444131-962bc200-dd7e-11eb-8324-12057920e474.gif)

**Additional context**

 - OS Ubuntu
 - Browser Google Chrome 
 - Version 92.0.4515.80 (Official Build) beta (64-bit)
 - Device Desktop PC

Best Regards.

**Comment by oyejorge** [comment]
Should be all set with the next release
