### ISSUE TITLE
Bootstrap 5 Support

### ISSUE THREAD

**Issue by Sladewill** [orchidjs/tom-select#14]
Is support for Bootstrap 5 on the books very soon, despite it being in Beta at the moment its not going to be long before full release.

As well default docs are set as Bootstrap 5 beta people will start using that automatically.

**Comment by oyejorge** [comment]
I haven't spent much time looking into it yet but yes, Bootstrap 5 will be supported. [It looks like there aren't many changes needed](https://github.com/selectize/selectize.js/issues/1584).

**Comment by oyejorge** [comment]
Ok, had to make a few changes to get the scss to compile with bootstrap5, [but it looks good so far](https://tom-select.js.org/examples/)

**Comment by Sladewill** [comment]
Yes I tried this out last night and it appears to be working perfectly.
