### ISSUE TITLE
`persist: true` interferes with `.addOption()`

### ISSUE THREAD

**Issue by trullock** [orchidjs/tom-select#145]
Repro: https://jsfiddle.net/o5pq9f1h/

click in the box, select `aaa`, remove `aaa`, refocus or type `a`, the `aaa` option is no longer there.

I wouldn't expect `persist: true` to make the options added via `addOption()` not persist....

**Comment by oyejorge** [comment]
The fix for this needed a slight change to the API so I've put it in the 2.0 branch and I just pushed out [Beta.1](https://github.com/orchidjs/tom-select/releases/tag/v2.0.0-Beta.1)
