### ISSUE TITLE
Issue with Bootstrap 5 and is-invalid class

### ISSUE THREAD

**Issue by apphancer** [orchidjs/tom-select#150]
**Bug description**

When the is-invalid class is applied to a `<select>` element, this class also gets applied to `div.ts-dropdown` causing

1. Weird styling to be applied to the dropdown (e.g. red warning icon and chevron icon repeated across the entire dropdown area)'
2. Dropdown not showing when clicking on the chevron icon; clicking on the input area does however expand the dropdown

![image](https://user-images.githubusercontent.com/3098891/126989626-12861aeb-9371-4d6b-87f5-719d0630d791.png)

**To Reproduce**

Create a select element with an `is-invalid` class, e.g. fail server-side form validation.

Here is an example of the output showing the issue: https://jsfiddle.net/apphancer/6f275osc/

**Expected behaviour**

I would expected the is-invalid class to not get propagated, or an option in the config to declare classes that should not be propagated.

It seems that removing the `.is-invalid` class from the `.ts-dropdown` element fixes the issue with the repeated background icons.
Removing `.form-select` from the `.ts-control` element fixes the issue affecting the clicks on the chevron icon.

**Comment by apphancer** [comment]
My quick workaround for now is to have the following config:

```
let config = {
    onInitialize: function () {
        this.wrapper.classList.remove('form-select');
        this.dropdown.classList.remove('is-invalid');
    }
};
```
Not sure if there are any other better workarounds or if this is in an issue with how I have implemented the whole thing.

**Comment by oyejorge** [comment]
Probably better to [set copyClassesToDropdown to false](https://jsfiddle.net/9Ljw57va/)

**Comment by apphancer** [comment]
> Probably better to [set copyClassesToDropdown to false](https://jsfiddle.net/9Ljw57va/)

Nice and clean. However, while it does solve the issue with the background image, it still seems to prevent the click event on the chevron icon from expanding the dropdown.

**Comment by oyejorge** [comment]
Good catch, looks like we need to tighten up some of the CSS. [Here's the quick fix](https://jsfiddle.net/peb3ux2o/)
