### ISSUE TITLE
getOption doesn't get option on newly initialized tom-select object

### ISSUE THREAD

**Issue by martinbarilik** [orchidjs/tom-select#151]
Hi there,

lately i have spotted a bug that my tests revealed. On newly initialized object, getOption method doesn't get an option, gets null. Only way i can get it is to refreshOptions(false) before. 

https://jsfiddle.net/mArtinko5MB/dukmpx3t/9/

No idea if that is expected behavior, but it seems to me it's unnecessary to call refreshOptions before doing anything with the select.

**Comment by oyejorge** [comment]
I have come across this before and I'm kind of 50/50 on where to go with it.

```getOption(value)``` returns the dom element that's used to display an option in the Tom Select dropdown. These dom elements are created only if they're needed. In a situation where there are thousands of options, dom elements may never be created for many of the options.

A solution may be to add a ```create_option``` argument so the function signature would look like this: ```getOption(value, create_option)```. Calling ```getOption('a',true)``` would create the dom element for 'a' if it doesn't already exist.

**Comment by oyejorge** [comment]
```getOption('a',true)``` can now be used. [docs](https://tom-select.js.org/docs/api/#option-methods)
