### ISSUE TITLE
Browser validation issue when 

### ISSUE THREAD

**Issue by Seb33300** [orchidjs/tom-select#153]
**Describe the bug**
When [dropdown input](https://tom-select.js.org/plugins/dropdown-input/#dropdown-input) plugin is enabled, the [browser validation](https://tom-select.js.org/examples/validation/) works, but the error message is not displayed.

This is because the search input is moved inside the dropdown which is hidden by default.
We can see the error message is we open the dropdown:

![image](https://user-images.githubusercontent.com/915273/127769941-5badde9e-932f-4dab-a059-5812894662e9.png)

====

Also, please note that a small issue is in the documentation, on the first example:

![image](https://user-images.githubusercontent.com/915273/127769974-af47b1cc-5d54-4b76-baa8-590f908cad79.png)

**Comment by oyejorge** [comment]
This has actually already been fixed [with this change](https://github.com/orchidjs/tom-select/commit/c2bd068a979ec4146a1b168803c5001aef7100cb) in our 2.0 branch.

**Comment by Seb33300** [comment]
Yes, branch 2.0 fix the issue. Thank you
