### ISSUE TITLE
Empty select option item with no value drops to last item

### ISSUE THREAD

**Issue by apphancer** [orchidjs/tom-select#157]
I am experiencing an issue with the how select option items are re-ordered by the plugin when an option is pre-selected, this in turn is causing issues when the form is submitted as the top item is considered the selected one.

**To Reproduce**
Create a select element with an option that has no value and a 1 or more additional values. 

Example:

```
<select name="label">
  <option value=""></option>
  <option value="3">Option A</option>
  <option value="1" selected="selected">Option B</option>
</select>
```

When there is no option selected in advance, tom-select applies the order correctly:

```
<select name="label" class="tomselected" tabindex="-1" hidden="hidden">
  <option value=""></option>
  <option value="3">Option A</option>
  <option value="1">Option B</option>
</select>
```

When there is an option selected in advance (e.g. a value coming from the back-end), tom-select changes the order, moving the selected option item to the top:

```
<select name="label" class="tomselected" tabindex="-1" hidden="hidden">
  <option value="1" selected="true">Option B</option>
  <option value=""></option>
  <option value="3">Option A</option>
</select>
``` 

The problem arises when the user deselects the pre-selected item leaving no option selected (e.g. using the delete keyboard key; using remove_button or clear_button plugins).

When the form is submitted, the posted Form Data (at least in Chrome) contains the value for the 1st select option.

**Expected behaviour**
Is it possible to maintain the original order of the options or make sure that, when no item is selected, the selected="true" attribute is set on the empty option?

**Comment by apphancer** [comment]
My bad! 
Sorted with `allowEmptyOption: true`

**Comment by apphancer** [comment]
Ok, I am obviously posting here in too much haste. 
The flow seems a bit glitchy. Although, adding `allowEmptyOption: true` works, it's far from ideal.

An empty option is only posted if the user manually selects the empty option. Deleting an option with the delete key or using the remove_button does not select the empty option and still has the issue described in my first message.
I will try to play with `onItemRemove` and `onClear`, but still I think it would be great if the order of the option elements could be addressed.

**Comment by oyejorge** [comment]
I'm not seeing the problem here. With ```allowEmptyOption: true```, clearing the Tom Select instance seems to update the original select so that the empty option is selected. Am I missing something?

**Comment by endelwar** [comment]
I'm experiencing the same issue: on the hidden select element, the order of option elements is changed: is it really necessary to reorder options? On my tests, browsers submit the first option in select if none has the selected attribute set to true, reordering options cause this bug.

**Comment by oyejorge** [comment]
If the only issue is that the order of &lt;option&gt; elements in the hidden &lt;select&gt; are changed, then I don't really see what the problem is. The value of the &lt;select&gt; will be the same and, since the &lt;select&gt; tag is hidden, it doesn't effect the end user.

**Comment by apphancer** [comment]
Using `allowEmptyOption: true` and selecting the empty option works absolutely fine. 
My worry - from a UX perspective - is that some users won't be aware that they can select the "empty space" at the top of the option list.
The `remove_button` plugin or the `clear_button`come to the rescue as they add a nice X icon that most users will be able to understand it allows for removing the selected option.

Please see my fiddle here https://jsfiddle.net/apphancer/62pxLjwb/4/

If the user uses the remove_button or if they set focus to the input field and hit the delete button of their keyboard, the user will get to see the option correctly removed. However, the select element will not have any <option> selected AND the empty <option> is not the first in the list. This in turn causes issues when the data is posted as the browser will post the selected value as the one used by the first <option> of the select.

This is what I have added as a workaround:

```
        onItemRemove: function () {
                this.input.value = '';
            },
```

This is no big deal, but it would be interesting to see if this is related to something that I am doing wrong, if there are better workarounds or if it could be improved in the plugin.

**Comment by oyejorge** [comment]
> My worry - from a UX perspective - is that some users won't be aware that they can select the "empty space" at the top of the option list.

You could give that empty space some text

```
<option value="">Empty Option</option>
```

> However, the select element will not have any selected AND the empty is not the first in the list. This in turn causes issues when the data is posted as the browser will post the selected value as the one used by the first of the select.

Could you double check that? [It's designed to select the empty option in this situation](https://github.com/orchidjs/tom-select/blob/master/src/tom-select.ts#L2067) and from what I can tell it's working. If the empty option isn't selected, could you let me know which browser & browser version your are seeing this in.

**Comment by apphancer** [comment]
After several tests I've managed to get to the bottom of it and can confirm that it is indeed all working as expected.

My issue was that the <select> field was getting created by Symfony with the `required="required"` attribute.

With the `required` attribute, the browser was submitting the value from the 1st <option> which is not the blank option. Removing the `required` attribute everything works well. So essentially I need to get this attribute removed as it shouldn't be there considering that the field is optional, and that is unrelated to this plugin.

Thanks for your time @oyejorge.
