### ISSUE TITLE
Some charachters not found in search

### ISSUE THREAD

**Issue by ay1man4** [orchidjs/tom-select#158]
**Describe the bug**
Some arabic charachters are not evaluated correctly in searching for library version starting **from 1.6.0 and above**, like charachter 'أ' .
However, search is working as expected for tom-select version 1.5.0, but this version has some styling issues with bootstrap 5.

**To Reproduce**
1. Go to [Sample of 1.7.7](https://codepen.io/absi_ayman/pen/bGWmddO)
2. Search for arabic word 'أهلا' or simply first charachter 'أ'
3. You will get no results. However, it is the second choice
4. Go to [Sample of 1.5.0](https://codepen.io/absi_ayman/pen/eYWPNgJ)
5. Search for arabic word 'أهلا' or simply first charachter 'أ'
6. It is working as expected

**Expected behavior**
Search should find any option having chrachters like 'أ', 'إ', 'آ', 'ؤ'

Thank you for this awesome library

**Comment by oyejorge** [comment]
Making some progress on this. One of the tricky pieces here is 'أهلا' can be represented by two distinct sets of codepoints:
'أهلا' (\u{623}\u{647}\u{644}\u{627}) or 'أهلا' (\u{627}\u{654}\u{647}\u{644}\u{627})

**Comment by ay1man4** [comment]
Yes, firs character of word in example 'أهلا' is 'أ' which is a composition of two characters 'ا' and 'ء'  so it has two codepoints:
"\u{623}"
"\u{627}\u{654}"

https://unicode.scarfboy.com/?s=%D8%A3

**Comment by oyejorge** [comment]
Alright, this has been fixed and will be good to go with the next release.
