### ISSUE TITLE
dropdown_input plugin not working properly on some browsers

### ISSUE THREAD

**Issue by Lastimoso** [orchidjs/tom-select#166]
**Describe the bug**
When `dropdown_input` is enabled it's impossible to focus on the input in some browsers. Sometimes you are able to click on the input after closing and re-opening the dropdown. But that doesn't work with Safari.

The example below uses Chrome 92.0.4515.90 on an Iphone 11.
https://user-images.githubusercontent.com/5191085/128923433-76d38ecb-8049-48d4-a751-945abec2ebd1.MP4

The example below uses Safari Safari 14.0.3 on a MacBookPro (BigSur)
![ezgif-7-02d7fa7eef3a](https://user-images.githubusercontent.com/5191085/128921661-ef7cab87-d771-4f2e-8945-9741d16e4213.gif)

We are seeing the same result in Safari desktop Versión 14.0.3

**To Reproduce**
We are seeing the issue in our app but you can reproduce it in the plugin example page:
1. Go to https://tom-select.js.org/plugins/dropdown-input/ using Safari on a Mac or Chome in Iphone
2. Click on the select.
3. Try to click on the second input (the one in the dropdown). It's not reachable.

**Expected behavior**
The inner input should be clickable

**Additional context**
Example1 - MacBook, macOS Big Sur 11.2.3 using Safari 14.0.3
Example2 - Iphone: ios 14 using Chrome 92.0.4515.90

Thanks for this fantastic library!

**Comment by oyejorge** [comment]
We made a number of changes to the dropdown_input plugin in version 2.0. Could you test it out [with this example](https://jsfiddle.net/h34f8ys6/) and let me know what you find?

**Comment by Lastimoso** [comment]
Thanks for your prompt reply!! 👏 👏 👏 

That fiddle example works on all the browsers we've tested previously!
Is there anything there that can help us understand how to fix that in 1.7.x?

**Comment by oyejorge** [comment]
Would be a lot easier to just use 2.0

**Comment by Lastimoso** [comment]
We use this library a lot in production. I cannot upgrade to an unreleased new major version. Do you have an idea about when it's gonna be released? Are there many breaking changes? Thanks

**Comment by oyejorge** [comment]
Here's the [summary of breaking changes](https://tom-select.js.org/docs/migration/)

I've made all the architectural changes I wanted to now and Beta.3 will be the last beta release. I'll try to get an RC out soon
