### ISSUE TITLE
Select remote data source halts browser as you typing fast

### ISSUE THREAD

**Issue by acetinick** [orchidjs/tom-select#186]
**Describe the bug**
https://jsfiddle.net/hx3ve14b/1/

Type something fast in the dropdown input whilst using a remote data source.

eg. "andrew"

It will halt browser, and you have to force to close tab

version : 2.0 rc1

**Comment by oyejorge** [comment]
This, and the other two, bugs have now been fixed in the rc.2 release

Thanks!
