### ISSUE TITLE
Focus ( click ) is not working when working with multiple browser windows

### ISSUE THREAD

**Issue by martinbarilik** [orchidjs/tom-select#191]
Focus ( click ) is not working when working with multiple browser windows. 

https://jsfiddle.net/mArtinko5MB/cq0z3687/23/

How to reproduce: 
- open the example and minimize the browser window to the point you can click on desktop. Now, click on select-box ( drop-down appears). Then click on the desktop ( drop-down vanishes ). Then again, click on select-box - drop-down appears on a microsecond and then vanishes, which makes my tests fails as drop-down options are visible only when SB is focused ( clicked ). 

This was working with previous 1.x latest version. 2.0 rc-2 broke it. 

Cheers buddy ;)

**Comment by martinbarilik** [comment]
Yes, i am, but it doesn't matter. It works just fine on my production server with current chrome and 1.x version. But it doesn't with current chrome version and 2.x rc2 version ;)

**Comment by oyejorge** [comment]
Oh it matters... it's one more reason to switch the testing framework over to selenium.

**Comment by martinbarilik** [comment]
I do not get completely what you are implying. 

The fact is that 1.x latest version on latest chrome is working as intended, but latest version of chrome with 2.0rc2 is not. No idea what more can i do here.

**Comment by oyejorge** [comment]
Sorry, I do see the problem and I have been working on a fix.

I've just been implying that I need to update the testing platform for tom-select so that it can catch issues like this.

**Comment by martinbarilik** [comment]
My bad, I didn't get it :)

Wonderful, waiting for a fix.

Cheers
