### ISSUE TITLE
.sortField doesn't work with remote data ?

### ISSUE THREAD

**Issue by martinbarilik** [orchidjs/tom-select#192]
Hi, remote data settings for tom-select does seem to corrupt original order of json response.

I am using code below: 

```
      let options = {
	      plugins: ['change_listener'],
	      render: {}
      };

      options.sortField = 'obchodne_meno'
      options.valueField = 'obchodne_meno';
      options.labelField = 'obchodne_meno';
      options.searchField = 'obchodne_meno';
      options.load = function (query, callback) {
      let url = `${Routes.my_path()}?str=${encodeURIComponent(query)}`;
      fetch(url).then(response => response.json()).then(json => {
	      callback(json.items);
      }).catch(() => {
	      callback();
      });
      }

      new TomSelect(select, options);
```

sortField doesn't seem to do anything and i am not setting any order in options. What's the catch ?

**Comment by oyejorge** [comment]
Can you give me a little more to work with? Example JSON for a query along with the display you see vs the display you'd like to see?

**Comment by oyejorge** [comment]
Actually, I think [this is what you're looking for](https://github.com/orchidjs/tom-select/discussions/178)

```js
...
 fetch(url).then(response => response.json()).then(json => {
     this.clearOptions(); // <-- clear options from previous queries
     callback(json.items);
}).catch(() => {
...
```

**Comment by martinbarilik** [comment]
Sorry, it didn't work.

Here is the example: https://jsfiddle.net/mArtinko5MB/k7nbsf5a/59/

What is expected: Write "ale" into selectbox so it starts request. 

expected order is:

- "Alena Tsomethingova"
- "Alena Komethingova"
- "Alena Zanythingá"

But it isn't ( it's Zanythingá, Komethingova, Tsomethingova).

The funny thing is that when i change values ( names ) to Tsomething, Ksomething, Zsomething and write "ale" into SB, it suddenly works and order is as expected. I have no idea what is going on. Bug is somehow connected to how string is computed in sort function.

**Comment by oyejorge** [comment]
Shoot, that's right.

> Unless present, a special `$score` field will be automatically added to the beginning of the sort list. This will make results sorted primarily by match quality (descending).

- https://tom-select.js.org/docs/#sortfield

The solution is to make sure `$score` is in the sortField setting:

```js
 sortField: [{field:'name'},{field:'$score'}],
```
or 
```js
 sortField: [{field:'$order'},{field:'$score'}],
```

**Comment by martinbarilik** [comment]
Great, it works. Thanks !
