### ISSUE TITLE
Missing dist folder

### ISSUE THREAD

**Issue by julienmiclo** [orchidjs/tom-select#198]
hello,

i can' find the /dist folder in master.zip. The readme say "All production files (js, css, scss) can be found in the /dist folder" but no dist folder.

Can you add /dist folder to your repo ?

Thank you.

**Comment by oyejorge** [comment]
Oops, thought I had the readme updated. The tom-select website [has been updated](https://tom-select.js.org/#installation) though.

 I'm following [this approach for the dist folder](https://mykeels.medium.com/node-how-to-handle-your-dist-files-9667f47316ab) so the dist folder won't be visible in the git repo.
