### ISSUE TITLE
dropdown_input plugin not working properly on some browsers (still an issue on Tom-select 2.0.rc.2)

### ISSUE THREAD

**Issue by Lastimoso** [orchidjs/tom-select#201]
**Describe the bug** 
When dropdown_input is enabled it's impossible to focus on the input in Safari on the first time you open the dropdown. We are able to click on the input after closing and re-opening the dropdown, but not before.

In Tom-select version 1.7.x the issue also occur with mobile Chrome as reported in [#166](https://github.com/orchidjs/tom-select/issues/166)

https://user-images.githubusercontent.com/5191085/132245626-880c7855-b0f5-4424-b864-74eefab6f17a.mp4

**To Reproduce**
We are seeing the issue in our app but you can still reproduce it in the plugin example page:
1. Go to https://tom-select.js.org/plugins/dropdown-input/ using Safari on a Mac
2. Click on the select.
3. Try to click on the second input (the one in the dropdown). It's not reachable.

**Expected behavior**
The inner input should be clickable

**Extra context**
We upgraded from 1.7.8 to 2.0.rc.2 in order to have this working. We dealt with all breaking changes and everything else works alright.
In our previous Bug report you shared a fiddle with version 2.0.Beta and we couldn't reproduce the issue there so we though it was OK. I forked that fiddle and tried using version 1.7.8 (that we know it had the issue) but the issue is not there: https://jsfiddle.net/s8jk9d2w/1/ even though it is in our apps and in the plugin page listed in the *To reproduce* section

Again, thanks for the library! Any ideas?

**Comment by oyejorge** [comment]
Hmm, I just tested [the example](https://tom-select.js.org/plugins/dropdown-input/) on Safari 12, 13, and 14 and everything seemed to be working fine.

**Comment by Lastimoso** [comment]
https://www.loom.com/share/a13449e34af84a21ac429c368adb9037
We are still seeing this bug in different computers. All Macbook pro M1 using safari 14.0.x
Maybe is only affecting M1 computers?

**Comment by Lastimoso** [comment]
https://www.loom.com/share/0ad72c55745b428baeb69635d59503af
Maybe this gives more context ☝️ I'm using the tab key in that example

**Comment by Lastimoso** [comment]
https://loom.com/share/a97cfd59ca494fbf81c0df3fc6a6bddb
Apparently this is the line blocking the input for me. 👉 https://github.com/orchidjs/tom-select/blob/8e96b1d9ee1a9ce265175c787e87e306eb5dae72/src/plugins/dropdown_input/plugin.ts#L65

**Comment by oyejorge** [comment]
Wow, thanks for the videos!

Very strange that that removing that line fixes the problem. Unfortunately, we do need to call focus on the control input. Maybe using something instead of the ```self.on('dropdown_open'``` event will work...

**Comment by oyejorge** [comment]
Just a guess here, but I'm wondering if you have any browser extensions installed? And if so, could you try it with the extensions disabled?

**Comment by Lastimoso** [comment]
No Extension.
I wonder if the setTimeout inside the `focus` function is counting with something being enqueued before the function inside the setTimeout. Maybe that's not happening...

**Comment by oyejorge** [comment]
Just tested on an M1 and still can't reproduce the error

**Comment by oyejorge** [comment]
Finally! Looks like it's a problem in Safari 14.0 but not 14.1

**Comment by Lastimoso** [comment]
Please let me know if there is anything I can do to help!

**Comment by oyejorge** [comment]
Can you test [this change](https://github.com/orchidjs/tom-select/commit/4bc41044345c8cc789f15bd2d8792c2a001ca22b)?

**Comment by Lastimoso** [comment]
It looks alright! 🎉  

👏 👏 👏 👏
