### ISSUE TITLE
Cant import via ESM

### ISSUE THREAD

**Issue by trullock** [orchidjs/tom-select#21]
This might be user error on my part, if so I'd be really grateful to know what I'm doing wrong.

When I do this `import TomSelect from 'tom-select';`

I get 

```
ReferenceError: navigator is not defined
    at \myproject\node_modules\tom-select\dist\js\tom-select.complete.js:728:28
```

Ignoring the precise error for a moment, this shows that the esm packages havent been loaded, but instead its used the commonjs ones.

This article seems to explain the situation well, but I dont know enough about npm or this project to recommend a course of action: https://2ality.com/2019/10/hybrid-npm-packages.html

Then, on to the error.

This is the offending line:

```	const IS_MAC = /Mac/.test(navigator.userAgent);```

Can we modify the codebase so its not talking to the global `navigator`? Or otherwise, what is my solution to import tomselect in a bundling scenario and not encounter this error?

**Comment by trullock** [comment]
`const IS_MAC = typeof navigator === 'undefined' ? false : /Mac/.test(navigator.userAgent);`

That seems a sensible solution?

**Comment by oyejorge** [comment]
Looks good. I'll get the added in just a minute.

**Comment by trullock** [comment]
Great, thanks!

Looking forward to the release ;)

**Comment by oyejorge** [comment]
All set!

**Comment by trullock** [comment]
Excellent, thanks!
