### ISSUE TITLE
How to remove typed text when selecting with enter?

### ISSUE THREAD

**Issue by trullock** [orchidjs/tom-select#22]
This might just be user-error, in which case an update to the docs might help, otherwise it might be a feature request.

When I use a select like this:

```
	new tomSelect(selectElem, {
		plugins: ['remove_button'],
		create: false
	});
```

I can start typing a few chars, then use the keyboard (up/down/enter) to select a item from the list.

When I do that, the characters i typed remain in the box. Can these be removed on selection?

Thanks

**Comment by oyejorge** [comment]
Like this? https://jsfiddle.net/84fLts2k/

**Comment by trullock** [comment]
Spectacular, thanks!

Might be worth a demo that does that, unless its there and I missed in. In which case make it more obvious/call me an idiot

:D

**Comment by trullock** [comment]
What threw me was that it has that behaviour by default when its a `<select multiple=false>`

**Comment by trullock** [comment]
Hmm, although your solution makes the dropdown say "no results found", if you type another char, then backspace it, you get the search list back...

**Comment by oyejorge** [comment]
It is different for multiple=false (and different from selectize). The reason: let's say you have a [long list](https://tom-select.js.org/examples/performance/) and you want to add all options that have "aaa". You wouldn't want to have to type "aaa" every time.

> your solution makes the dropdown say "no results found"

[Looks like it needs one more line](https://jsfiddle.net/q20dzath/)

**Comment by trullock** [comment]
Awesome, thanks for the support!
