### ISSUE TITLE
Browser tab unresponsive when typing >4 characters in a multiple select

### ISSUE THREAD

**Issue by apphancer** [orchidjs/tom-select#228]
Chrome's tab freezes with a select element with multiple="multiple". I initially thought this was caused by the fact that I was using Stimulus.js. However, I seem to have been able to replicate the issue in jsfiddle without using Stimulus.js.

Using 1.7.8

**To Reproduce**
1. Visit https://jsfiddle.net/apphancer/uoz6q8g5/4/ with Chrome
2. Type in a word with 1-2 characters and select it: all works well
2. Type in a word with more than 4-5 characters: no more characters can be typed and the tab freezes

It doesn't seem to be an issue with Firefox and Safari.

**Comment by grogy** [comment]
I confirm, update to version 2.0 fixed this issue. :+1:
