### ISSUE TITLE
Auto-complete not working

### ISSUE THREAD

**Issue by MushiX** [orchidjs/tom-select#232]
**Describe the bug**
When the form autocomplete is run, the original select changes its value, but the tom-select element will remain unchanged.

**To Reproduce**
Steps to reproduce the behavior.
If possible, please provide a JSFiddle or CodePen example.
Example: https://jsfiddle.net/4tLkzupv/
1. In the example autofill in my browser don't work
2. Copy a code to local projekct
3. You must cause to your browser save data at this form with non first element select list
4. Next click at username field and choose your saved user
5. In console (on Dev Tools) you have your saved value, but tom-select still have choose first element list

**Expected behavior**
After autofill change visible position of tom-select value

**Additional context**
 - Arch Linux
 - Brave
 - PC

**Comment by MatthewKennedy** [comment]
@oyejorge,

This issue occurs when for example if you have an address form with country drop-down using tom-select, if I start entering my name, Safari prompts me to click my contact details and then auto-fills the name, and address fields, including setting the hidden <select> option to United Kingdom, but the Tom Select in the DOM remains showing the country that the page loaded with, "United States".
