### ISSUE TITLE
How to get bootstrap validation styles to apply?

### ISSUE THREAD

**Issue by trullock** [orchidjs/tom-select#24]
The tomselect bootstrap scss defines styles for `.is-invalid` but the class applied to the invalid element is `.invalid`

Consequently an invalid TS has a `.invalid` class on it, but no styling

This example https://tom-select.js.org/examples/required/ shows the styling not applying either

Am I doing something wrong?

Thanks for the support and otherwise fantastic component!

**Comment by oyejorge** [comment]
I went ahead and just updated the docs for this one. Let me know if this is helpful or not: https://tom-select.js.org/examples/validation/

**Comment by oyejorge** [comment]
There were actually a couple of changes in the previous commit that might help your implementation so I pushed out v1.1.3.

**Comment by oyejorge** [comment]
I believe this issue has been resolved so I'm going to close it.

**Comment by trullock** [comment]
Apologies, got distracted on something else.

This looks great, thanks for the effort!
