### ISSUE TITLE
Disable Autocomplete | Avoid keyboard on Mobile

### ISSUE THREAD

**Issue by Egorka** [orchidjs/tom-select#25]
Hi, Thank you for the great library.

Is it possible to open simple select without autocomplete input?

On mobile, focus will open keyboard and reduce the view you have.

**Comment by oyejorge** [comment]
We don't have a way to detect mobile and prevent the keyboard from opening. One approach for this could be to use the controlInput config. [For example](https://jsfiddle.net/L1yrg2e7/)

**Comment by Egorka** [comment]
Thank you,

controlInput config exactly what I was looking for.

**Comment by TomWFox** [comment]
This was just what I was looking for although there are some side effects when using `controlInput` in this way:

1. Setting the `<select>` to required doesn't work 
2. The `<select>` won't focus when tabbing through a form (or using arrows on iOS)

The second one is only a minor UX issue but the first is not ideal - although perhaps it could be validated in JS...
