### ISSUE TITLE
Cmd/Ctrl+A in Dropdown Input doesn't select text

### ISSUE THREAD

**Issue by patbenatar** [orchidjs/tom-select#251]
**Describe the bug**

When typing in the dropdown input, I'm unable to use cmd+a or ctrl+a to select all text typed into the input.

**To Reproduce**
1. Go to https://tom-select.js.org/plugins/
2. Click on the Dropdown Input example
3. Start typing
4. With the dropdown input still focused, hit cmd+a or ctrl+a

**Expected behavior**

I would expect this input to behave just like a normal text input: cmd+a or ctrl+a should select the text in the input.

**Additional context**
 - OS: Windows
 - Browser: Chrome
 - Version 95.0.4638.69
 - Device: Desktop

**Comment by oyejorge** [comment]
Should be all set with the above commit

**Comment by patbenatar** [comment]
Thanks @oyejorge ! I've been loving this library.
