### ISSUE TITLE
Change mouse cursor from `text` to `default`(=arrow)

### ISSUE THREAD

**Issue by ThomasLandauer** [orchidjs/tom-select#255]
**Describe the bug**
On hover, the widget shows a `text` mouse cursor. I'm reporting this as *bug*, since `text` should only be used for writing. But the initial click doesn't give a blinking text cursor, but expands the widget. So IMO the cursor should be either `default`(=arrow) or `pointer`.
I think it's happening in this line:
https://github.com/orchidjs/tom-select/blob/86135915416927b01cca5424bda605535b469abd/src/scss/tom-select.scss#L153

**Comment by oyejorge** [comment]
> But the initial click doesn't give a blinking text cursor

Hmm, I do see a blinking text cursor when I click in though

**Comment by ThomasLandauer** [comment]
Sorry, I started with Bootstrap 5 CSS right away, so I didn't ever see the default layout till I just investigated the Vue.js bug ;-)

So here's what I mean:

![cursor](https://user-images.githubusercontent.com/1054469/140739935-14c83212-6191-4145-a844-d50328e759ad.png)

In this situation, the *main* result of clicking is expanding the widget ("signaled" by the arrow at the right). Since a standard `<select>` looks exactly the same and shows the arrow cursor (I think it's called `default` in CSS) on hover, I would suggest to use the same, for consistency.

**Comment by oyejorge** [comment]
Instances of Tom Select are pretty different from standard ```<select>``` tags though and there is a blinking cursor when you click in. I think it's fine as is since it's easy to customize with a little CSS but open to changing it if others feel strongly about it.

**Comment by genachka** [comment]
@oyejorge awesome control! Thanks for making it and continuing to improve it. I'm coming from Select2, Choices.js, etc. and am using yours for the first time starting with v2 and also using the Bootstrap 5 CSS. For me, if the search is enabled on the control then it's fine to have the default "I" cursor (I would except an arrow cursor when it's just a dropdown though) except when you hover over the dropdown arrow I expect the cursor to change to an arrow and it's currently not but other such controls do including standard bootstrap behavior so would be great if you can support same?
