### ISSUE TITLE
Not working when Vue.js is started *after* Tom Select

### ISSUE THREAD

**Issue by ThomasLandauer** [orchidjs/tom-select#256]
**To Reproduce**
I tried to create a fiddle, but couldn't even get Tom Select to work :-( https://jsfiddle.net/f4jsau3c/
So here's a copy-pastable code:
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Tom Select</title>
        <link href="https://cdn.jsdelivr.net/npm/tom-select@2.0.0-rc.5/dist/css/tom-select.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/tom-select@2.0.0-rc.5/dist/js/tom-select.complete.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>
    </head>
    <body>
        <main>
            <select multiple="multiple">
                <option>One</option>
                <option>Two</option>
            </select>
        </main>
    <script>
        new TomSelect('select', {});
        let vue = new Vue({
            el: 'main'
        });
    </script>
    </body>
</html>
```
Here, Tom Select isn't working at all (Firefox + Chrome).

**Solution**
Move the `new TomSelect(...)` line *below* Vue.js.

If this can't be fixed (or is the expected behavior ;-) it should be documented somewhere at https://tom-select.js.org/

**Comment by oyejorge** [comment]
I'm not an experienced Vue user at all but, correct me if I'm wrong, it seems like this kind of conflict is not uncommon with Vue.js

**Comment by ThomasLandauer** [comment]
See https://github.com/orchidjs/tom-select/discussions/260#discussioncomment-1666971
