### ISSUE TITLE
Paste does not work

### ISSUE THREAD

**Issue by dmke** [orchidjs/tom-select#262]
**Describe the bug**

When pasting a value into a `<select/>` field, <kbd>Ctrl+v</kbd> does nothing.

I can hover start typing and the desired value appears as expected.

**To Reproduce**

- Copy `arnold`.
- Go to https://tom-select.js.org/examples/, scroll to the `<select> (allow empty)` example.
- Click into the select field (the dropdown appears with options "None", ..., "Arnold Schwarzenegger")
- Hit <kbd>Ctrl+v</kbd>. Nothing happens.

https://user-images.githubusercontent.com/327411/141461473-ea6c983d-afb8-4bde-98a8-830e0df90db9.mp4

**Expected behavior**

The value from the clipboard should be inserted, and Arnold Schwarzenegger should be suggested, so that I can confirm the selection with either <kbd>Enter</kbd> or by clicking on it.

**Additional context**

The culprit lies in `onPaste`:

https://github.com/orchidjs/tom-select/blob/86135915416927b01cca5424bda605535b469abd/src/tom-select.ts#L582-L585

where `isFull` checks whether `maxItems` is reached:

https://github.com/orchidjs/tom-select/blob/86135915416927b01cca5424bda605535b469abd/src/tom-select.ts#L2077-L2079

The behaviour I'd expect would be to either replace the current selection with the pasted value (and restoring it should I press <kbd>Esc</kbd>), or to not distinguish between ordinary key presses and pasting a value.

**Comment by dmke** [comment]
My current workaround is to simply mute `isFull`:

```js
class TomSelectWorkaround extends TomSelect {
  isFull() { return false }
}
```

One could overwrite `TomSelect.prototype.isFull = () => false`, however I'm not sure what kind of consequences this has for multi-selection fields.

**Comment by oyejorge** [comment]
Looks like we can remove the isFull() check in onPaste() without creating any problems. Thanks!
