### ISSUE TITLE
First item in dropdown is highlighted by default

### ISSUE THREAD

**Issue by ThomasLandauer** [orchidjs/tom-select#266]
**Describe the bug**
When opening the dropdown, the cursor bar is already placed on the first item (i.e. it *appears* to be selected, but in fact isn't).

**To Reproduce**
See the fiddle you created yourself (for another issue):
https://jsfiddle.net/am7wLgb3/
When clicking, the blue cursor bar is already on "One".

I tried these options, but both didn't change anything:
```js
placeholder: 'foo',
allowEmptyOption: true,
```

**Expected behavior**
When the user just *opens* the dropdown, nothing should be highlighted.

**Comment by oyejorge** [comment]
The highlighted item in the dropdown is an indicator of which item would be selected when a user hits the enter key on the keyboard.
