### ISSUE TITLE
Identify created item from existing ones on onItemAdd

### ISSUE THREAD

**Issue by EdouardPan** [orchidjs/tom-select#297]
Hello,

After reading documentation, I cannot figure out how to identify an item that was created (by the user with the option `create: true`) from the selection of an existing option by the user. Is there a way to distinguish these two situations during the callback?

Than you :)

**Comment by oyejorge** [comment]
A jsfiddle would be helpful to understand where you're getting stuck

**Comment by Alireza-Farahani** [comment]
Facing the same problem. I wan't to send a different request for adding/creaing item to existing options. When I print `$item` argument from `onItemAdd` I get this for created Item:
`<div class="item" data-value="new title" data-ts-item="">`
and this for existing options:
`<div class="item" data-value="4" data-ts-item="">`

Is there any way to distinguish between these two?

**Comment by EdouardPan** [comment]
Hello!

@Alireza-Farahani  precised my point: when you are in a onItemAdd callback, there is no way (to my knowledge) to distinguish an existing option to an option created by the user.

Is it enough clear?

**Comment by oyejorge** [comment]
I think this is what you're looking for:

```js
new TomSelect('#tom-select-input', {
    ....
    onItemAdd: function(value, item) {
        if( this.userOptions.hasOwnProperty(value) ){
          // item was created by user
        }else{
          // item created from existing option
        }
    }
}
```
