### ISSUE TITLE
Placeholder visible when a value is pre-selected

### ISSUE THREAD

**Issue by frnhr** [orchidjs/tom-select#30]
**Describe the bug**
Placeholder text is visible when dropdown has a selected value prior to plugin initialization.

**To Reproduce**
1. Go to https://tom-select.js.org/examples/
2. Scroll down to `<select> <option disabled>`
3. Notice that next to `Nikola Tesla` there is also `Select a person...` placeholder text visible.

**Expected behavior**
Dropdown has a selected value, therefore placeholder text should not be visible.

Continuing on the steps above, if you open the dropdown and click on `Nikola Tesla` option (so, just selecting again the option that is already selected), then the placeholder text goes away. The two states (on page load and after clicking the option) are the same, so the representation should also be the same, i.e. without the placeholder.

Perhaps this is not so straight forward for multi-select case, not sure what is the desired behavior there. But for single-select case, it is clear - selected value == hidden placeholder.

**Additional context**
 - OS: Mac 11.2
 - Browser Chrome
 - Version 88.0.4324.192 (Official Build) (x86_64)
 - Device: Macbook pro

**Comment by oyejorge** [comment]
The is actually the intended default behavior at the moment. Leaving it as is makes it easier to customize with plugins ([dropdown_input](https://tom-select.js.org/plugins/dropdown-input/) and [input_autogrow](https://tom-select.js.org/plugins/input-autogrow/)) or to use the [controlInput setting](https://tom-select.js.org/plugins/no-backspace-delete/).

**Comment by oyejorge** [comment]
Ok, this should be all set. The placeholder will be hidden for single-select but displayed for multi-select. Anyone can change/reverse this behavior with the hidePlaceholder setting.

Thanks!
