### ISSUE TITLE
Not working with class selectors (ex. ".select-tags")

### ISSUE THREAD

**Issue by diego-betto** [orchidjs/tom-select#306]
**Describe the bug**
Seems to work only if you use ID selectors (ex, '#select'), not if you use class selector ('.selects')

**To Reproduce**
https://codepen.io/bettodiego/pen/GRMMgwx

**Expected behavior**
Every input should show the component

**Comment by oyejorge** [comment]
Each instance of the TomSelect class can only represent one input. To create multiple instances using css class selectors, you can do the following.

```js
document.querySelectorAll(".select-tags").forEach((el)=>{
  new TomSelect(el,{
    persist: false,
    create: false,
  })
});
```

**Comment by diego-betto** [comment]
Oh, ok thank you.

So maybe can be a bit confusing if the selector in the docs shows "#...." if it is not a generic selector.
The ID without the '#' should be enough I think.

Thanks for your plugin e support.

**Comment by t-prod** [comment]
Hi,

Do you know how I can intitalize again a TomSelect component if I clone a line for instance ?
I try your script but I have a blank select when a new Select is displayed.

Laravel livewire is used with a wire:ignore directive. I try sync but it's not working.

Thanks for your help
