### ISSUE TITLE
Allow text selection when input type="text"

### ISSUE THREAD

**Issue by MarcProe** [orchidjs/tom-select#31]
When using autocomplete on `<input>`, after selecting a value that value gets "locked" and is no longer editable.

See: https://github.com/selectize/selectize.js/issues/256

The use case is for me that I want to choose from a set of given texts (these are from an OCR-engine and may be faulty), and then correct some letters or add something to the text.

**Comment by oyejorge** [comment]
It's not perfectly clear to me what's being requested here and in the selectize issue.

> The use case is for me that I want to choose from a set of given texts and then correct some letters or add something to the text.

So, choose from options in the dropdown then edit the text of the selected items. Does that sound right?

If that's the case, I'm wondering how you feel about this example: https://jsfiddle.net/me3j89d0/. Hitting the backspace key "removes" an item but keeps the text of the item so you can edit the text then re-add it.

**Comment by MarcProe** [comment]
Exactly that. Thank you so much!
