### ISSUE TITLE
sortField disable sorting sorts by value

### ISSUE THREAD

**Issue by greg098** [orchidjs/tom-select#310]
When following the docs to disable sorting, options are displayed in value order, not original order.

See: https://tom-select.js.org/docs#sortfield where is says "To disable sorting entirely and maintain the original order of options, use: sortField:()=>1"

Using:
tom-select Version 2.0.0
bootstrap version 5.1.3

User select input with option list:
```
   <select id="test2">
      <option value="4">AAA</option>
      <option value="3">BBB</option>
      <option value="2">CCC</option>
      <option value="1">DDD</option>
   </select>
   <script> new TomSelect("#test2", {sortField:()=>1 });  </script>
```

You expect to see the select list items in AAA, BBB, CCC, DDD order.
Instead the select lists items in DDD, CCC, BBB, AAA order, i.e. sorted by value.

Confirmed on Safari 15.2 and Chrome 96

Maybe just a documentation change to use "sortField: {}"?

PS: Nice work, I like it. You seem have the only alternate select I have found that will work correctly on BS 5.1 as is.

**Comment by oyejorge** [comment]
Looks like `sortField:()=>1` isn't going to work in all cases. To maintain the original sorting order, use this instead:

```js
sortField:[{field:'$order'},{field:'$score'}]
```

**Comment by greg098** [comment]
That works well, thank you.  

Maybe update the documentation  https://tom-select.js.org/docs#sortfield where is says "To disable sorting entirely and maintain the original order of options, use: sortField:()=>1" to instead say "sortField:[{field:'$order'},{field:'$score'}]" ??
