### ISSUE TITLE
using removeOption(), can't sync back to original options

### ISSUE THREAD

**Issue by makayabou** [orchidjs/tom-select#312]
I want to change the options of a Select, depending on the choice made on another select.   

I use removeOption(value) to get rid of an option, but when I try to use sync(), deleted option doesn't come back, although I still can see it in <select\> html.   
  
```   
const tiers_select = new TomSelect('#selectbox_parcours_tiers', settings);
const other_partners_select = new TomSelect('#selectbox_parcours_partners', settings);

tiers_select.on('change', () => {
    other_partners_select.sync();
    other_partners_select.removeOption(tiers_select.getValue());
});
```    

Here is a jsfiddle that reproduce the bug [https://jsfiddle.net/makayabou/co95pwaL/](https://jsfiddle.net/makayabou/co95pwaL/)

**Comment by oyejorge** [comment]
Not a bug
```js
var settings = {
    allowEmptyOption: true, 
    //valueField: 'id', <--- this was set incorrectly
    //labelField: "description", <--- this was set incorrectly
};
```
