### ISSUE TITLE
with `maxItems` set to `null` it's impossible to have an empty select by default

### ISSUE THREAD

**Issue by diego-betto** [orchidjs/tom-select#314]
**Describe the bug**
As the title, it seems that the first option is always selected,  also with `allowEmptyOption`

**To Reproduce**
https://jsfiddle.net/diegobetto/xjcp6gz8/2/

**Expected behavior**
An empty select with just the placeholder text

Thank you

**Comment by makayabou** [comment]
You need to use a void `<option></option> , and get rid of `allowEmptyOption` and `maxItems`.

See https://jsfiddle.net/makayabou/pwbgkejo/22/

**Comment by oyejorge** [comment]
The problem is with the underlying select.

In the given jsfiddle, the html select only allows for one selected option. In this situation, the first option is selected.
```html
<select ... >
        <option value="">Select...</option>
	<option value="4">Thomas Edison</option>
	...
```

Change the html to the following. With a "multiple" select, the first option won't be selected.
```html
<select ... multiple>
        <option value="">Select...</option>
	<option value="4">Thomas Edison</option>
	...
```
