### ISSUE TITLE
Placeholder does not work with dropdown_input and remove_button plugins

### ISSUE THREAD

**Issue by IvanBoichuck** [orchidjs/tom-select#32]
Placeholder does not work with dropdown_input and remove_button plugins

My code:
`document.querySelectorAll('.filter__select').forEach(element => {`
`new TomSelect(element, {`
	  `plugins: ['remove_button','dropdown_input'],`
	  `sortField: 'text',`
  `});`
`});`

**Comment by oyejorge** [comment]
Fixed with that last commit. Thanks Ivan!

**Comment by IvanBoichuck** [comment]
Thank you, very cool plugin !
