### ISSUE TITLE
Virtual scroll - keeps jumping to top when using keyboard

### ISSUE THREAD

**Issue by fisharebest** [orchidjs/tom-select#320]
**Describe the bug**

When scrolling through data using the *mouse*, new data is loaded and the scroll-position remains the same.  This is the behaviour I would expect.  But when using a *keyboard*, when new data is loaded, the scroll-position jumps to the top.

**To Reproduce**

Visit https://tom-select.js.org/plugins/virtual_scroll/
Type something into the search box.  e.g "fish".
Use the down-cursor key on the keyboard repeatedly.
Here's a video:

https://user-images.githubusercontent.com/2306088/150551952-96a240fe-37f7-4f17-aa86-91981dfc1d5f.mov

**Expected behavior**

After loading more options, the scroll-position should remain the same - just as it is when using a mouse.

**Additional context**

 - OS: OSX 10.15.7
 - Browser: Firefox
 - Version: 96
 - Device: Mac

**Comment by VirgileZol** [comment]
The bug is still here,
even using the mouse

**Comment by claygriffiths** [comment]
Can confirm this happens with mouse scrolling as well. Pinning the version to `2.0.2` resolves the issue.

**Comment by Alex-Sichkar** [comment]
By the way, the issue can be reproduced on the plugin demo page for the latest version (2.4.3) available here: https://tom-select.js.org/plugins/virtual_scroll/
