### ISSUE TITLE
this.clearOptions() on onDropdownOpen() no longer reloads remote data

### ISSUE THREAD

**Issue by seabasss** [orchidjs/tom-select#338]
**Describe the bug**
In an earlier version of Tom Select remote data was reloaded if `this.clearOptions()` was run on `onDropdownOpen()`, but that doesn't happen anymore. Is there a new way to do this?

It seems to work up until version `v2.0.0-rc.5` and in the `v2.0.0` release it stopped working.

**To Reproduce**
```
onDropdownOpen: function() {
    this.clearOptions();
},
```

**Expected behavior**
Remote data should be reloaded every time the dropdown is opened.

**Comment by oyejorge** [comment]
Seems to work from what I can see. Can you can put together a JSFiddle, CodePen or similar to demonstrate the problem?

**Comment by seabasss** [comment]
Will do tomorrow. Are you trying it with load()? I get ”no results” when i open the dropdown a second time so it’s clearing the list but no new network request is happening to fetch the remote data again. Thanks!

**Comment by oyejorge** [comment]
Any chance of getting a jsfiddle?

**Comment by seabasss** [comment]
Sorry, never got to it. I’ll try to make one the next few days! Thanks!

**Comment by seabasss** [comment]
Not sure it's the pretties solution, but I solved it by adding `this.load();` and now my options always reloads from the remote when I open the dropdown. Let me know if there's a better way.

```
onDropdownOpen: function() {
    this.clearOptions();
    this.load();
},
```

**Comment by ytilotti** [comment]
Hi all, a little question but with virtual_scroll an idea to reset the next page? Because the answer's @seabasss is good but need more with virual_scroll.

**Comment by ytilotti** [comment]
After some research & tests, there is a problem with virtual scroll with the code of @seabasss.
The code necessary with a virtual scroll:
```
onDropdownOpen = function() {
  this.clearOptions();
  this.getUrl('__forceToClear');
  this.load('');
};
```
The string `__forceToClear` is arbitrary. A public `clearPagination()` function on the virtual_scroll plugin would be required!
