### ISSUE TITLE
Typescript error 'item' is declared but its value is never read' (very quick to fix :P )

### ISSUE THREAD

**Issue by siamakmontazer** [orchidjs/tom-select#343]
**Describe the bug**
Stenciljs project can not build a component with tom-select as there is a typescript error in sifter.ts file

**To Reproduce**
1. Create a stencil component
2. Import tom-select and create TomSelect instance
3. Run "npm run build"
4. See the following error and stencil build fails
`TypeScript: ./node_modules/@orchidjs/sifter/lib/sifter.ts:347:25
           **'item' is declared but its value is never read.**

    L346:  } else {
    L347:       iterate(self.items, (item:T.ResultItem, id:string|number) => {
    L348:               search.items.push({'score': 1, 'id': id});
`

**Comment by oyejorge** [comment]
> very quick to fix :P

Awesome! Would you mind making a pull request on the sifter project?

**Comment by oyejorge** [comment]
Oops, there was already a pull request for that

**Comment by Wait4Code** [comment]
hey, i've just foudn a related issue : there are still typescript errors in sifter.ts file : 
_Type 'string | undefined' is not assignable to type 'string | null'_ (sifter.ts:63:5)
_Type 'string | undefined' is not assignable to type 'string'._ (sifter.ts:64:5)
_Object is possibly 'undefined'_ (sifter.ts:265:12)
_Object is possibly 'undefined'_ (sifter.ts:275:15)

Obviously, it is not the right repo to fix them. But, even if i'm far from being an expert of Typescript, I think that in `tom-select.d.ts` you should not import Sifter from lib files but from dist files :
`import Sifter from '@orchidjs/sifter/dist/sifter';`
(or `import Sifter from '@orchidjs/sifter'` -- not sure what's the difference between them)

At least, this tweak works in my project.

**Comment by oyejorge** [comment]
If this is a problem, please open a new issue or pull request
