### ISSUE TITLE
First option is always selected

### ISSUE THREAD

**Issue by elanclarkson** [orchidjs/tom-select#345]
**Describe the bug**
The first option is always selected even though the input value is empty. This is indicated by the aria-expanded attribute on the first option being set to true, and the active class being present despite there not yet being any values in the input.

**To Reproduce**
1. Go to https://tom-select.js.org/examples/
2. Scroll down to the second example labeled '\<select\>'
3. Click the select menu
4. See Arnold Schwarzenegger is selected even though value is empty 

**Expected behavior**
The first option should not be selected by default if it is not present in the input. This would be the case if no default values have been specified and allowEmptyOption isn't set to true.

Hopefully I've explained that well and haven't misunderstood the intended behaviour, but in any case thanks so much for this great plugin!

**Comment by oyejorge** [comment]
Duplicate #266
