### ISSUE TITLE
destroy() not working as espected when loading select element from ajax call

### ISSUE THREAD

**Issue by mvxproject** [orchidjs/tom-select#346]
when loading a select element from Ajax call, and initialization new TomSelect object, the old options of the select are preserved.

```
mvx.ready(function () {
    if (tomselectcountry2)
        tomselectcountry2.destroy();
    
	tomselectcountry2 = new TomSelect('#country2'), { });
});
```

In the destroy function, if I comment the line

` self.input.innerHTML = revertSettings.innerHTML;`

The new options are displayed as expected.

Is it possible to add a boolean parameter to the function for preserving innerHtml or not.

```
destroy(preserve) {
	    var self = this;
	    var revertSettings = self.revertSettings;
	    self.trigger('destroy');
	    self.off();
	    self.wrapper.remove();
            self.dropdown.remove();
            if (preserve) {
	           self.input.innerHTML = revertSettings.innerHTML;
            }
	    self.input.tabIndex = revertSettings.tabIndex;
	    removeClasses(self.input, 'tomselected', 'ts-hidden-accessible');

	    self._destroy();

	    delete self.input.tomselect;
	  }
```

 
Thanks.

**Comment by oyejorge** [comment]
This is more of a feature request than a bug. (note feature requests [go here](https://github.com/orchidjs/tom-select/discussions/categories/ideas])

Also, I suspect the best approach here is to update the existing Tom Select instance instead of destroying and re-initializing.
