### ISSUE TITLE
Select Multiple: Selecting a choice should also remove search term

### ISSUE THREAD

**Issue by SFr682k** [orchidjs/tom-select#348]
### Steps to reproduce
Reproducible with the `<select multiple>` example at https://tom-select.js.org/examples/

1. Click on the input. The popup opens.  
   ![01](https://user-images.githubusercontent.com/23553692/158033902-79278570-a342-4ba7-ac34-4f1ac21b7286.png)
2. Enter some letters (“alab”).  
   ![02](https://user-images.githubusercontent.com/23553692/158033903-403d0e48-6370-4695-8a9f-13b500c16656.png)
3. Select an entry (“Alabama”).  

### Observed behavior
 - “Alabama” is selected
 - The input still contains the search term “alab” and searches for it

![03](https://user-images.githubusercontent.com/23553692/158033905-5688f9c5-7f3f-49db-89c6-7520a9aa1fd7.png)

### Expected behavior
 - “Alabama” is selected
 - The search term “alab” is removed and the popup shows a list of remaining choices

### Additional information
 - OS: Linux (Debian 11)
 - Browser: Firefox ESR 91.6.0
 - Tom Select 2.0.1

**Comment by jvosloo** [comment]
Not sure if it's a bug or not, but I'm also interested in having the search term removed on multi options select

**Comment by oyejorge** [comment]
Right, this isn't a bug. See #22 for more info. Here's the code for making it work the way you want

```
new TomSelect("#input-tags",
   { onItemAdd: function(
   { this.setTextboxValue('');
   this.refreshOptions(); } 
});
```

**Comment by SFr682k** [comment]
Thanks for the explanation!

Would it be possible to add the code from above to the documentation?  (Unless its already there and I missed it.)  In my opinion, that would come in handy for users who migrate to Tom Select from other libraries which behave differently.  A suitable place might be the [“Basic Examples” page](https://tom-select.js.org/examples/).
