### ISSUE TITLE
Unable to sync or to recreate a Tom Select with classname

### ISSUE THREAD

**Issue by t-prod** [orchidjs/tom-select#351]
Hi,

**Describe the bug**
I try to create dynamically a TomSelect instance. The first is working but when I create an other one it does not works.

**To Reproduce**
![image](https://user-images.githubusercontent.com/1824638/159870868-506161e7-bd1d-45ed-b77b-f011720bbaa9.png)

I'm using Livewire and when I add an other line, this is the code :

```
window.addEventListener('lineAdded', (e) => {
        document.querySelectorAll('.select-results').forEach((el)=>{
            new TomSelect(el,settings);
            console.log(el);
        });
    })
```

Error :
![image](https://user-images.githubusercontent.com/1824638/159871229-2c67668a-315c-43a1-a824-762efa0900c3.png)

Is it impossible to use TomSelect with class name cause I can have several lines in my app ?

Thanks for your answer

**Comment by oyejorge** [comment]
Appreciate the screencaps and code snippet, but without a complete reproducible example (on jsfiddle or similar), there's not much I can do. 

Your error message indicates "Tom Select already initialized on this element" which doesn't necessarily indicate a bug and may just be a problem with your implementation.

**Comment by t-prod** [comment]
I understand it is just the fact  to refresh or rebuild each Tom Select. Do you have an idea ?

**Comment by aymanalhattami** [comment]
@t-prod  Is there any solution for this.
I have the same problem

**Comment by tb-mtg** [comment]
I have same problem also.
