### ISSUE TITLE
Same Tom Select Configuration not supported in multiple select inputs

### ISSUE THREAD

**Issue by dhanar98** [orchidjs/tom-select#353]
**Describe the bug**
When I apply the same tom-select configuration for multiple select inputs. it didn't accept.

**To Reproduce**
[JSFIDDLE](https://jsfiddle.net/jo7q1wrx/12/)

**Expected behavior**
The Same need to apply to all the select input fields.

**Comment by oyejorge** [comment]
Each instance of TomSelect can only be associated with a single input/select. See https://jsfiddle.net/0kt5vhws/
