### ISSUE TITLE
Options are incorrectly given active class when data is set via settings

### ISSUE THREAD

**Issue by PatrickSJ** [orchidjs/tom-select#355]
**Describe the bug**
When options are added via settings if you have multiple TomSelect instances referencing the same settings then the active class incorrectly set.

**To Reproduce**
See https://jsfiddle.net/p3kgdxtn/ for example.

1.  For the first option select Cat
2. For the second option notice that Bird & Cat are active.  Select Dog
3. For the third option notice that Bird, Cat, and Dog are active.  Select Fish
4. Re-select the first option.  Notice that Cat, Dog, and Fish are active.

**Expected behavior**
There should only be 1 option that is active.  The option selected in a different TomSelect instances should not be showing as active.

**Additional context**
This only happens when the same set of options / settings is referenced.  The problem does not occur if a deep clone of the settings is made.

**Comment by PatrickSJ** [comment]
I would say that yes, it is a bug.  From what I see the options passed upon initialization are then associated with a generated id, e.g., select3-opt-1.  That same ID is then _shared_ amongst all of the TomSelect elements.  So select1-ts-dropdown now has options select3-opt-1 through select3-opt-5.

Would this be resolvable by removing the active class from options that don't also have the selected class upon the dropdown opening?

Also, since this was a fork of selectize do you happen to know what was done there to prevent this issue?

**Comment by oyejorge** [comment]
> Also, since this was a fork of selectize do you happen to know what was done there to prevent this issue?

Selectize deep cloned everything

> Edit: Is it the option caching that causes this?

No. It's because JavaScript passes arguments with "[call by sharing](https://bambielli.com/til/2016-02-15-javascript-call-by-sharing/)"

**Comment by oyejorge** [comment]
[Added third possible solution](https://github.com/orchidjs/tom-select/issues/355#issuecomment-1096910912)

**Comment by PatrickSJ** [comment]
Found a workaround whilst using a shared configuration object.  

```
const parameters = {
	options: [
		{ value: 1, text: 'Bird' },
		{ value: 2, text: 'Cat' },
		{ value: 3, text: 'Dog' },
		{ value: 4, text: 'Fish' },
		{ value: 5, text: 'Hamster', },
	],
	onFocus: function () { this.clearCache() }
}
```
