### ISSUE TITLE
sync() was not remove un-exists options

### ISSUE THREAD

**Issue by asika32764** [orchidjs/tom-select#362]
**Describe the bug**

Use `sync()` on tom-select but not remove some options which is not exists on select element.

**To Reproduce**

See gif 

![tomselect](https://user-images.githubusercontent.com/1639206/165795434-bbddf84c-132c-4c0d-a70f-8dc94afb93f3.gif)

And JSFiddle
https://jsfiddle.net/z30uh1cv/3/

Just click "Remove B and sync" button, you will see the "B" options still exists in TomSelect dropdown list.

**Expected behavior**

Should remove the non-exists options.

**Additional context**
 - OS: Windows
 - Browser Chrome
 - Version 100.0.4896.127
 - Device: PC

<!--
Thanks for taking the time to submit your bug report,
and don't forget to star our repo!

**Comment by oyejorge** [comment]
I think we may need to update the docs for sync() rather than change how it works. 
To get the desired behavior, use clearOptions() like so https://jsfiddle.net/abo16qpc/

**Comment by asika32764** [comment]
clearOptions() will keep the currently selected option, and the doc says that we must use clear() to clear selected option.

But sometimes we may need a case:
- Change select options by JS (May remove or add some options)
- make an option selected
- Sync TomSelect with new options and new selected option.

If we run this way

```js
tom.clear();
tom.clearOptions();
tom.sync();
```

This will lose the selected option which we did by JS.

**Comment by asika32764** [comment]
https://jsfiddle.net/abo16qpc/ is not enough to my case. If we select B first, this option won't be removed.

![tomselect2](https://user-images.githubusercontent.com/1639206/165811061-747732fa-35cf-4035-8465-91c647d81df6.gif)

**Comment by oyejorge** [comment]
Then don't remove the option if it's selected: https://jsfiddle.net/rt75uoxf/

**Comment by asika32764** [comment]
No. To the most cases, users will expect that if they select an option first, and the list changed, the behavior will be:

- If selected option exists in new list:
    - keep selected option
- If selected option not exists in new list:
    - clear selected option and be empty or select first of new list

This behavior is similar to native select element.

But now, there is no way to implement this for tom-select

**Comment by oyejorge** [comment]
> But now, there is no way to implement this for tom-select
Ok, so you're not sure how to approach this problem. There are a number of ways to do this but here's what I would do https://jsfiddle.net/qmho9txe/3/

**Comment by asika32764** [comment]
Yes I see you extends a CustomSelect from TomSelect. This is a hack way.

So could TomSelect support an official way (maybe `syncOptions()`) to implement this? I think this is a general usage for many cases.

**Comment by oyejorge** [comment]
Since this is new functionality we need two things:

1) I think we need to consider whether or not this functionality should be (a) added to the core, (b) added as a plugin, or (c) left as-is where users can implement the functionality with the bit of code in the jsfiddle above.

Adding it depends on the edge case described above where an end-user has a selected option which is then removed from the option list by the program being used. Seems like there should be some prompt/notice to the end user when removing already selected options but that is outside of our scope.

2) If there are enough users who want this added, we then need unit and/or functional tests

**Comment by asika32764** [comment]
Delete a selected option and make selected as the first option is a known behavior on native select input. This will not be a wired thing for users as my opinion.

See https://jsfiddle.net/asika32764/dy7L9uwo/

![select](https://user-images.githubusercontent.com/1639206/166923390-02a9740f-5f20-451e-9d1e-c0760bf214a9.gif)

Maybe a param that developer can choice:

```
syncOptions(keepSelected = false)
```

**Comment by oyejorge** [comment]
Hmm, I don't think the above solution would work for &lt;input&gt; tags

**Comment by SucheG** [comment]
in with multiple options:
it can be useful if you dynamicly update options but
you want keep already selected values

**Comment by asika32764** [comment]
I agree that keep selected options is an important experience in some UI component.

But we need a way to implement the behavior that same with the native `<select>` element, this should be a basic function, and if some developers do not want this, just provide an option to toggle this behavior.

Currently there is no hack way  to implement it.

**Comment by oyejorge** [comment]
Anyone try the new clearOptions() callback? It seems like the solution is there and we can close this issue.
