### ISSUE TITLE
Items settings not working when using Remote Data

### ISSUE THREAD

**Issue by michele-grifa** [orchidjs/tom-select#363]
**Describe the bug**
I'm using remote data to populate a select, with a little subset of data when is instantiated, and works perfectly. But when i try to set the items property, the select don't show the pre-selected value.
If i use the options property instead of the remote data, it works as intended.

**Expected behavior**
When setting the items property, should display the pre-selected value.

**To Reproduce**

- Go to [jsFiddle](https://jsfiddle.net/8vmteu3w/3/)
- Click on the select
- The item with value '0320000' should be selected but is not

**Additional context**
 - Browser Firefox 97.0.1
 - Version 2.0.0

**Comment by michele-grifa** [comment]
> 

Thanks for the explanation. 

Off-topic: is there a way to manually reload the select, i tried the load method but not work. I'm trying to create two dependants selects that loads from remote data, only when the first has a selected item.

**Comment by timmyd87** [comment]
@michele-grifa I'm having the same problem, did you come up with a preferred solution for this?

**Comment by michele-grifa** [comment]
> @michele-grifa I'm having the same problem, did you come up with a preferred solution for this?

This is my solution.

```javascript

select.on('load', function (value, item) {
                select.setValue('pre-selectedvalue')
            });
```

**Comment by timmyd87** [comment]
Thank you so much!!

**Comment by typo3ua** [comment]
> > @michele-grifa I'm having the same problem, did you come up with a preferred solution for this?
> 
> This is my solution.
> 
> ```js
> select.on('load', function (value, item) {
>     select.setValue('pre-selectedvalue')
> });
> ```

Hi! @michele-grifa ... where I should d to add this code? Can you provide the code full your solution?
