### ISSUE TITLE
Bootstrap 5.x form validation classes are not applied/displayed

### ISSUE THREAD

**Issue by joostdebruijn** [orchidjs/tom-select#364]
**Describe the bug**
For Bootstrap 5.x, the form validation classes are not applied as described here: https://getbootstrap.com/docs/5.1/forms/validation.

**To Reproduce**
1. Create a form which supports the custom validation classes as described here: https://getbootstrap.com/docs/5.1/forms/validation/#custom-styles.
2. Make a required TomSelect.
3. Submit the form without entering something in the required select.
4. The select will not marked as invalid.

**Expected behavior**
I expect the `is-valid` / `is-invalid` will be applied and displayed correctly.

**Additional context**
 - OS: Windows 11 (22000.651)
 - Browser Chrome 100.0.4896.127
 - Version: tom-select v2.0.1
 - Device: Desktop

**Comment by oyejorge** [comment]
> Create a form which supports the custom validation classes as described here: https://getbootstrap.com/docs/5.1/forms/validation/#custom-styles.

Anyone care to create an exmple on jsfiddle or similar?

**Comment by joostdebruijn** [comment]
Sure, will do!

**Comment by joostdebruijn** [comment]
@oyejorge I've created one here: https://jsfiddle.net/vdw9oy5u. If you submit the form (without selecting something), you'll see the difference between a validated native select and a validated TomSelect with Bootstrap 5 styling. Let me know, if I can help you with more information.

**Comment by oyejorge** [comment]
That was fast, thanks!
