### ISSUE TITLE
Select uses wrong Bootstrap 5 variables for padding

### ISSUE THREAD

**Issue by zipper** [orchidjs/tom-select#367]
**Describe the bug**
In Bootstrap 5, there are padding variables `$input-btn-padding-y` and `$input-padding-y`. By default, the later has default value of the first one. In Tom Select sources for Bootstrap 5 theme, the `$select-padding-y` is set to `$input-btn-padding-y`, but when the `$input-padding-y` is set differently, Tom Select is rendered wrong (eg. pills in multi select are not properly vertically centred).
https://github.com/orchidjs/tom-select/blob/0821f1980fed35e92948507b9bff9a9093ba5762/src/scss/tom-select.bootstrap5.scss#L43-L44

**To Reproduce**
Use Bootstrap 5 theme, where `$input-padding-y` has value different from `$input-btn-padding-y`. The multi select would have its active items not vertically centred.

**Expected behavior**
A default value of `$select-padding-y` should be `$input-padding-y`. Analogically for the `x` variable.
```scss
 $select-padding-x: $input-padding-x !default; 
 $select-padding-y: $input-padding-y !default; 
```

<!--
Thanks for taking the time to submit your bug report,
and don't forget to star our repo!

**Comment by oyejorge** [comment]
Thanks for checking, I think we're ok leaving that as-is.
