### ISSUE TITLE
Strange zoom on focus on iOS

### ISSUE THREAD

**Issue by joeyave** [orchidjs/tom-select#369]
**Describe the bug**
When focusing on field on iPhone it zooms. HTML tag is select.

https://user-images.githubusercontent.com/48005710/166589154-a2e35c52-227b-4a5e-b121-ca2a12e0f67f.mp4

```
var settings = {
        plugins: ['remove_button', 'input_autogrow'],
        create: true,
        // createFilter: /^\p{Lu}\p{Ll}+( \p{L}+)*$/gmu,
        placeholder: "Добавить тег"
    };
    new TomSelect('#tags',settings);
```

**Comment by oyejorge** [comment]
Might be this
https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone

**Comment by joeyave** [comment]
Increasing font size for .ts-dropdown, .ts-control, .ts-control and .input resolved the issue.

**Comment by apphancer** [comment]
I can confirm the issue is caused by Safari's autozoom.

https://weblog.west-wind.com/posts/2023/Apr/17/Preventing-iOS-Safari-Textbox-Zooming#:~:text=Once%20an%20input%20field's%20absolute,you%20started%20building%20your%20app.

> OS triggers auto-zoom when the absolute, rendered text size of an input field is less than 16px

It can be fixed as follows:

```css
.ts-control input, .ts-control .item {
    font-size: 16px;
}
```
