### ISSUE TITLE
Ignore duplicate option

### ISSUE THREAD

**Issue by THenkeDE** [orchidjs/tom-select#371]
**Describe the bug**
When i set "duplicates: false" in options i can not have the same option more than once but if i set "create: true" in the options, too, i can manually add a duplicate.

**Expected behavior**
it won't let me add an already present option

To help myself i added a Filter

```
            createFilter: function( optionValue ){
                return !this.options[optionValue];
            },
```

but i think TS should consider the duplicates option automatically

**Comment by oyejorge** [comment]
Could you provide a full example on jsfiddle or similar? I'm not able to reproduce the problem you describe. [For example](https://jsfiddle.net/y8no3t97/)

**Comment by THenkeDE** [comment]
@oyejorge sure thing, [my fiddle](https://jsfiddle.net/a9jsr27p/1/)

I think it has something to do with the disabled options, so it basically does not add a duplicate but does not count disabled options in.

Maybe it is just as simple as this

**Comment by oyejorge** [comment]
I see. [Here's a stripped down fiddle](https://jsfiddle.net/oj4fb5ey/1/)

**Comment by oyejorge** [comment]
Thanks!
