### ISSUE TITLE
Bootstrap form validation issue with two instances

### ISSUE THREAD

**Issue by JerryBels** [orchidjs/tom-select#375]
**Describe the bug**
So I'm dynamically filling options using AlpineJS, depending on another select. After looking around, I found the `sync, `clear` and `clearOptions` that allowed me to get this working. But the bootstrap 5 validator is buggy and I can't understand why. Both selects are `required`, but if the first has a selected option both will be marked as valid by bootstrap - even though the form won't submit since the second isn't actually valid, since it's empty.
Of course if I simply remove Tom Select from the second one, everything works fine with the native select element.

**To Reproduce**
Create an example on JSFiddle, CodePen or similar service and outline the steps for reproducing the bug.
1. Go to https://codepen.io/JerryBels/pen/rNJMrMz
2. click the validate button. The form appears as invalid.
3. Click on the first select and choose one or more languages
4. Don't choose a language in the second select box after they appeared in it
5. See that bootstrap marks both as valid
6. Also, if you click again on the validate button, the form still won't be submitted.

**Expected behavior**
The second select should be marked as invalid - it is with the native select.

Thank you for this really awesome repo, I'm really glad I found it!

**Comment by oyejorge** [comment]
Dang, I had the wrong css selector in there. 
Thanks!

**Comment by JerryBels** [comment]
Cool :) do you know when the next stable version will release§

**Comment by oyejorge** [comment]
I don't have a date set but it should be soon. If you need a fix fast you
could wrap each of your selects in div or span:
<div><select>...</select></div>
