### ISSUE TITLE
Bootstrap 5 bug with checkbox since v2.0.1

### ISSUE THREAD

**Issue by james-em** [orchidjs/tom-select#380]
Bug is only present with Boostrap 5 theme.

v2.0.0
![Screen Shot 2022-05-17 at 12 32 38 PM](https://user-images.githubusercontent.com/63726983/168862607-920663d0-6fd7-4e6e-bdff-8b7de116f938.png)

v2.0.1 and v2.0.2
![Screen Shot 2022-05-17 at 12 33 03 PM](https://user-images.githubusercontent.com/63726983/168862659-92105344-77ff-47cb-b5f3-745cb970affc.png)

Normal checkbox is fine (when is-valid class not present).

HTML sample

```
<fieldset class="mb-3 boolean optional page_disable_indexing">
   <div class="form-check"><input name="page[disable_indexing]" type="hidden" value="0" autocomplete="off">
      <input
         class="form-check-input is-valid boolean optional" type="checkbox" value="1" checked="checked"
         name="page[disable_indexing]" id="page_disable_indexing">
      <label class="form-check-label boolean optional" for="page_disable_indexing">Disable indexing</label>
   </div>
</fieldset>
```

**Comment by oyejorge** [comment]
Screenshots are great but unless I can see the problem on a live example, there's not much I can do.

Here's what I can see at https://tom-select.js.org/plugins/checkbox-options/#checkbox-options.
![Screenshot from 2022-05-17 10-38-27](https://user-images.githubusercontent.com/1043524/168863801-585368a1-4f44-441b-944d-607aaec91075.png)
