### ISSUE TITLE
Invalid event fires on initialization of required select

### ISSUE THREAD

**Issue by jclusso** [orchidjs/tom-select#388]
**Describe the bug**
Required selects trigger the window invalid event 4 times on creation of the select.

**To Reproduce**
When the page loads the invalid event is fired 4 times.
<img width="878" alt="image" src="https://user-images.githubusercontent.com/622516/170398334-c0150d23-45a1-4b29-aa59-69f3ffedd9ef.png">
https://jsfiddle.net/vsm5nt3x/

**Expected behavior**
The invalid event should not fire on initialization of required selects.

**Comment by oyejorge** [comment]
Hmm, not sure there's anything we can do to prevent this entirely. Any time input.checkValidity() returns false, that event will be fired. See https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/invalid_event

**Comment by oyejorge** [comment]
We could get it down to two events fired by adding a check for `isSetup`
```js
refreshValidityState() {

	if( !this.input.checkValidity ) return;
	if( !this.isSetup ) return; 
	
	this.isValid = self.input.checkValidity();
	...


```

**Comment by jclusso** [comment]
@oyejorge I don't know much about how this works. How do other custom select plugins deal with this?

**Comment by oyejorge** [comment]
It appears other select plugins don't check the validity of inputs with JavaScript. Any styling is accomplished using the `:invalid` css selector

**Comment by jclusso** [comment]
@oyejorge is there something that tom-select can't do using the `:invalid` selector or is that a feasible solution?

**Comment by oyejorge** [comment]
It can't set the TomSelect.isValid variable

**Comment by oyejorge** [comment]
[Looks like there's a better way](https://stackoverflow.com/questions/46263522/difference-between-checkvalidity-validity)

**Comment by jclusso** [comment]
Nice! That makes sense.
