### ISSUE TITLE
Invalid layout for input group 

### ISSUE THREAD

**Issue by laurentmuller** [orchidjs/tom-select#401]
**Invalid layout for input group**
Using input group style, the button on the left and right are not aligned when texts are in multiple lines. 

**To Reproduce**
- Create a select list within a input group.
- Add a left and right button.
- Enter multiple values so in take more than 1 line.
- The buttons are not aligned as picture below:

![image](https://user-images.githubusercontent.com/4330059/174534039-52466fd2-b15e-4c9f-8162-0c03b1eaaeea.png)

**Expected behavior**
The buttons must be aligned.

**Comment by oyejorge** [comment]
Adding nowrap to the input-group to would fix it but that changes the bootstrap defaults

```css
.input-group {
  flex-wrap: nowrap;
}
```

**Comment by bazineta** [comment]
It's possible to add the BS `flex-nowrap` style to the `input-group` in the markup, e.g., `<div class="input-group flex-nowrap></div>`; that'll at least look decent.

**Comment by oyejorge** [comment]
Thanks, that seems like an appropriate solution.
