### ISSUE TITLE
diacritics search

### ISSUE THREAD

**Issue by oyejorge** [orchidjs/tom-select#407]
### Discussed in https://github.com/orchidjs/tom-select/discussions/402

<div type='discussions-op-text'>

<sup>Originally posted by **athagiorgos** June 20, 2022</sup>
Hi, hope you all doing well. I have a small problem when using tom select for searching areas in my website. everything works well, but the problem when searching with greek characters. For example i want to search an area, and i have to add the diacritics to the respective letter otherwise tom sleect says no results found although it does have data behind the scenes. So if I type the greek ε without the diacritic, tom select will only match all ε letters like this but i want it to search for this letter with diacritic on top, like έ. Is there any solution to this? I tried adding the diacritics option and turning it from true to false but that didn't do anything.
  </div>

**Comment by athagiorgos** [comment]
I have found a way around this. Because i cannot do anything when tom select searches for diacritics, i wanted to turn off automatic search so it could display me all the data that came from my API. So setting searchField: [] to an empty array actually stops tom select from trying to search specific fields and also compares the diacritics. However you lose the highlighting feature but it's a minor thing now that I can search correctly, because i am performing the search at my API, and have the results.

**Comment by oyejorge** [comment]
Fixed with https://github.com/orchidjs/tom-select/commit/43c91b08bb2a76b6d91f1c9b180c412299c5fcc3

**Comment by cuu508** [comment]
I noticed that the first time the options are filtered in a Tom Select instance there is a noticeable delay before the dropdown with filtered options appears. I have `refreshToggle: 0` set already. After the first hiccup the followup filtering runs are quick. The initial delay seems to roughly the same for selects with a few options, and selects with several hundred options. The delay disappears if I set `diacritics: false` in the options.

I'm testing on Firefox 151. Here's a screenshot from a profiling report, the yellow chunk in the timeline is from around when I enter the first character.

<img width="3840" height="1984" alt="Image" src="https://github.com/user-attachments/assets/9d1f6338-c6a7-4157-8f8d-92507cdeebd9" />

Is this working as intended? Does diacritics support require some expensive one-time initialization?

**Comment by NicolasCARPi** [comment]
@cuu508 what's the code doing this?

**Comment by cuu508** [comment]
Here's a minimal example:

```html
<!DOCTYPE html>
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/tom-select/dist/css/tom-select.css" rel="stylesheet">
</head>
<body>
    <select>
        <option>Foo</option>
        <option>Bar</option>
    </select>
    <script src="https://cdn.jsdelivr.net/npm/tom-select/dist/js/tom-select.complete.js"></script>
    <script>
        new TomSelect("select", {refreshThrottle: 0});
    </script>
</body>
</html>
```

Click into the control and enter the character "b" (to filter the options list by "b"). 

* With `diacritics: false`, the dropdown contents update instantly
* Without `diacritics: false`, there's a ~800ms hiccup and then the dropdown updates

Profile link: https://profiler.firefox.com/public/tdv7ra4thmqhkfjhmyc7x7c4nz1jrbt2r8tqp10/calltree/?globalTrackOrder=01&implementation=js&thread=1&v=16

I'm seeing this on Firefox, but not on Chrome.

**Comment by NicolasCARPi** [comment]
Yes, I see it too on FF and not Chromium. Maybe it's a JS engine optimization 🤷‍♂️ difference. If you want to go down the rabbit hole and provide a fix for this, you're welcome ;)
