### ISSUE TITLE
The first option of the dropdown is automatically 'active'

### ISSUE THREAD

**Issue by FritzHerbers** [orchidjs/tom-select#409]
**Describe the bug**
When the dropdown is opened the first option or the last chosen option (when cleared) gets active.

**To Reproduce**
Use from Basic Examples the  "select" example (second example).
1. Open the dropdown
2. Arnold is active (wrong)

1. Open the dropdown
2. Choose Nikola
3. Remove Nikola
4. Open the dropdown
5. Nikola is active (wrong)

**Expected behavior**
Correct 'active' behavior
- No "active" selected when openend.
- When selection is removed, no "active" should be selected

Further question / enhancement:
Is there an option to disable showing the active option, especially in selects with only a few options it is not that obvious what is going on.

**Comment by oyejorge** [comment]
This is consistent with native select elements and performs as designed so I don't think this is a bug.

**Comment by FritzHerbers** [comment]
@oyejorge 

I understand the point when using the keyboard, it also scrolls the active down.
However, when using the mouse it does not behave accordingly.

Please have a look at https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select
You will notice that the active option scrolls down with the mouse movement. 

With tom-select it stays at the first option. IMO this is very misleading.

**Comment by FritzHerbers** [comment]
@oyejorge 
Put in another way, when scrolling up and down with the keyboard the "active" row is moved correctly.
Also hovering with the mouse works correct, the new option is shown as "active".

However, the last "active" row before using the mouse keeps "active", which is wrong/misleading. It shows two "active" rows. The native select element does not show this behavior.

Can you please have a look into this issue and comment.
