### ISSUE TITLE
Selected class appears after every selection

### ISSUE THREAD

**Issue by acetinick** [orchidjs/tom-select#41]
**Describe the bug**

![image](https://user-images.githubusercontent.com/571649/111911640-0e3fd780-8a6f-11eb-8abb-bd3f792e04f1.png)

**To Reproduce**
- in single select mode,  (assume same for multi-select)
- change selections
- each selection keeps "selected" class

**Expected behavior**
Selected class should only be assigned for selected options, and all others removed.  There is an 'active' class that appears after you select but this class doesn't initialise with initial selection,  so makes styling on selected item hard.

**Comment by oyejorge** [comment]
Confirmed, fixed, and tests added. A few more changes and I'll make another release

**Comment by lofcz** [comment]
@oyejorge still present in 2.0 only when options are passed as data, when options are supplied from DOM it works fine
