### ISSUE TITLE
JS error when checkbox plugin and create option used together

### ISSUE THREAD

**Issue by zipper** [orchidjs/tom-select#414]
**Describe the bug**
When `create: true` option and checkbox options plugin are used together, there is an JS error:
> Uncaught TypeError: Cannot set properties of null (setting 'checked')
    at plugin.ts:35:14

**To Reproduce**
Create an example on JSFiddle, CodePen or similar service and outline the steps for reproducing the bug.
1. Go to https://codepen.io/zipper/pen/qBoBaab
2. Create new option with whatever value
3. See error in console.

**Expected behavior**
There should be no error 🙂 

**Additional context**
 - Version 2.0.3

<!--
Thanks for taking the time to submit your bug report,
and don't forget to star our repo!

**Comment by oyejorge** [comment]
Just tried it and didn't get an error. Probably going to need to know which browser you were using.
