### ISSUE TITLE
[html attribute data-XXX] data-sort-field does not work

### ISSUE THREAD

**Issue by JeremieBergeron** [orchidjs/tom-select#415]
**Describe the bug**
data-sort-field html attribute is not parsed correctly: `[{field:'$score'}]`.

It seems to be execute like a string.

**To Reproduce**
1. Go to https://codepen.io/jeremieBergeron/pen/NWYWmqX
2. Click on the select. You will see that the order is what I wrote in sortField
3. Go to https://codepen.io/jeremieBergeron/pen/dymyLOM
4. Click on the select. You will see that the order is what it has by default. It does not care about the data-sort-field

**Expected behavior**
data-sort-field should be usable

Here is the doc about data-*: https://tom-select.js.org/examples/options/
Here is the doc about sortField: https://tom-select.js.org/docs/#sortfield

**Comment by oyejorge** [comment]
> sortField: "[{field:'$score'}]",

should be `sortField: [{field:'$score'}],`


> Here is the doc about data-*: https://tom-select.js.org/examples/options/

That doesn't say anything about using data-* attributes for TomSelect instance configuration
