### ISSUE TITLE
When using drag&drop plugin selected order is not present ordered

### ISSUE THREAD

**Issue by artur79** [orchidjs/tom-select#421]
I'm using a plugin https://tom-select.js.org/plugins/drag-drop/, after reordering some items an correct order is passed on form submit to the backend (Rails in my case) and saved correctly. But when I return to the page the order of selected items is the same as the order of all available options, which does not make sense when using drag & drop sorting because I need keep it custom.

For now I use workaround by setting selected items ids as data attribute for select, then on js side I read it and pass to options, here's example with stimulus controller (which is not mandatory of course)

```
import TomSelect from 'tom-select'
import { Controller } from '@hotwired/stimulus'

export default class extends Controller {
  static values = { selectedIds: Array }

  connect() {
    const el = this.element

    let config = {}

    if(el.multiple) {
      config.plugins = [
        'drag_drop',
        'remove_button'
      ]

      // workaround to keep order of items custom, independent from order of available options
      if(this.selectedIdsValue) {
        config.items = this.selectedIdsValue
      }
    }

    new TomSelect(el, config)
  }
}
```

**Comment by braindeaf** [comment]
It feels like this is a short-coming of taking a relatively innocuous HTML Select and enhancing with TomSelect. HTML itself doesn't have a mechanism to order multiple selections and I can only assume that the order is based on the original options order in the DOM. So would this be an opportunity to standardise ordering in this way, by having an attribute on the option that copes with order in this scenario? Either way, yes. This functionality would be very helpful.

**Comment by oyejorge** [comment]
>  I can only assume that the order is based on the original options order in the DOM

Correct. Unless of course you tell [TomSelect how to order items](https://stackoverflow.com/questions/72882317/tom-select-how-to-keep-order-when-using-drag-and-drop-plugin)
