### ISSUE TITLE
Select field is not reset within a form on a reset event

### ISSUE THREAD

**Issue by Dennis14e** [orchidjs/tom-select#422]
**Describe the bug**
The select field is not reset within a form on a reset event.

**To Reproduce**
See here: https://jsfiddle.net/2mgpkujd/
1. Change selected option on both selects
2. Click reset button
3. Expect the same behavior from normal Select and TomSelect

**Expected behavior**
The same behavior from normal Select.

**Additional context**
 - OS: Arch Linux
 - Browser: Google Chrome
 - Version: 103.0.5060.114

**Comment by oyejorge** [comment]
Still not sure if this is the best approach for handling a form reset but it seems to work for the given select: https://jsfiddle.net/et2h5ofc/

**Comment by Dennis14e** [comment]
This seems to work, thanks.
I currently use it this way so it works with any form/select: https://jsfiddle.net/p0cfej1d/
