### ISSUE TITLE
Prevent preload, and reset remote options on every dropdown - not just the first

### ISSUE THREAD

**Issue by daryld212** [orchidjs/tom-select#423]
I've been wrapping my head around trying to figure this out:
I have a perfectly set up Tom-Select dropdown that uses remote data. On the first click of the dropdown, the data is loaded. Once I've selected an item and clicked the dropdown again, the data is preloaded and not reset.

How can I force Tom-Select to reload the data every time the dropdown is opened?

My code (using with Stimulus):

```
connect() {
  const config = {
    plugins: ['clear_button'],
    valueField: 'value',
    labelField: 'text',
    persist: false,
    openOnFocus: true,
    preload: 'focus',
    loadThrottle: null,
    hideSelected: false,
    load: (q, callback) => this.search(q, callback)
  }
  new TomSelect(this.element, config)
}

async search(q, callback) {
  const response = await get(this.urlValue, {
    query: { q: q },
    responseKind: 'json'
  })

  if (response.ok) {
    const list = await response.json
    callback(list)
  } else {
    console.log(response)
    callback()
  }
}
```

**Comment by oyejorge** [comment]
`canLoad()` prevents sending duplicate calls to your backend via a check on the `loadedSearches` map. You could clear `loadedSearches` or override `canLoad()`

**Comment by daryld212** [comment]
Thanks @oyejorge – I've tried canLoad() but it looks like it's not being triggered. Also tried clearing loadedSearches inside onFocus(), also doesn't seem to affect the loaded data.

shouldLoad seems to get triggered, but not canLoad.

Am I putting the canLoad() override in the right place?

```
connect() {
  const config = {
    plugins: ['clear_button'],
    valueField: 'value',
    labelField: 'text',
    persist: false,
    openOnFocus: true,
    preload: 'focus',
    loadThrottle: null,
    hideSelected: false,
    load: (q, callback) => this.search(q, callback),
    canLoad: function(value) {
        return true;
    },
    onfocus() {
        this.loadedSearches = {};
    }
  }
  new TomSelect(this.element, config)
}

async search(q, callback) {
  const response = await get(this.urlValue, {
    query: { q: q },
    responseKind: 'json'
  })

  if (response.ok) {
    const list = await response.json
    callback(list)
  } else {
    console.log(response)
    callback()
  }
}
```

**Comment by ytilotti** [comment]
@daryld212, have you found a solution? Same issue here.

**Comment by daryld212** [comment]
@ytilotti yes, I used class inheritance to override the load and onFocus methods to prevent my select from reloading:

```
class ReloadTomSelect extends TomSelect {

  load(value) {
    this.clearOptions();
    super.load(value);
  }
  
  onFocus(e) {
    var classList = this.wrapper.classList;
    if( classList.contains('preloaded') ) {
      classList.remove('preloaded');
    }
    super.onFocus(e);
  }

}
```

And updated the original instance to use the new class:

```
if (!this.element.tomselect) {
  new ReloadTomSelect(this.element, config)
}
```
