### ISSUE TITLE
When using ajax, items get saved with value attribute instead of data-value

### ISSUE THREAD

**Issue by Hammy27** [orchidjs/tom-select#424]
I was playing with your remote data example ([https://tom-select.js.org/examples/remote/](url)). Then I wanted to delete some of the selections through the API. This failed miserably.

I suspect the reason to be found in the `value` attribute of the selected options. When using the fetch method, selected options get "saved" with an attribute called `value` and asigned the respective value.

When calling the `removeItem `function, the nested `getItem` function looks for an option with the attribute `data-value` (instead of the set `value` attribute), can't find anything and thus the item never gets deleted.

**Comment by Hammy27** [comment]
My workaround for the time beint is the following:

```
removeitem = function(value) {
   let itemtodelete= document.querySelector("option[value='" + value + "']")
   tomselect.removeItem(itemtodelete)
}
```

But this would obviousely not be necessary, if the option would have an `data-value` attribute.

**Comment by oyejorge** [comment]
`see removeOption()`

**Comment by akumanara** [comment]
![image](https://user-images.githubusercontent.com/7745757/206668353-f12edc54-094f-40f9-85e8-7c2d948d1de5.png)

I found this on my Sentry error logging inside the shouldDelete function. I allow the creation (create: true) of new items. Any ideas?
