### ISSUE TITLE
Sass error on Bootstrap 5 style when CSS variables are being used

### ISSUE THREAD

**Issue by levipadre** [orchidjs/tom-select#426]
**Describe the bug**
When I'm inporting tom-select.bootstrap5.scss or even tom-select.scss and I'm using with Bootsrap 5 everyting is working well until I start to use CSS variables for certain elements, like `$select-color-dropdown-border-top: mix($input-border-color, $input-bg, 0.8) !default;`
At the moment mix() function can't process css variables in Sass, so I get this error `SassError: $color1: var(--bs-gray-300) is not a color.` There is one other place `src/plugins/dropdown_header/plugin.scss` where mix has been used, same problem here too.

**To Reproduce**
Just use CSS variable in $input-bg for instance, like `$input-bg: var(--#{$prefix}form-control-bg) !default;`

**Expected behavior**
Until Sass can work with css variables in mix function, maybe it would be great to not use mix and let the developer use their own values for these elements.

**Additional context**
 - sass version: 1.54.0
 - sass-loader version: 13.0.2

**Comment by oyejorge** [comment]
I don't think we use mix() anywhere that bootstrap doesn't already use mix()?

**Comment by levipadre** [comment]
Thank you for the answer.
But if I change input bg value, like $input-bg: var(--bs-primary); Bootstrap code won't give Sass error. I know Bootsrap uses mix(), but not with css variables.

**Comment by oyejorge** [comment]
You could provide a value for $select-color-dropdown-border-top.

**Comment by levipadre** [comment]
Yeah, that's what I did, just thought maybe you can solve it without it. Thanks anyway
