### ISSUE TITLE
Can't use remove plugin

### ISSUE THREAD

**Issue by garak** [orchidjs/tom-select#43]
**Describe the bug**

I'm trying to use remove plugin in a web application.

I tried two ways:

```
import TomSelect from "tom-select/dist/js/tom-select.base";
import "tom-select/dist/esm/plugins/remove_button/plugin";
```

```
import TomSelect from "tom-select/dist/js/tom-select.base";
import "tom-select/dist/js/plugins/remove_button";
```

The first one fails at compile, with error:

>"./node_modules/tom-select/dist/js/plugins/remove_button.js" contains a reference to the file "../../tom-select.ts".
This file can not be found, please check it for typos or update it if the file got moved.

The second one compiles, but then fails on browser with console error:

> Uncaught Error: Unable to find "remove_button" plugin

**Additional context**
 - OS: Debian
 - Browser: Firefox
 - Version: 86
 - Device: laptop

**Comment by oyejorge** [comment]
> import TomSelect from "tom-select/dist/js/tom-select.base";
> import "tom-select/dist/esm/plugins/remove_button/plugin";

Looks like the problem is that `tom-select.base` doesn't exist. The path should probably be `tom-select/dist/js/tom-select.js`

[Here's an example](https://tom-select.js.org/examples/esm/)

**Comment by garak** [comment]
> Just change the first path to `tom-select/dist/esm/tom-select` and it should work

I tried, but I get the same compile error
