### ISSUE TITLE
Unable to override canLoad() or clear loadedSearches

### ISSUE THREAD

**Issue by daryld212** [orchidjs/tom-select#434]
(Following from ticket #423)

I'm trying to force my tom-select instance to reload the data on every use, and not store them. As new items may be added at any time, it's important that the list of options is refreshed each time it is opened.

Is it possible to override canLoad() or clear loadedSearches using the npm build of tom-select or do I need to run my own edited build?

I've added canLoad() to my config, but tom-select isn't recognizing it. Do I need to override this elsewhere?

Here is my code:
```
const config = {
  loadThrottle: null,
  load: async function(q, callback) {
    // Clear loadedSearches
    this.loadedSearches = {};
    ...
  },
  canLoad: function(value) {
    // Force data to load
    return true;
  }
}
new TomSelect(this.element, config)
```

**Comment by oyejorge** [comment]
canLoad() isn't a configuration setting, it's an internal function. For overriding, [you could create a custom plugin](https://tom-select.js.org/docs/plugins/#creating-plugins) or go [the inheritance route](https://javascript.info/class-inheritance).
