### ISSUE TITLE
This page uses the non-standard "zoom" property

### ISSUE THREAD

**Issue by Sozialarchiv** [orchidjs/tom-select#44]
**Describe the bug**

Firefox shows the following message in the console:

`This page uses the non-standard "zoom" property. Instead, you can use calc (), or "transform" together with "transform-origin: 0 0".`

**To Reproduce**
1. Go to https://tom-select.js.org/
2. Open firefox console
4. See warning

**Expected behavior**
No warning

Thank you very much for this great script.

**Comment by oyejorge** [comment]
Appears it was used to help old versions of IE render properly. I'll remove it since we don't need to support those versions any more

**Comment by Sozialarchiv** [comment]
Thank you.
