### ISSUE TITLE
Where to put my own plugin?

### ISSUE THREAD

**Issue by craigh** [orchidjs/tom-select#441]
Your docs say

> All plugins live in their own folders in ["src/plugins"](https://github.com/orchidjs/tom-select/tree/master/src/plugins).

Where can I place my own custom plugin so that it is registered and available?

> Plugins should not call TomSelect.define directly, this is done when importing the plugin.

so, how is this done then?

**Comment by oyejorge** [comment]
That bit of documentation could use some improvement.

To start, here's a simple custom plugin example:

https://jsfiddle.net/8bx4yLh0/

**Comment by craigh** [comment]
@oyejorge thanks for the response.

I ultimately did something like this:

```js
import TomSelect from 'tom-select/dist/js/tom-select.base';

import change_listener from 'tom-select/dist/js/plugins/change_listener';
import checkbox_options from 'tom-select/dist/js/plugins/checkbox_options';
// ...
import virtual_scroll from 'tom-select/dist/js/plugins/virtual_scroll';

TomSelect.define('change_listener', change_listener);
TomSelect.define('checkbox_options', checkbox_options);
// ...
TomSelect.define('virtual_scroll', virtual_scroll);

// add our own plugins
import button from './plugins/button/plugin';
import limit_display from './plugins/limit_display/plugin';

TomSelect.define('button', button);
TomSelect.define('limit_display', limit_display);

export default TomSelect;
```

which is pretty similar to what you proposed in the jsfiddle - just a little more spread out (and I used `tom-select.base`. Took me a while to figure it out though 😉 

So - now I have two plugins that I think would be useful to this project. I'd like to offer them back to you.

1. limit_display - allow the control to limit the number of _displayed_ selections and when greater than the limit, display `X items selected` instead.
2. button - add unlimited buttons to the dropdown element. each button action used to select an optgroup.  Also includes pseudo-optgroups to select all/none.

I wrote them in JS and with bootstrap 'built in' so they would need to be converted to TS and create/use sass files I guess. I would leave that part to you, but I doubt it would take you long.

Would you like the code?

**Comment by oyejorge** [comment]
Sounds great! Could you do a pull request for each plugin?

**Comment by craigh** [comment]
yeah, I think so.

**Comment by craigh** [comment]
done!
