### ISSUE TITLE
dropdown element is jumping on page load/reload

### ISSUE THREAD

**Issue by calculabs** [orchidjs/tom-select#443]
When I load the page, the dropdown element experiences a styling glitch. Presumably because the js loads after page loads. What can be done to avoid this and show the select dropdown as it should be on page load without the style glitch?

![tom-select-page-load-glitch](https://user-images.githubusercontent.com/88167579/184679826-a405086b-fe66-40ae-9fa2-a85c9b59508c.gif)

**Comment by oyejorge** [comment]
> Presumably because the js loads after page loads. 

Yeah, pretty much

>What can be done to avoid this and show the select dropdown as it should be on page load without the style glitch?

Since the jump is caused by styling being applied by JS, you could apply matching CSS style to the inputs prior to JS load+execution.
