### ISSUE TITLE
Multiple select on the same page seems not possible: Cannot read properties of undefined (reading 'trim')

### ISSUE THREAD

**Issue by giacomok** [orchidjs/tom-select#447]
**Describe the bug**
I have 2 select on the same page, I get this error on the second one:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'trim')
    at init_textbox (app.js?id=81bc03f0e3fe7c52ee160c79ad49e3df:205835:32)
    at getSettings (app.js?id=81bc03f0e3fe7c52ee160c79ad49e3df:205859:6)
    at new TomSelect (app.js?id=81bc03f0e3fe7c52ee160c79ad49e3df:205908:22)
```

If I use just one (it does not matter which is) I do not get any error.

**To Reproduce**
The code to create tom select is this:

```
document.getElementsByClassName('tom-select').forEach(item => {
    let options = {
        closeAfterSelect: true,
        plugins: {
           dropdown_input: {},
           remove_button: {
              title: "Remove this item",
           },
       },
       persist: false,
    };

    new TomSelect(item, options);
});
```

**Expected behavior**
Both select works

<!--
Thanks for taking the time to submit your bug report,
and don't forget to star our repo!

**Comment by oyejorge** [comment]
Pretty sure multiple selects on the same page are possible. For example: https://tom-select.js.org/examples/

Also:
> Create an example on JSFiddle, CodePen or similar service and outline the steps for reproducing the bug.
