### ISSUE TITLE
1.4.1 appendChild on node error

### ISSUE THREAD

**Issue by acetinick** [orchidjs/tom-select#45]
**Describe the bug**

![image](https://user-images.githubusercontent.com/571649/112236164-8f9e9200-8c48-11eb-9069-671a6354ccd5.png)

**To Reproduce**
- upgraded to 1.4.1

**Comment by oyejorge** [comment]
Hmm. I'm not able to reproduce the error. Any chance you can share an example where you're seeing the error?

**Comment by acetinick** [comment]
I got this in my debug,  but for some reason getting it also when we downgrade now to 1.4.0.  Not sure how it started happening (

![image](https://user-images.githubusercontent.com/571649/112237916-549e5d80-8c4c-11eb-84e7-554723b63183.png)

**Comment by oyejorge** [comment]
Thanks, that helps. Curious,  wich browser + version is this on?

**Comment by acetinick** [comment]
latest Chrome + Edge happening for us.

**Comment by oyejorge** [comment]
Strange, I'm not seeing the error on either of those. Is there a way for me to see the error live? Or can you duplicate it in a jsfiddle?

**Comment by acetinick** [comment]
Yea I can confirm that downgrading to 1.4.0 fixes the issue.  Can't reproduce yet in jsfiddle, but will look into more tomorrow.  Could be conflict with way we initialising control, as we using Stimulus JS.

**Comment by oyejorge** [comment]
Ok. Makes sense that downgrading works.

**Comment by oyejorge** [comment]
One more thought. Does the error show up for you when viewing the examples on https://tom-select.js.org?

**Comment by oyejorge** [comment]
The above change might solve the problem you're seeing

**Comment by naomi-nori** [comment]
I just encountered this in an emberjs application. Since ember extends prototypes (of `Array` in this case) using the `for..in` loop at https://github.com/orchidjs/tom-select/blob/master/src/tom-select.ts#L2302 ends up iterating over properties of the array, not just its values.

I'm not familiar with typescript so I don't know if this makes complete sense but switching the loop to a `forEach` should fix it.

**Comment by oyejorge** [comment]
Ah hell, I thought prototyping on Array was a thing of the past. Well, I
certainly can't control where this gets used so I'll add an Array.prototype
to the tests suite and make sure this never pops up again.

Thanks!

**Comment by acetinick** [comment]
@oyejorge confirmed this fixed now in 1.4.3 ,  great stuff)
