### ISSUE TITLE
Safari: Validation message not centered

### ISSUE THREAD

**Issue by gharlan** [orchidjs/tom-select#450]
**Describe the bug**
In Safari the validation message for required select fields is not centered.

**To Reproduce**
1. Go to https://jsfiddle.net/xz0p3L7f/2/
2. Click on "Send": centered validation message is shown for the first select field (not using tom-select).
3. Select something in first select field.
4. Click on "Send" again: validation message for tom-select field is shown on the left.

<img width="855" alt="Bildschirmfoto 2022-08-19 um 23 32 28" src="https://user-images.githubusercontent.com/330436/185710576-53ae6845-fa79-439b-8394-b982c16ef034.png">

<img width="829" alt="Bildschirmfoto 2022-08-19 um 23 32 59" src="https://user-images.githubusercontent.com/330436/185710586-aa93223b-5548-49d0-8f23-8ebf4534f3d4.png">

**Expected behavior**
Validation message should be centered.

**Additional context**
 - macOS
 - Safari 15.6.1

**Comment by oyejorge** [comment]
[Will you try this](https://jsfiddle.net/xav1zcnt/)?

**Comment by gharlan** [comment]
Thanks 👍
