### ISSUE TITLE
Server side rendering & dropdown population

### ISSUE THREAD

**Issue by horak** [orchidjs/tom-select#451]
Converting unanswered [discussion 442](https://github.com/orchidjs/tom-select/discussions/442) into an issue to see if it reaches any new eyeballs:

<div type='discussions-op-text'>

<sup>Originally posted by **horak** August 13, 2022</sup>
Can I render and populate a dropdown server-side using a template engine like (pug)?

I think I'm missing a few pieces of the puzzle. Any help would be appreciated. Here is some pseudocode. 

server.pug
```pug
select#dropdown
  each option in dropdown_options
    option(id=option.id data-count=option.count)=option.title
```

client.js (excluding the options property)
```js
new TomSelect('#dropdown', {
  onItemAdd:function(){
    this.refreshOptions();
  },
  valueField: 'id',
  searchField: 'title',
  render:{
    option:function(data,escape){
      return '<div class="d-flex"><span>' + escape(data['title']) + '</span><span class="ms-auto text-muted">' + escape(data.count) + '</span></div>';
    },
    item:function(data,escape){
      return '<div>' + escape(data['title']) + '</div>';
    }
  }
})
```

**Comment by oyejorge** [comment]
The whole list cannot be rendered on the server. Options need to be passed to TomSelect where they're rendered by the option render method. See https://tom-select.js.org/examples/remote/
