### ISSUE TITLE
Dropdowns in Boostrap4 accordions are cut off

### ISSUE THREAD

**Issue by fosterfarrell9** [orchidjs/tom-select#454]
**Describe the bug**
In Bootstrap4, TomSelect dropdowns in accordions are cut off:

![dropdown](https://user-images.githubusercontent.com/28628554/186126524-2f28a165-84df-4ff2-a0e0-69ce6b2145db.png)

**To Reproduce**
[https://jsfiddle.net/g0puqz31/](https://jsfiddle.net/g0puqz31/)

**Expected behavior**
The dropdowns are not cut off.

**Additional context**
The problem appears across several browsers. It does not appear in Bootstrap5, see [https://jsfiddle.net/3e904daj/](https://jsfiddle.net/3e904daj/). We are running a legacy app that is still on Bootstrap4. Is there some way to monkey patch this with Bootstrap4 for the time being until we migrate to Bootstrap5? I tried playing around with some `z-index` properties, but without success. Some other person reported a possibly related issue in [https://stackoverflow.com/questions/72441934/tom-select-options-are-not-showing](https://stackoverflow.com/questions/72441934/tom-select-options-are-not-showing).

<!--
Thanks for taking the time to submit your bug report,
and don't forget to star our repo!

**Comment by oyejorge** [comment]
[Here's one way to make it work using popper and the `dropdownParent` setting](https://jsfiddle.net/myL1rpth/)
