### ISSUE TITLE
searching doesn't update the selected option in dropdown

### ISSUE THREAD

**Issue by ymeynot45** [orchidjs/tom-select#455]
The bug occurs the any time you type into the search box while something is already selected.  If the first letter you type is included in the first option already selected, it will stay highlighted on that first option regardless if that letter is the first letter of the option.

This bug can be recreated on TomSelects own JSFiddle examples. https://tom-select.js.org/examples/. -- Select Multiple
1. Click on the entry field to enter a letter. It will drop down and auto select "Alabama".
2. Type "L"
3. The drop down will change so that "Louisiana" is the top answer on the list, yet "Alabama" is still selected.  So if you hit enter or you will choose "Alabama" not "Louisiana" even though "Louisiana" is the top entry.

I would expect that when I type in a search restriction that it would by default choose the top answer, not stay on the previous less qualified answer.  I expect that after typing 'L" that it would put "Louisiana" at the top (which it did) and that it would select it as the current selected target/element (which it does not).

Follow up:
This bug doesn't exist in all of the TomSelect JS Fiddles. If you go to https://tom-select.js.org/  -- and do it on the site it exists.
BUT if you open the JSFiddle and try it... you get this instead:
Click into the box and the highlighted option is "Blue Bloods" which starts with a B but contains an L. So if the above is true and I type an L it should stay on "Blue Bloods" and move "Lassiter" to the top.  Instead it moves "Lassiter" to the top AND selects it.  I don't know what the difference is in those two TomSelect examples but maybe it will help you track down the bug.

**Comment by oyejorge** [comment]
I believe the difference between tom-select.js.org and jsfiddle is because of [this change](https://github.com/orchidjs/tom-select/pull/435/files) that has not been released yet.

**Comment by ymeynot45** [comment]
Thank you for pointing out the fixes to me.  I merged the changes in my local branch and I want to confirm, independently, that it does fix the bug. It was a big help and it finished the project.

Do you have a set release schedule or does it just happen when you are happy with the current state of Tom Select? 
I am curious, as the last one was early July and you have made a lot of changes since then. 
I recommend Tom Select to people, and would like to keep abreast of the development cycle.

**Comment by ymeynot45** [comment]
Thank you for pointing out the fixes to me. I merged the changes in my local branch and I want to confirm, independently, that it does fix the bug. It was a big help and it finished the project.

Do you have a set release schedule or does it just happen when you are happy with the current state of Tom Select?
I am curious, as the last one was early July and you have made a lot of changes since then.
I recommend Tom Select to people, and would like to keep abreast of the development cycle.

**Comment by oyejorge** [comment]
Awesome, thanks for confirming!

I don't have a set release schedule. It's still a pretty small project in terms of users and I don't have a ton of free time to work it so I try to minimize the number of minor-fix releases by only releasing when I'm relatively confident new changes are working well... Ideally that means we'll have another release later this week.

**Comment by ymeynot45** [comment]
Well if it helps get more users by next week you can list Lobste.rs the
tech site as being one of the users of Tom Select.

**Comment by ymeynot45** [comment]
Thank you for getting back to me on this issue.  I can't deploy my removal
of jQuery to the site until this issue is resolved.  I was about to fork
Tom Select myself to see if I could fix it.

Do you know when that change might be released?  I would like to tell my
client that I have a date in which we can merge the new code.

Sincerely,

W.K./H.R./YmYn

**Comment by oyejorge** [comment]
Should already be out
