### ISSUE TITLE
AutoFill Not Changing The Tom-Select

### ISSUE THREAD

**Issue by MatthewKennedy** [orchidjs/tom-select#457]
If you use the browser built in auto-fill and a tom-select is in the form, it won't update the tom-select value if the select is changed.

Video of bug in action: https://youtu.be/BQw_ft_jqfA

**Comment by ymeynot45** [comment]
I am slightly worried that you put personal information in that video.

**Comment by oyejorge** [comment]
Also, try the [change-listener plugin](https://tom-select.js.org/plugins/change-listener/). Pretty sure it will work but I don't recall testing it with auto-fill.

**Comment by MatthewKennedy** [comment]
I'll have a look at that now, thanks for the help.

**Comment by MatthewKennedy** [comment]
@oyejorge That works perfectly.
