### ISSUE TITLE
Bootstrap 5; form-select class and multiple

### ISSUE THREAD

**Issue by bazineta** [orchidjs/tom-select#463]
This is more of a sanity check question than a bug per se.

In Bootstrap's select documentation, they always apply the `form-select` class, even in the case of a multiple select. However, in their implementation of a vanilla `multiple` select, there's no dropdown, so they don't apply a dropdown chevron to the input.

While it would seem that the same thing should apply to tom-select, e.g., the validation classes will only work if the original `select` is a `form-select` or `form-control`, if I apply the `form-select` class in concert with the `clear_button` plugin on a `multiple`, then the clear button and the dropdown chevron exist in the same space. That's not true of a `single`; the clear button is offset in that case.

Thus the sanity check nature of the question here. If we want the validation classes to work, then we've got to have either `form-select` or `form-control` present. Seems as if in the case of a `multiple`, `form-select` is the wrong choice due to the `clear_button` overlap, but is `form-control` therefore the right one?

**Comment by oyejorge** [comment]
[A jsfiddle or similar would be helpful here](https://github.com/orchidjs/tom-select/issues/new?assignees=&labels=bug&template=bug_report.md&title=)

**Comment by oyejorge** [comment]
I think we're squared away now.
