### ISSUE TITLE
Using minimal version with Typescript

### ISSUE THREAD

**Issue by zipper** [orchidjs/tom-select#468]
**Describe the bug**
I would like to use TomSelect without plugins in Typescript, but I'm unable to make it work. When using `import TomSelect from 'tom-select`, it uses the complete version. How should I import the basic JS file? When importing using `import TomSelect from 'tom-select/dist/esm/tom-select'`, I get an error:
```
ERROR in [at-loader] ./src/assets/js/Controls/TomSelectControl.ts:2:23
    TS7016: Could not find a declaration file for module 'tom-select/dist/esm/tom-select'. '/ ... /node_modules/tom-select/dist/esm/tom-select.js' implicitly has an 'any' type.
  Try `npm install @types/tom-select` if it exists or add a new declaration (.d.ts) file containing `declare module 'tom-select/dist/esm/tom-select';`
```

Although, no matter what version I import, I also get error in Sifter:
```
ERROR in [at-loader] ./node_modules/@orchidjs/sifter/lib/sifter.ts:26:9
    TS7008: Member 'items' implicitly has an 'any' type.
```

I can solve the first error using little shim.d.ts like this:
```ts
declare module 'tom-select/dist/esm/tom-select' {
  import { TomSettings } from 'tom-select/dist/types/tom-select.d.ts'

  export { TomSettings }
}
```
but can't solve the second error (and also I'm not sure about the solution for the first either, because then there is no property `define` for linking the plugins).

Also, when importing the plugins individually, e.g. `import TomSelectRemoveButton from 'tom-select/dist/esm/plugins/remove_button/plugin'`, I have similar problem with missing module declaration file.

**Comment by zipper** [comment]
Ok, the "solution" for first error doesn'nt work either. Besides the define
```
ERROR in [at-loader] ./src/assets/js/Controls/TomSelectControl.ts:11:11
    TS2339: Property 'define' does not exist on type 'typeof import("tom-select/dist/esm/tom-select")'.
```
I would also get this error when calling `new TomSelect()`:
```
ERROR in [at-loader] ./src/assets/js/Controls/TomSelectControl.ts:57:18
    TS2351: This expression is not constructable.
  Type 'typeof import("tom-select/dist/esm/tom-select")' has no construct signatures.
```

**Comment by zipper** [comment]
So I managed to solve the problems with Tom Select using
```ts
declare module 'tom-select/dist/esm/tom-select' {
	import TomSelect from 'tom-select/dist/types/tom-select'

	export default TomSelect
}
```
Similarly for plugins I need. But the error in Sifter remains and indeed adding explicit `any` at Sifter.ts:26 solves the issue. I made a PR in your fork https://github.com/orchidjs/sifter.js/pull/12, could you please take a look if thats ok with you?

**Comment by oyejorge** [comment]
I believe we need to add some 'exports' entries in package.json

**Comment by zipper** [comment]
I have created gist, where you can see the error https://gist.github.com/zipper/d6eb2ff2d81f6266ac283b9bfed21ce6. Just `run npm install && npm run build` after cloning it and you should see the error with sifter. If you remove the shim.d.ts, you should see the error with missing module declaration.

In the gist, I'm using TomSelect 2.1.0. You can also try to change it to latest 2.2.1, where there are different module declaration files missing. I was unable to resolve those, but since the sifter itself hasn't been updated, it shouldn't matter.

**Comment by oyejorge** [comment]
I couldn't get the gist to work as-is. I had to replace awesome-typescript-loader with ts-loader. After doing that, `npm run build` completed without any errors (without shim.d.ts).

**Comment by zipper** [comment]
@oyejorge I just tried that and I get the same error with `ts-loader` as well 🤔 Just to clarify, I'm using Node 16.18.0 and npm 8.19.2.
```
ERROR in /mnt/d/Htdocs/tom-select-ts-error/node_modules/@orchidjs/sifter/lib/sifter.ts
26:8-13
[tsl] ERROR in /mnt/d/Htdocs/tom-select-ts-error/node_modules/@orchidjs/sifter/lib/sifter.ts(26,9)
      TS7008: Member 'items' implicitly has an 'any' type.
ts-loader-default_e3b0c44298fc1c14

webpack 5.74.0 compiled with 1 error in 2733 ms
```

I just replaced `awesome-typescript-loader` with `ts-loader` as you described and changed target to es2020 (as es2021 weirdly produced an error). Without the shim, I also get the previous errors 🙁

**Comment by zipper** [comment]
Ok, as I didn't have the typescript as dependency, I had it installed by awesome-typescript-loader in old version. After removing node_modules and doing clean install with ts-loader, newer version of typescript installed and the error with implicit any disappeared, leaving me only with the missing .d.ts:
```
ERROR in /mnt/d/Htdocs/tom-select-ts-error/select.ts
./select.ts 1:22-54
[tsl] ERROR in /mnt/d/Htdocs/tom-select-ts-error/select.ts(1,23)
      TS7016: Could not find a declaration file for module 'tom-select/dist/esm/tom-select'. '/mnt/d/Htdocs/tom-select-ts-error/node_modules/tom-select/dist/esm/tom-select.js' implicitly has an 'any' type.
  If the 'tom-select' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module 'tom-select/dist/esm/tom-select';`
ts-loader-default_e3b0c44298fc1c14

webpack 5.74.0 compiled with 2 errors in 1559 ms
```

As I can resolve that with shim file, feel free to close this issue 🙂 Thank you very much for helping me figuring out where the problem is! 🙂

**Comment by oyejorge** [comment]
Sounds good!
