### ISSUE TITLE
Plugins `clear button` and `remove button` don't work well together

### ISSUE THREAD

**Issue by cavasinf** [orchidjs/tom-select#469]
**Describe the bug**

When using `clear button` and `remove button` plugins together with a multiple `select` row,
clear button is not well placed and cannot be differentiate with other remove buttons.

![image (1)](https://user-images.githubusercontent.com/25293190/190103883-bc441510-df82-4cfc-bbaa-4fbd05bcc5da.png)
![image (2)](https://user-images.githubusercontent.com/25293190/190103896-11472ba7-6f59-44e2-95e2-b6c3baf29e1d.png)

**To Reproduce**
1. Have `clear button` enabled
2. Have `remove button` enabled
3. Select multiple items
4. Have select with multiple lines 
5. Hover the select

**Expected behavior**
- The clear button should more recognizable than the remove button.
- It should be as the same height as the drop down caret.
- Maybe clear button needs his own place that item couldn't take ?

![image](https://user-images.githubusercontent.com/25293190/190110437-5a6056c8-fd73-4461-8209-cb856b869d41.png)
`Green lines` are safe zone for the clear button:
1. Select items will never cross that line
2. Dropdown caret should not cross that line

**Additional context**
 - OS: Windows
 - Browser: Firefox
 - Version: 2.0.3
 - Bootstrap: 5
 - Theme/Template: www.Tabler.io

**Comment by oyejorge** [comment]
```
**To Reproduce**
Create an example on JSFiddle, CodePen or similar service and outline the steps for reproducing the bug.
```

**Comment by cavasinf** [comment]
Here is a demo : https://jsfiddle.net/florian_allsoftware/f0wkpyd9/8/

Using : 
1. Symfony (only for class naming)
2. Tabler.io (Template)
3. TomSelect

Make it like that.
1. Symfony -> Add  `form-select` class to `select`
2. Tabler.io -> Stylize `form-select` by adding the caret at the end.
3. TomSelect -> Don't use the caret because there's not the class `single` (`multi` currently), but Tabler.io added it anyway.
