### ISSUE TITLE
scrolling on selection when using optgroups 

### ISSUE THREAD

**Issue by craigh** [orchidjs/tom-select#470]
**Describe the bug**
When using optgroups:

If you have a long list of options and mouse down to a later choice, when you select the item, the option list scrolls to the top optgroup. This is very inconvenient when selecting multiple options.

**To Reproduce**
- https://jsfiddle.net/p7gm46c2/
- Scroll to "wonderful4" option and select.
- Choice viewer will scroll to top optgroup header.

or go to your demo:
- https://tom-select.js.org/examples/optgroups/
- in the first example, select "skis"
- choice viewer scrolls to top

**Expected behavior**
No movement of choice viewer at all.

**Comment by Applelo** [comment]
Hello, a fix is already merge for this https://github.com/orchidjs/tom-select/pull/435. Waiting for a release ^^

**Comment by craigh** [comment]
@Applelo that's great! Thanks! I hope a release comes soon!

**Comment by Applelo** [comment]
If you cannot wait, it's possible to copy the function `refreshOptions` and uses the [plugin api](https://tom-select.js.org/docs/plugins/) to override the default one and put the fix I made. Not the prettiest option but it works.
