### ISSUE TITLE
Problem with remote data

### ISSUE THREAD

**Issue by irandoct** [orchidjs/tom-select#471]
Hi,
I'm using the following code:
new TomSelect('#pt',{
	    placeholder: 'انتخاب خدمت فیزیوتراپی',
		valueField: 'nationalNumber"',
		labelField: 'fullName',
		searchField: 'fullName',
		onChange: function(value) {
	    },
		sortField: {
		field: 'fullName',
		direction: 'asc'
	    },
		// fetch remote data
		load: function(query, callback) {
			$.ajax({
			type: "POST",
				cache: true,
				url: "https://SERVER/ihioservices.php",
				data: { 
				    searchTerm: query,
					ClinicID: cid,
                    cpartySessionId: "<?php echo $a->ihiosession; ?>",
					serviceTypeId: "4"
				},
				success: function(res) {
				callback(res.info);
				$('#insinfo').html(res); //for debuging
				},
				error: function(res) {
				callback();
			}
		});
		},
		// custom rendering functions for options and items
		render: {
		no_results: function( data, escape ){
			return '<div class="no-results">نتیجه ای یافت نشد.</div>';
		},
			option: function(item, escape) {
				if (item.state.isCovered){
				return `<div class="py-2 d-flex">
							<div class="icon me-3">
							<i class="fas fa-grip-lines-vertical text-success"></i> 
							</div>
							<div>
								<div class="mb-1">
									<span class="text-success">
										${ escape(item.fullName)}
									</span>
								</div>
							</div>
						</div>`;
				} else {
				return `<div class="py-2 d-flex">
							<div class="icon me-3">
							<i class="fas fa-grip-lines-vertical text-danger"></i>
							</div>
							<div>
								<div class="mb-1">
									<span class="text-danger">
										${ escape(item.fullName) }
									</span>
								</div>
							</div>
						</div>`;	
				}	
			},
			item: function(item, escape) {
				if (item.state.isCovered){
				return `<div class="py-2 d-flex">
							<div class="icon me-3">
							<i class="fas fa-grip-lines-vertical text-success"></i> 
							</div>
							<div>
								<div class="mb-1">
									<span class="text-success">
										${ escape(item.fullName)}
									</span>
								</div>
							</div>
						</div>`;
				} else {
				return `<div class="py-2 d-flex">
							<div class="icon me-3">
							<i class="fas fa-grip-lines-vertical text-danger"></i>
							</div>
							<div>
								<div class="mb-1">
									<span class="text-danger">
										${ escape(item.fullName) }
									</span>
								</div>
							</div>
						</div>`;	
				}	
			}
		},
	});	
///////////////////////////////////////////////////////
My json result from remote server is :
//////////////////////////////////////////////////////
{
	"resCode": 1,
	"resMessage": "فهرست خدمات با موفقیت واکشی شد.",
	"info": [{
		"fullName": "فیزیوتراپی زانوی سمت راست 901645-303",
		"shortName": "RIGHT KNEE JOINT PHYSIOTHERAPY",
		"nationalNumber": "901645303",
		"interfaceName": "RIGHT KNEE JOINT PHYSIOTHERAPY",
		"description": "به کارگیری روش ها و یا اعمال درمانی روتین فیزیوتراپی و طب فیزیکی و توانبخشی شامل هر تعداد از موارد ذکر شده برای هر ناحیه در هر جلسه",
		"NORepeat": 1,
		"state": {
			"isCovered": true,
			"isSpecialDisease": false
		}
	}, {
		"fullName": "فیزیوتراپی زانوی سمت چپ 901645-403",
		"shortName": "LEFT KNEE JOINT PHYSIOTHERAPY",
		"nationalNumber": "901645403",
		"interfaceName": "LEFT KNEE JOINT PHYSIOTHERAPY",
		"description": "به کارگیری روش ها و یا اعمال درمانی روتین فیزیوتراپی و طب فیزیکی و توانبخشی شامل هر تعداد از موارد ذکر شده برای هر ناحیه در هر جلسه",
		"NORepeat": 15,
		"state": {
			"isCovered": true,
			"isSpecialDisease": false
		}
	}]
}

The problem is that I can't see items ?!
What's wrong with my code?

Thanks

**Comment by oyejorge** [comment]
(1) not a bug (2) code not formatted (3) [not using issue template](https://github.com/orchidjs/tom-select/issues/new?assignees=&labels=bug&template=bug_report.md&title=) (4) not using jsfiddle or similar.... closing
