### ISSUE TITLE
Search field on `optgroup` doesn't work

### ISSUE THREAD

**Issue by fabienwnklr** [orchidjs/tom-select#472]
As describe in title, the search doesn't work on `optgroup`

Example : https://jsfiddle.net/gctLjfro/5/

I try with `[ 'optgroup', 'label', 'label_scientific']` no one work.. 

 - OS: Windows
 - Browser Chrome
 - Version 1.43.93
 - Device: Computer

**Comment by oyejorge** [comment]
Search only works on option values.

**Comment by ekrokowski** [comment]
@fabienwnklr You could use this to achieve that behaviour:

```javascript
new TomSelect('.selector', {
    searchField: ['text', 'groupName'],
    onInitialize: function() {
        Object.keys(this.options).forEach((key) => {
            this.updateOption(this.options[key].value, {
                ...this.options[key],
                groupName: this.optgroups[this.options[key].optgroup].label
            })
        });
    }
})
```

So you basically update your options to also include the group label and add that to the searchFields.
