### ISSUE TITLE
Stop working on Safari iOS 12

### ISSUE THREAD

**Issue by ocarreterom** [orchidjs/tom-select#483]
**Describe the bug**
This plugin stop working on Safari iOS 12 since v2.2.0 update.
Seems an infinite loop.

Was this intencional? Should it be added to the release notes?

**To Reproduce**
1. Go to [tom-select.js.org](https://tom-select.js.org) with Safari 12 (tested on iPad Air 2 with iOS 12.4)

https://user-images.githubusercontent.com/11599942/193596322-dba6be73-efb1-4a2c-865b-6c6190f23599.mov

**Additional context**
 - OS: iOS
 - Browser: Safari
 - Version: 12
 - Device: iPad Air 2

**Comment by oyejorge** [comment]
There should be more information in the [dev tools](https://developer.apple.com/safari/tools/). Take a look at the "console" tab and "network" tab to get more info.

**Comment by ocarreterom** [comment]
Nothing at the console :/

In this video you can see how the assets are loaded 4 times before Safari stops with "webpage crashed".

https://user-images.githubusercontent.com/11599942/193609140-47709f89-b892-4b73-bd6d-f4559c433183.mov

**Comment by oyejorge** [comment]
> Was this intencional? 

Definitely not.

I'm not seeing the problem when I try in Safari 12.

![Screenshot 2022-10-03 at 11-30-24 Dashboard](https://user-images.githubusercontent.com/1043524/193641375-9358fdbd-7178-4f11-8b21-c3a0a3a7e77d.png)

**Comment by ocarreterom** [comment]
I'am testing in iOS 12.4, Safari 12.1.2, Webkit 607.1.40.

<img width="890" alt="Captura de Pantalla 2022-10-03 a las 22 39 42" src="https://user-images.githubusercontent.com/11599942/193679021-45645630-e057-42cb-9618-047c5a8866fa.png">

The equivalent in macOS should be one of this versions:

<img width="429" alt="Captura de Pantalla 2022-10-03 a las 22 43 41" src="https://user-images.githubusercontent.com/11599942/193679274-e82b486d-8208-4e32-b09e-14529e9bf65a.png">

Is the version you tested? If it's working maybe it's a bug in the iOS version…

**Comment by oyejorge** [comment]
Yeah, I tested on 12.1.2 and I can't think of anything in the code that would cause the browser refresh

**Comment by ocarreterom** [comment]
Could you try on iOS 12.4?
In this video it's working in iOS 13.7, but not in iOS 12.4. I testing in Simulators but it also crash in real devices.

https://user-images.githubusercontent.com/11599942/193760357-f64ea195-37f8-46a6-abac-c52694b6afd6.mov

**Comment by oyejorge** [comment]
I believe I've found and fixed the problem. Let me know if you still it.

**Comment by ocarreterom** [comment]
@oyejorge it's fixed! Thanks!
