### ISSUE TITLE
Sass error since tom-select v2.2.0

### ISSUE THREAD

**Issue by morgoth** [orchidjs/tom-select#492]
When using the provided CSS, the error is thrown:
```
Error: "var(--ts-pr-min)" is not a number for `max'
        on line 26:18 of node_modules/tom-select/dist/css/tom-select.default.css, in function `max`
        from line 26:18 of node_modules/tom-select/dist/css/tom-select.default.css
```
There was a try to fix this in https://github.com/orchidjs/tom-select/pull/479 but it still does not work.

I'm using Ruby on Rails with sass processor (sassc-rails) and trying to `@import dist/css/tom-select.default.css`

**Comment by lafeber** [comment]
FYI: This is the fix: https://github.com/sass/sass/issues/2849

**Comment by ohsun0405** [comment]
Same problem for me on Ruby on Rails 7
Any workarounds or update coming?
I'm doing this at `production.rb` for now.
```
- config.assets.css_compressor = :sass
+ config.assets.css_compressor = nil
```

**Comment by artur79** [comment]
Got the same error as above (for 2.2.2) when tried to create stimulus controller for tomselect

```
import TomSelect from 'tom-select'
import { Controller } from '@hotwired/stimulus'

export default class extends Controller {
  connect() {
    let config = { maxOptions: null }

    this.select = new TomSelect(el, config)
  }

  disconnect() {
    if (this.select) {
      this.select.destroy()
    }
  }
}
```

**Comment by fnagel** [comment]
Same issue here: ` Uncaught TypeError: tom_select_1.default is not a constructor`

Any idea what's the issue here?
