### ISSUE TITLE
Problem with آ character

### ISSUE THREAD

**Issue by arbazargani** [orchidjs/tom-select#493]
On my remote side i have my response, which is working as well.
but problem with the character "**آ**":
[link](https://en.wiktionary.org/wiki/%D8%A2)

any word with this character wont load,
for example to search the word "آلمان" tomselect shows **no results find**.
i can't fix this and what i did is to search "لمان" to avoid this problem.
(consider that i checked the ajax request sent by tomselect and "آلمان" **is loaded with results of remote side**, but tom select shows me no results find.

please fix this. appreciate your support and your awesome doing.

**Comment by oyejorge** [comment]
It works for me ([example](https://jsfiddle.net/sd24Lozw/).

Please follow the bug report template so we don't waste time going back and forth trying to just reproduce the problem.

**Comment by oyejorge** [comment]
No response
