### ISSUE TITLE
Problem with displaying icon of clear button after form validation.

### ISSUE THREAD

**Issue by chaczyk007** [orchidjs/tom-select#494]
After the form is validated, the icons overlap.
![image](https://user-images.githubusercontent.com/19430358/196147871-d35be163-d4a5-4d3e-82f1-ae5c05d00a2b.png)

**To Reproduce**
Add clear button plugin and then validate the form on submit.
https://tom-select.js.org/plugins/clear-button/

**Example**
https://jsfiddle.net/chaczyk/3oskyx2b/

**Expected behavior**
Display a button to clear value in front of the validation icon.

**Comment by nisegami** [comment]
I ended up working around it with a bit of CSS:
`
.is-valid .clear-button {
    right: 3.75rem !important; 
}

.is-invalid .clear-button {
    right: 3.75rem !important;
}
`

**Comment by Dennis14e** [comment]
This bug still exists.

**Comment by chaczyk007** [comment]
This bug still exists.
