### ISSUE TITLE
Deleting all items changes vertical size of form-control-sm

### ISSUE THREAD

**Issue by Sobotkama** [orchidjs/tom-select#496]
**Describe the bug**
When using theme `bootstrap 5` and the select has class `form-control-sm`, the entire select grows vertically when all items are deleted.

**To Reproduce**
1. Go to https://tom-select.js.org/examples/styling/
2. Select theme `Bootstrap 5`
3. Delete all the items in the `form-control-sm` or `form-control-sm (single)` example on the right
4. The select's height increases

**Expected behavior**
The select's height stays the same when 

**Additional context**
 - OS: Windows
 - Browser chrome v106, firefox
 - Version 2.2.2

**Comment by zipper** [comment]
I have just noticed the same. Also when single select is used, the selected item is not vertically centered, see the attached screenshot from Chrome 106 @ Windows 10. First part shows the bug from first post, on second line you can see the incorrect alignment.

![obrazek](https://user-images.githubusercontent.com/3872371/197214234-c40debe5-962d-41de-a45c-224cf72510e1.png)

**Comment by Sobotkama** [comment]
This issue is still relevant

**Comment by zipper** [comment]
Still relevant

**Comment by Sobotkama** [comment]
Still relevant
