### ISSUE TITLE
Display remote data (API) without filtering

### ISSUE THREAD

**Issue by Crovitche-1623** [orchidjs/tom-select#497]
Hello,

I have a problem with the dropdown. I use Tom Select with an API that already handles typos etc. But it seems that tom select excludes results that do not explicitly contain the content of the input field. Could I just include the results returned by my API?

Sincerely

**Comment by oyejorge** [comment]
This has been covered somewhere in the discussions or issues. It would be good to add to the docs once found.

**Comment by Crovitche-1623** [comment]
Thank you for your quick answer. Is this this [issue](https://github.com/orchidjs/tom-select/issues/78) (#78) ?

**Comment by Crovitche-1623** [comment]
Thank you @oyejorge. I tried to fix my select today and #78 was the correct issue. Maybe we can add something in the documentation about it ?
```
// Fetch remote data
load: function (query, callback) {
  const url = parent.urlValue + '?q=' + encodeURIComponent(query)

  fetch(url)
    .then(response => response.json())
    .then(json => {
      this.clearOptions()

      callback(json.hits)
    }).catch(() => {
      callback()
    })
},
```

**Comment by pySilver** [comment]
Facing the same issue here. However I cannot use `this.clearOptions()` since I'm using `virtual scroll plugin` so I'd like user to have previosly loaded values.

**Comment by juniwalk** [comment]
> Facing the same issue here. However I cannot use `this.clearOptions()` since I'm using `virtual scroll plugin` so I'd like user to have previosly loaded values.

I used `clearOptions` and just got stuck on `virtual scroll` not working.
