### ISSUE TITLE
tsc complains moving from 2.2.1 to 2.2.2

### ISSUE THREAD

**Issue by mattgodbolt** [orchidjs/tom-select#500]
**Describe the bug**
In the latest version a change was made to use `RecursivePartial`

```ts
export default function getSettings( input:TomInput, settings_user:RecursivePartial<TomSettings>):TomSettings{
```

`tsc` complains for options like: 
```
                options: [
                    {id: DiffType.ASM, name: 'Assembly'},
                    {id: DiffType.CompilerStdOut, name: 'Compiler stdout'},
                    {id: DiffType.CompilerStdErr, name: 'Compiler stderr'},
                    {id: DiffType.ExecStdOut, name: 'Execution stdout'},
                    {id: DiffType.ExecStdErr, name: 'Execution stderr'},
                    {id: DiffType.GNAT_ExpandedCode, name: 'GNAT Expanded Code'},
                    {id: DiffType.GNAT_Tree, name: 'GNAT Tree Code'},
                ],
```

where both `id` and `name` have errors like:
```
[tsl] ERROR in /home/mgodbolt/dev/personal/ce/compiler-explorer/static/panes/diff.ts(156,47)
      TS2322: Type 'string' is not assignable to type 'RecursivePartial<any>'.
```

**To Reproduce**

Annoyingly I can't repro in jsfiddle - https://jsfiddle.net/psq9job4/ is the flavour of it. But both my IDE and webpack bundling ts assets complains about it, and I'm not quite sure where I'm going wrong.

**Expected behavior**
No errors.

**Additional context**
I rolled back to 2.2.1 for now in our project. It's entirely possible it's my fault and there's some TSC setting I need to fiddle with. Using tsc 4.8.4

**Comment by mattgodbolt** [comment]
@oyejorge - any thoughts on this and related issues? Should we look to fix things on our own with a forked version? Do you have time to look at these issues? :)

**Comment by mattgodbolt** [comment]
@oyejorge one last ping. We love TomSelect - but if it's not supported any more (understandably! we all have busy lives)... we'll start looking at alternative forks.

Thanks :)

**Comment by marius-mcfly** [comment]
![Bildschirm­foto 2023-06-07 um 10 14 22](https://github.com/orchidjs/tom-select/assets/61968399/23e512cf-81d8-439b-be2a-1a118ca9e5d4)

Same problem here. Any updates on this issue? :)
