### ISSUE TITLE
Problem with Checkbox Options plugin with duplicate options

### ISSUE THREAD

**Issue by quentinmassias** [orchidjs/tom-select#509]
**Describe the bug**
When you use the Checkbox Options plugin with a select with optgroups and duplicate options (option in multiple optgroup with the same value), on add and remove item, only one checkbox is toggled, not all of them.

PS : When you close and reopen the TomSelect dropdown, you can see every checkbox of the options of same value checked/unchecked, it just does not work on add/remove item instantly.

**To Reproduce**
- Create a simple select with 2 optgroups
- Put an option with value 'a' in both optgroup
- Instantiate TomSelect with plugin Checkbox Options on your select
- Check/uncheck option 'a' 

**Expected behavior**
Every option with same value should be checked/unchecked at the same time (without having to close and reopen TomSelect dropdown)

<!--
Thanks for taking the time to submit your bug report,
and don't forget to star our repo!

**Comment by quentinmassias** [comment]
Any info about this ? Still a problem.

**Comment by kevchcm** [comment]
I had the same issue when using slugs for the value, what I had to do was used unique IDs on the values, but yeah I wish there was a way to know what is the optgroup for an item with duplicate value
