### ISSUE TITLE
Firefox search causes value to not be available to form.

### ISSUE THREAD

**Issue by drsox** [orchidjs/tom-select#51]
**Describe the bug**
Firefox appears to fail to get updated form values from the selected search result.

**To Reproduce**
1. Create an HTML form.
2. Use tom-select in a <select> element with multiple entries.
3. Load your test page and search using tom-select and click a result.
4. Submit the form.
5. The form value for that select field will likely be empty.

Video of the problem is attached

**Expected behavior**
The form value should be returned (as it seems to be, reliably, in Chrome).

**Additional context**
Tested on Windows Firefox 86.0b8 and 86.0.
The problem also affects other firefox based browsers such as Pale Moon.

https://user-images.githubusercontent.com/761083/112556443-25116180-8dc2-11eb-8086-2a1918c80583.mp4

**Comment by oyejorge** [comment]
Do you have that codepen saved by chance?

**Comment by oyejorge** [comment]
Never mind, was just trying to save a little time, I have it working ... or rather not working. 

Thanks for taking the time to create a video, it's very helpful!

**Comment by oyejorge** [comment]
Looks like the source of the extra onchange event is this line: https://github.com/orchidjs/tom-select/blob/master/src/tom-select.ts#L1171

**Comment by oyejorge** [comment]
We might not be able to avoid ffox triggering an onchange event for the form when the control input is blurred, but we can probably make sure the value is set correctly before the blur/onchange occurs.

**Comment by oyejorge** [comment]
Good and bad:
1. The bad: the same behavior does occur in chrome
2. The good: found a great way to solve this

**Comment by drsox** [comment]
Thanks for the updates. Using the page in the same way on my implementation in Chrome didn't seem to trigger the problem. Glad you have ideas on how to fix it :)
