### ISSUE TITLE
Sass deprecation warning

### ISSUE THREAD

**Issue by joostdebruijn** [orchidjs/tom-select#517]
**Describe the bug**
Sass is throwing a depreciation warning during build time:

```
Deprecation Warning: $weight: Passing a number without unit % (0.8) is deprecated.

To preserve current behavior: $weight * 1%

More info: https://sass-lang.com/d/function-units

   ╷
31 │ $select-color-dropdown-border-top: mix($input-border-color, $input-bg, 0.8) !default;
   │                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/tom-select/src/scss/tom-select.bootstrap5.scss 31:36
```

**To Reproduce**
Do an import `tom-select.bootstrap5.scss` and build your project with Sass 1.56.0. The depreciation message above will be displayed.

**Expected behavior**
Don't receive any deprecation messages.

**Additional context**
It's happening with the latest release of this package: v2.2.2.

<!--
Thanks for taking the time to submit your bug report,
and don't forget to star our repo!

**Comment by mmarton** [comment]
same deprecation is present with BS4
`@import '~tom-select/src/scss/tom-select.bootstrap4.scss';`
