### ISSUE TITLE
tom-select doesn't work well together with CSP

### ISSUE THREAD

**Issue by joostdebruijn** [orchidjs/tom-select#52]
**Describe the bug**
When setting a CSP-policy, `unsafe-inline` must be set on `style-src` (there a two inline style attributes on a div with class `ts-dropdown single` and a div with class `ts-dropdown-content`) and `data:` must be allowed on `img-src` (for the dropdown icon). Probably there are some more situations like this.

**To Reproduce**
1. Set a CSP-policy on a page with tom-select selectors, such as: `content-security-policy: default-src 'self'`.
2. The selectors don't work, have a look at the console in DevTools to see the blocked resources.

**Expected behavior**
I would expect this plugin to work with a secure CSP.

**Additional context**
 - OS: Windows 10, 20H2
 - Browser: Chrome
 - Version:  89.0.4389.90
 - Device: Desktop

**Comment by oyejorge** [comment]
I moved the inline styles and I'm getting a clean CPS report in DevTools but I'm going to look at `img-src` and `data:` a little more.

**Comment by joostdebruijn** [comment]
Thanks for the very quick response and fix. Maybe good to know: I encountered this issue using the Bootstrap 5.x theme. Maybe it's related to that specific theme or Bootstrap itself. I can have a closer look at it tomorrow.

**Comment by oyejorge** [comment]
Ah, yep, there it is. I was looking at bootstrap4

**Comment by oyejorge** [comment]
Not sure if you've seen this, [here's what Bootstrap says about CSP and embedded SVGs](https://getbootstrap.com/docs/5.0/customize/overview/#csps-and-embedded-svgs)

> Several Bootstrap components include embedded SVGs in our CSS to style components consistently and easily across browsers and devices. For organizations with more strict CSP configurations, we’ve documented all instances of our embedded SVGs (all of which are applied via background-image) so you can more thoroughly review your options.
> ... 
> Based on community conversation, some options for addressing this in your own codebase include replacing the URLs with locally hosted assets, removing the images and using inline images (not possible in all components), and modifying your CSP. Our recommendation is to carefully review your own security policies and decide on a best path forward, if necessary.

**Comment by joostdebruijn** [comment]
Thanks, @oyejorge. Very helpful and thus not related to tom-select.
