### ISSUE TITLE
After selecting an item, the typed characters are still visible

### ISSUE THREAD

**Issue by hrauch** [orchidjs/tom-select#543]
I'm using the mutliple select mode and it does work very well. But after selectng the right word in my list of tags, the characters I typed are shown behind the tag. If I am searching for similar words, this is fine. But if I want to select another quite different tag, it would be better if the typed characters were not shown.
May be an option "clear input after selecting" would be possible.

**Comment by kevinpapst** [comment]
Yes please, a setting would be great here, as this is really a disturbing feature.

**Comment by bdkruse** [comment]
While I agree this should be default behavior, the example on the Tom Select landing page solved this issue for me. Here is how the codepen example solved the problem

```
new TomSelect("#select-tags",{
  onItemAdd:function(){
    this.setTextboxValue('');
  }
}
```

**Comment by kevinpapst** [comment]
Wow, that is simple, thanks for sharing @bdkruse 👍 

It does the job, let's hope it has no strange side effects...

**Comment by jclusso** [comment]
While @bdkruse method is a good start, I found that I needed to add `this.refreshOptions()` otherwise the options were missing.

```javascript
onItemAdd: function() {
  this.setTextboxValue('');
  this.refreshOptions();
},
```

**Comment by jclusso** [comment]
@bdkruse has a good start but I needed to add `this.refreshOptions(false)` otherwise the list was still being filtered.

```javascript
onItemAdd: function() {
  this.setTextboxValue('');
  this.refreshOptions(false);
}
```

**Comment by adrienbrault** [comment]
@jclusso Thank you!
