### ISSUE TITLE
Tom Select enabled field does not react to form reset events

### ISSUE THREAD

**Issue by landure** [orchidjs/tom-select#544]
**Describe the bug**

When a `<button type="reset"/>` is present in the `<form>` where a tom-select field is, tom-select field value is not reset by a click on the form reset button.

**To Reproduce**

1. Got to [tom-select.js fail to reset value on reset button click @ CodePen](https://codepen.io/landure/pen/dyjGGjP)
2. Change the select value in both fields of the example to `Other value` (both in the HTML select and in the Tom Select field).
3. Click on `Reset` button.
4. The HTML select value is reset, but the TomSelect value is not reinitialized.

**Expected behavior**

In the example above, the TomSelect value should be reinitialized to its value at page load (e.g. `Initial value`).

**Comment by m-lassoued** [comment]
I'm facing the same issue :/

**Comment by Crosswind** [comment]
We have the same issue in one of our projects. Any chance this can be looked at?
