### ISSUE TITLE
clear() method empty the visible tom-select field, but set the select field to the default selected option

### ISSUE THREAD

**Issue by landure** [orchidjs/tom-select#545]
**Describe the bug**

When tom-select is used on a field with '<option value="default" selected="selected">default value</option>', the `clear()` method empty the tom-select field, but the `<select>` field value is set to the default value as set by `selected="selected"` attribute.

**To Reproduce**

1. Go to [tom-select.js clear() method empty tom-select.js but set the value to the default field value @ CodePen](https://codepen.io/landure/pen/abjdNJO)
2. Click on `Reset`
3. Click on `Submit` to view field value at submit.

**Expected behavior**

Tom-Select should have two methods:

* `clear()` should empty the field and set the initial select to empty.
* `reset()` should set the initial select to its initial value and update the associated tom-select to the initial value, and should be called by the form reset event (see #544 ).

**Comment by pvh-archifact** [comment]
A possible workaround using the clear button plugin can be used.
i created a [JSFidle ](https://jsfiddle.net/USRFobiwan/hc1Lwjp0/)example.

We register the reset button click and go over the .ts-control elements in the form and find the .clear-button and do a click on it. Rather simple workaround. but it works.
