### ISSUE TITLE
Error after update to 2.2.2

### ISSUE THREAD

**Issue by artur79** [orchidjs/tom-select#546]
I'v got error after update to 2.2.2 when trying to use Tom Select in Rails app and Stimulus controller like:

```
import { Controller } from "@hotwired/stimulus"
import TomSelect from 'tom-select'
```

```
... node_modules/tom-select/dist/js/tom-select.complete.js: unknown Statement of type "ForOfStatement"
```
any ideas ?

**Comment by oyejorge** [comment]
Sounds like this https://stackoverflow.com/questions/72936556/how-to-solve-syntax-error-of-d3-array-src-number-js-unknown-statement-of-type

**Comment by artur79** [comment]
Good point, but any way to skip it ? We've dropped support for IE11 in our apps some time ago.

**Comment by morgoth** [comment]
@oyejorge is there any way to fix this without introducing IE11 support?

**Comment by morgoth** [comment]
still an issue

**Comment by artur79** [comment]
> still an issue

yep. bump
