### ISSUE TITLE
When using optgroups order sometimes is scrambled 

### ISSUE THREAD

**Issue by artur79** [orchidjs/tom-select#550]
Not sure if it's random or there is some rule, but order or optgroups on tomeselect side sometimes is different than in original underlaying select, I'v tried to use config option:

```
sortField: [{ field: '$order' },{ field: '$score' }]
```
to prevent it, but no success. Worth mention it only happens with some option is already selected on page load.

**Comment by DJDuque** [comment]
@artur79 I think I am having the same issue. Did you manage to find a work around?
