### ISSUE TITLE
Disable typing in select

### ISSUE THREAD

**Issue by amichel86** [orchidjs/tom-select#552]
Hello and thank you for your plugin. I tried StackOverflow but didn't get any answers. Super simple question, I would like to know if there's an option to disable the ability to type into the field. I was able to disable searchField with null but can't find the option for typing.

Video: https://www.loom.com/share/a8f4f8000c2a40c4b082a8941e094fab

Thank you!

**Comment by tylers-dev** [comment]
@amichel86 Maybe there is a better way, but would this solve your problem?
https://jsfiddle.net/tb7qy01c/

**Comment by amichel86** [comment]
@tylers-dev you are a life saver, thank you so much it works! :)
