### ISSUE TITLE
Virtual Scroll Plugin scrolls to top when next url loads

### ISSUE THREAD

**Issue by JackAtOmenApps** [orchidjs/tom-select#556]
**Describe the bug**
Each time nextUrl loads on the Virtual Scroll examples on the tom-select website, the select scrolls all the way back to the top of results, which is a frustrating user experience.

**To Reproduce**
View Virtual Scroll examples at https://tom-select.js.org/plugins/virtual_scroll/ or https://tom-select.js.org/plugins/ and scroll far enough to load more than one url's worth of options.

**Expected behavior**
The new content is appended, and user can scroll from the position which used to be the bottom (and is now the top of the new set of results).

**Additional context**
 - Ubuntu 22.04
 - 108.0.5359.124 (Official Build) (64-bit)
 - Version used on tom-select website
 - Laptop

**Comment by OmenApps** [comment]
For comparison, using Chrome in Android it works properly.

**Comment by Actionb** [comment]
This is still an issue in version 2.3.4

The workaround that I currently use monkeypatches `scrollToOption`  to not do anything until the callback has done its thing.
```javascript

      fetch(url)
        .then(response => response.json())
        .then(json => {
          const _scrollToOption = this.scrollToOption
          this.scrollToOption = () => {}
          callback(json.results)
          this.scrollToOption = _scrollToOption
```

**Comment by adaniello** [comment]
No news about this issue?

**Comment by MatTheCat** [comment]
Tracked this one down to `same_query` in `refreshOptions`: when it is called following new options being added its value almost always is `false`, which is wrong since the query didn’t change. The result is that the first option is considered the active one, and scrolled to.

**Comment by adaniello** [comment]
@skerit can you share your solution, please?
Thanks
