### ISSUE TITLE
Support for Bootstrap 5.3 Alpha 

### ISSUE THREAD

**Issue by james-em** [orchidjs/tom-select#559]
**Describe the bug**

The stylesheet `tom-select.bootstrap5.scss` doesn't build when importing Bootstrap 5.3 Alpha. It works when using Bootstrap 5.2.0

![Screenshot 2023-01-23 at 13 26 28](https://user-images.githubusercontent.com/63726983/214123719-3c8e6887-fbfa-46ce-b717-09b648ba0b01.png)

**Comment by kevinpapst** [comment]
Other places are affected as well, like :

```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: argument `$color-1` of `mix($color-1, $color-2, $weight: 50%)` must be a color
        on line 31 of node_modules/tom-select/dist/scss/tom-select.bootstrap5.scss, in function `mix`
        from line 31 of node_modules/tom-select/dist/scss/tom-select.bootstrap5.scss
>> $select-color-dropdown-border-top: mix($input-border-color, $input-bg, 0.8) 
```

Some variables now contain `var()` calls, instead of direct `#colors` or `$variables`. 
So it is not safe to pass them into `mix()`.

**Comment by Yann-BUTSCHER-EIRL** [comment]
I'm not sure if this is related or not but since Bootstrap 5.3 Alpha it is now possible to switch to other color modes and more specifically, to a dark mode (as mentioned in the [official documentation](https://getbootstrap.com/docs/5.3/customize/color-modes/)).

Would you consider adding support for a dark theme?

**Comment by silent-e** [comment]
I threw together a quick hack with dark styling.  I'm currently on Bootstrap 5.3.2.  This is a Sass file.  I'm using media queries and not the `data-bs-theme` functionality.

```sass
@media (prefers-color-scheme: dark)
{
  .ts-control,
  .full .ts-control,
  .ts-wrapper.single.input-active .ts-control
  {
    background-color: var(--bs-body-bg);
    border: var(--bs-border-width) solid var(--bs-border-color);
    color: var(--bs-body-color);
  }

  .ts-control > input
  {
    color: var(--bs-body-color);
  }

  .ts-wrapper:not(.form-control):not(.form-select).single .ts-control,
  .ts-wrapper.single:not(.form-control):not(.form-floating.form__text-area):not(.form-select) .ts-control
  {
    background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3e%3cpath fill='none' stroke='%23495057' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='m2 5 6 6 6-6'/%3e%3c/svg%3e");
  }

  .ts-wrapper.plugin-remove_button:not(.rtl) .item .remove
  {
    border-inline-start-color: var(--bs-border-color);
  }

  .ts-wrapper.multi .ts-control > div
  {
    background-color: var(--bs-secondary-bg);
    color: var(--bs-body-color);
  }

  .ts-dropdown
  {
    background-color: var(--bs-body-bg);
    color: var(--bs-body-color);

    .active
    {
      background-color: var(--bs-secondary-bg);
      color: var(--bs-body-color);
    }

    [data-selectable] .highlight
    {
      background: $yellow-800;
    }
  }
}

```

**Comment by Floppy** [comment]
@silent-e's media query has just solved a big problem I was having with tomselect and Bootstrap 5.3's automatic dark theme! This would be great to reopen and look at integrating properly; @silent-e would you consider doing this as a PR?
