### ISSUE TITLE
Crash of the plugin when I continuously press some letters

### ISSUE THREAD

**Issue by fHuteau** [orchidjs/tom-select#560]
**Describe the bug**
I encounter this bug on a professional project but I reproduce it on the site https://tom-select.js.org.
If I keep pressing certain letters, like f or k, the plugin crashes the site and the CPU usage increases.
It doesn't happen with all the keyboard key.

I reproduced it on different computers with different browsers but all are under Windows 10/11.

![Capture d’écran 2023-01-25 165052](https://user-images.githubusercontent.com/57004056/214613593-ae2e1bea-0994-4bda-a0a0-d41b338f5f3d.png)
![Capture d’écran 2023-01-25 165155](https://user-images.githubusercontent.com/57004056/214613587-17cee7dd-b942-4c8e-925d-d303132b1743.png)

**Comment by ejozmar** [comment]
any update about this issue?
