### ISSUE TITLE
Impossible to select and copy the selected choice

### ISSUE THREAD

**Issue by Seb33300** [orchidjs/tom-select#596]
**Describe the bug**
When the user select a choice, he is not able to copy the value he selected.
Especially when the field looks like a text input, some users dont understand why they cannot copy the text.

**To Reproduce**
1. Go to https://tom-select.js.org/examples/
2. Scroll down to the 2nd example (`<select>`)
3. Select a value (eg: `Nikola`)
4. Click on the input
5. You will see the mouse cursor changing to a "text" cursor but we are not able to select the text to copy it

**Expected behavior**
We should be able to copy the text Nicola we previously selected. Or at least add an option to make this possible.

**Comment by amitjindal** [comment]
I have the same problem here. I want to copy the email address in this (value of the option): https://tom-select.js.org/examples/contacts/
Unable to do.

Is there a workaround?

**Comment by Seb33300** [comment]
Still relevant
