### ISSUE TITLE
Doesn't work with Bootstrap 5.3

### ISSUE THREAD

**Issue by dmitrue** [orchidjs/tom-select#600]
Hi, Bootstrap 5.3 was released and I was wondering if there plans to upgrade TomSelect to support latest version?
For now it does not work:
`Error: $color1: var(--bs-border-color) is not a color.
$select-color-dropdown-border-top: mix($input-border-color, $input-bg, 0.8) !default;`

**Comment by adas172002** [comment]
Same as https://github.com/orchidjs/tom-select/issues/599#issue-1732584992
