### ISSUE TITLE
Order not respected with options and options group

### ISSUE THREAD

**Issue by valentin-procab** [orchidjs/tom-select#603]
**Describe the bug**
I have a select with both options and optiongroups but when tom-select is initialized, the order change and all my options are stacked before all the optiongroups.
I haven't find anything in the docs to keep the same order.

**To Reproduce**
[Exemple](https://jsfiddle.net/kL3hd48m/)

**Expected behavior**
I want my options and optiongroups order to stay the same as when my select is defined

**Comment by melbings** [comment]
Same for me.

For now, I will need to put single options into a group of their own, in order to keep the intended overall sort order.
