### ISSUE TITLE
PageSpeed thinks: "Prevents users from pasting into input fields" (?!)

### ISSUE THREAD

**Issue by coudrak** [orchidjs/tom-select#605]
I'm not sure if it's an issue about TomSelect or PageSpeed, but PageSpeed Insights gives a warning "Prevents users from pasting into input fields" when we use TomSelect.

Pasting works in the TomSelect inputs, so I don't understand why PageSpeed thinks it's not possible.
An idea about that?

To try PageSpeed with the example page: https://pagespeed.web.dev/analysis/https-tom-select-js-org-examples/b3jtf8tk4i?form_factor=mobile

![Capture](https://github.com/orchidjs/tom-select/assets/3312725/77d6886c-b334-48a9-be81-3438ba1d8e8e)

**Comment by yanivtoledano** [comment]
I'm seeing the same thing - unsure why...
