### ISSUE TITLE
dropdown direction

### ISSUE THREAD

**Issue by KonradWebArray** [orchidjs/tom-select#607]
Does this support dropdown direction auto?
Seems to always opens "down" even if the screen cuts it off. Would expect this to open "up" in that situation.

**Comment by kido1611** [comment]
I solved this problem by adding floating-ui. Maybe you can try it.

**Comment by oyejorge** [comment]
Related: https://github.com/orchidjs/tom-select/issues/6

**Comment by bellef** [comment]
Thanks 👍
