### ISSUE TITLE
Checking in on maintenance

### ISSUE THREAD

**Issue by josefdlange** [orchidjs/tom-select#609]
Hi! I apologize for misusing Issues in this instance, and I hope this doesn't come off pushy; it's not my intent. 

There is at least one issue whose resolution I think would be really important to keep TomSelect relevant going into the future -- fixing compatibility with Bootstrap >= 5.3 -- and there are a few PRs from which to choose to merge in and handle the issue. 

I know that life can be busy, and I think I speak for most users of open-source projects like this when I say it's understandable that something can fall pretty low in priorities when measured against everyday life! That said, do you think there's a way to get this one issue resolved? Or perhaps to designate some trusted user with maintenance authority on this project, to help it keep move forward?

I don't claim to have extreme familiarity with the architecture of TomSelect but I'd volunteer to help out if need be. I can at least detect bad code smell in PRs :)

I hope you are well -- that's most important -- and are enjoying the summer! Thank you for bringing TomSelect into existence, I'm hopeful it can continue to grow and evolve with support.

**Comment by josefdlange** [comment]
Hi @oyejorge I hate to be a bother, but I'd love to hear of a way to make progress here.

**Comment by josefdlange** [comment]
Hi there, just checking in again to see if there's anything I or any member of the community can do to help keep this project alive and well. @oyejorge pls!

**Comment by mattgodbolt** [comment]
@craigh has a branch he's trying to get up to date. I hope @oyejorge is OK and is just busy!

**Comment by craigh** [comment]
The fork is here: https://github.com/RemoteDevForce/tom-select

available via npm/yarn `@remotedevforce/tom-select`

**Comment by oyejorge** [comment]
Sorry I wasn't available for a while. Yep, been busy. Let me know if there are more changes to the RemoteDevForce fork that should be incorporated.

**Comment by mattgodbolt** [comment]
hi @oyejorge ! glad to hear you're back. hope everything's ok with you!

**Comment by craigh** [comment]
> Let me know if there are more changes to the RemoteDevForce fork that should be incorporated.

@oyejorge - I am not watching you have have already merged but if you merged some of the other fixes, you might need this one also - it corrected an issue with double borders.

https://github.com/RemoteDevForce/tom-select/commit/18a7623c68d3b750808f941b57e55380879c5777

**Comment by oyejorge** [comment]
Thanks!
