### ISSUE TITLE
default behaviour auto-resizes dropdown even if single-select only mode

### ISSUE THREAD

**Issue by samsong** [orchidjs/tom-select#611]
is it possible to disable the auto resize autogrow / shrink behaviour for <select> ?.

I just want to set the dropdown to the maximum option length and keep it that width forever to stop visually disrupting the user.

**Comment by 9mm** [comment]
Im also wondering this...

I want it to behave like a normal select box where its the length of the longest item. I cant find any information how to do this...

<img width="224" alt="image" src="https://github.com/orchidjs/tom-select/assets/1386207/9e97429e-431c-4448-837d-325dda4727dc">

**Comment by jclusso** [comment]
Was looking for a solution to this and figured I would share the answer here that worked. https://github.com/orchidjs/tom-select/discussions/563
