### ISSUE TITLE
Unable to run tests locally

### ISSUE THREAD

**Issue by mattgodbolt** [orchidjs/tom-select#612]
Long time user and now trying to fork and fix some things myself.

However, cloning, then `npm install` then `npm run test` fails during the grunt task `sass:build` with:

```
Fatal error: Error: $color1: var(--bs-border-color) is not a color.
```

-- Can anyone help me understand what I'm doing wrong? I tried applying some of the sass-fixing PRs but no luck.

**Comment by mattgodbolt** [comment]
Hackily commenting out the bootstrap5 support (which my project doesn't need) and ...
```
> tom-select@2.2.2 test
> karma start

15 07 2023 13:23:08.529:ERROR [plugin]: Cannot find plugin "/home/matthew/dev/tom-select/node_modules/karma-accessibility-checker".
  Did you forget to install it?
  npm install /home/matthew/dev/tom-select/node_modules/karma-accessibility-checker --save-dev
15 07 2023 13:23:08.856:ERROR [karma-server]: Server start failed on port 9876: Error: No provider for "framework:aChecker"! (Resolving: framework:aChecker)
15 07 2023 13:23:08.858:ERROR [reporter]: Can not load reporter "aChecker", it is not registered!
  Perhaps you are missing some plugin?
```

I am clearly missing something :)
I'm doing an `npm install` and then `npm run test`

**Comment by craigh** [comment]
I see the same errors. disabling BS5 support is not an option for me :(

**Comment by craigh** [comment]
@mattgodbolt we are trying to make a workable fork also. We fixed some of the issues with the color thing you mentioned [here](https://github.com/RemoteDevForce/tom-select/commit/88413547cb0ec1ca864a341de18b774714b8645a) but still have the karma test errors.

**Comment by mattgodbolt** [comment]
Thanks @craigh . BS5 is required for me too, I was just trying to work out what options I had.

**Comment by craigh** [comment]
@mattgodbolt give https://www.npmjs.com/package/@remotedevforce/tom-select a try. I haven't tested it yet, but I think it is ready.

**Comment by mattgodbolt** [comment]
Thanks! Will do!

**Comment by mattgodbolt** [comment]
I'm a bit of a noob when it comes to replacing an existing package with a forked version: I `npm r`'d tom-select and then `npm`'d yours ... is there a way to use yours in place of tom-=select or do I need to go through my whole program and update all the `tom-select` requires and whatnot with `@remotedevforce/tom-select` or similar? (I'll do that...but just in case I'm being silly...)

**Comment by mattgodbolt** [comment]
Well...with that change I was able to load up but I get a new and exciting set of type errors as per #518. Some heinous casting might get it working, but this is sadly another reason why a good answer for the future of this would be nice (maybe moving to your fork and trying to fix these things?)  Thank you for the work so far!

**Comment by craigh** [comment]
@mattgodbolt I'm a total newb with all this. Looks like you got a good start in your PR so you have the idea. I've not tried to build any typescript, so I've not dealt with that issue. We have a TS dev in our repo, so let's move further discussion to [my repo discussions](https://github.com/RemoteDevForce/tom-select/discussions) or [issues](https://github.com/RemoteDevForce/tom-select/issues) instead of further polluting this.
