### ISSUE TITLE
Why isn't the selected text removed during the second round of editing?

### ISSUE THREAD

**Issue by esledov** [orchidjs/tom-select#615]
I've set maxItems to 1, so I assume tom-select is in single-select mode. However, I've noticed that after selecting an item once, the previously selected text does not get removed when I start entering new text. This is confusing.

As I begin to type new text, the dropdown menu is filtered according to this new input alone, yet the old text remains visible. What is the rationale behind this? Is it a bug?

![edison2](https://github.com/orchidjs/tom-select/assets/10031989/c09ddd3a-4e90-4f4c-94eb-5189bb26bc06)

**Comment by calvinrbnspiess** [comment]
I experienced this issue too and think this should not be the default behaviour.

I solved it by setting `closeAfterSelect` and blurring the input on close. Additionally, I hide the selected option when the dropdown is open.

```javascript
 new TomSelect("#select", {      closeAfterSelect: true, onDropdownClose(dropdown) {
        const input = dropdown.closest("#select).querySelector(".ts-control input");

        input.blur();
    }})
```

```css
.dropdown-active, .input-active {
  .ts-control div[data-ts-item] {
    display: none;
  }
}
```

**Comment by ksouthworth** [comment]
Thanks, I was trying to achieve the same thing (fix the lingering input control after an item was selected).  I adapted the code snippet below and it works how I think it should now.


> I experienced this issue too and think this should not be the default behaviour.
> 
> I solved it by setting `closeAfterSelect` and blurring the input on close. Additionally, I hide the selected option when the dropdown is open.
> 
> new TomSelect("#select", {
>     closeAfterSelect: true,
>     onDropdownClose: function(dropdown) {
>         const input = dropdown.closest("#select").querySelector(".ts-control input");
> 
>         input.blur();
>     }
> })
> 
> .dropdown-active, .input-active {
>   .ts-control div[data-ts-item] {
>     display: none;
>   }
> }
