### ISSUE TITLE
drag_drop plugin TypeError: $ is undefined

### ISSUE THREAD

**Issue by JiveDig** [orchidjs/tom-select#619]
I'm loaded tom-select complete via CDN (2.2.2) and using the drag_drop plugin.

I'm getting `TypeError: $ is undefined` error the following line:
```
if (!$.fn.sortable) throw new Error('The "drag_drop" plugin requires jQuery UI "sortable".');
```

If I add `var $ = jQuery;` above that line the error goes away and everything works. Is this something I'm missing on my end?

**Comment by glaszig** [comment]
you're missing jquery.

**Comment by JiveDig** [comment]
Nope, it's there. I confirmed it's in the source, and it's loaded before.

**Comment by glaszig** [comment]
sure it's been loaded _before_ that line of code of in tom-select is executed? that's the only reason i can think of that gives sense to `$ is undefined`.

**Comment by glaszig** [comment]
is it possible that your jquery is running in `.noConflict()` mode?

> If you need to use another JavaScript library alongside jQuery, return control of $ back to the other library with a call to $.noConflict(). Old references of $ are saved during jQuery initialization; **noConflict() simply restores them.**
> - https://api.jquery.com/jQuery.noConflict/

that's why your `$ = jQuery` works and it may actually be the proper workaround.

**Comment by JiveDig** [comment]
Interesting. I don't really use jQuery so i'm not sure. A quick google showed this https://wpmudev.com/blog/daily-tip-adding-custom-js-to-wordpress-remember-jquery-noconflict-wrappers/, so I guess it is. Bummer that it doesn't work out of the box with WordPress. Not a huge deal though.

**Comment by glaszig** [comment]
though i think because the `jQuery` global is more stable and likely to be what it claims to be the plugin should use that instead of `$`...

**Comment by naton** [comment]
You're missing jQuery **UI**, specifically the plugin [Sortable](https://jqueryui.com/sortable/)

**Comment by oyejorge** [comment]
the next version of the plugin will not use jquery: https://github.com/orchidjs/tom-select/commit/cb4dc0c4a2b0269af9f2d0b6499234157ab249fb

**Comment by glaszig** [comment]
even better 👍
