### ISSUE TITLE
When enabling the checkbox_options plugin, input isn't cleared after selection. 

### ISSUE THREAD

**Issue by Rio517** [orchidjs/tom-select#632]
## Description
When enabling the checkbox_options plugin, input isn't cleared after selection. If using the keyboard, the user experience is troublesome as the user is likely to accidentally remove their selection with subsequent presses of the enter key. 

See video:

[tomselect_checkbox_issue.webm](https://github.com/orchidjs/tom-select/assets/14241/2c3acbeb-a827-47bc-8847-1da11c8a8beb)

It is also possible this is the desired behavior, but I'm guessing not.

## **To Reproduce**

You can see this behavior on the plugin's page in the documentation: https://tom-select.js.org/plugins/checkbox-options/
1. Go to https://tom-select.js.org/plugins/checkbox-options/
2. Click on the input field
3. Type "coo" to highlight the "cool" option
4. Hit enter, and the "cool" option will be selected/checked.
5. Notice that the input field isn't cleared.
6. Hit enter again. (and again and again)
7. Notice that the "cool" option is now deselected.

For now, I'm adding the following line as a workaround.

 `select.on("item_add", (value, item) => {select.setTextboxValue("") })`

## **Expected behavior**

The input field is cleared after selection, so the user doesn't accidentally unselect an option, and the user doesn't have to manually clear their previously typed entry.

## **Additional context**
 - OS: Windows 11, MacOS, and Linux Mint 20.2
 - Browser: Chrome 117
 - Version: Documentation site version as of 2023-09-22
 - Device: Laptops

**Comment by ToshY** [comment]
For your information, @oyejorge doesn't seem to maintain tom-select anymore, so I'm not sure if there's any point in creating a bug report here. Maybe you have more chance of going to a fork, e.g. https://github.com/RemoteDevForce/tom-select and submit it there (you'd probably have to fix and create a PR for it yourself as the maintainer of that repo won't).

Also see #601 .

**Comment by oyejorge** [comment]
Sounds like #22
