### ISSUE TITLE
[Bug]: Error thrown after 2.2.3 upgrade

### ISSUE THREAD

**Issue by DawidJanczak** [orchidjs/tom-select#642]
### Bug description

Hello,

We're getting the following error after upgrading to 2.2.3 (we're using webpack with sass-loader):
```
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Can't find stylesheet to import.
   ╷
74 │ @import "../plugins/drag_drop/plugin";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   node_modules/tom-select/dist/scss/tom-select.scss 74:9  @import
```

We're importing `tom-select` scss like so `@import "tom-select/dist/scss/tom-select";` in our scss files.

### Expected behavior

I was expecting the build to pass. It was working fine in 2.2.2 so it seems like a regression.

### Steps to reproduce

I'm not sure this is something I can do with JSFiddle, would probably have to set up new project with webpack. Opening with hopes it will be obvious why this fails, but if not let me know and I can spend some time on the weekend setting something up.

### Additional context

- OS: Docker, Alpine
- Browser -
- Version -
- Device: -

**Comment by ocarreterom** [comment]
Same for me.

v2.2.2: `node_modules/tom-select/dist/scss/tom-select.scss:141`
```scss
@import "./plugins/drag_drop.scss";
@import "./plugins/checkbox_options.scss";
@import "./plugins/clear_button.scss";
@import "./plugins/dropdown_header.scss";
@import "./plugins/dropdown_input.scss";
@import "./plugins/input_autogrow.scss";
@import "./plugins/optgroup_columns.scss";
@import "./plugins/remove_button.scss";
```

v2.2.3: `node_modules/tom-select/dist/scss/tom-select.scss:74`
```scss
@import "../plugins/drag_drop/plugin";
@import "../plugins/checkbox_options/plugin";
@import "../plugins/clear_button/plugin";
@import "../plugins/dropdown_header/plugin";
@import "../plugins/dropdown_input/plugin";
@import "../plugins/input_autogrow/plugin";
@import "../plugins/optgroup_columns/plugin";
@import "../plugins/remove_button/plugin";
```

**Comment by Banner-Keith** [comment]
The only way I can get it to build in my testing is like this:

```
@import "plugins/drag_drop";
@import "plugins/checkbox_options";
@import "plugins/clear_button";
@import "plugins/dropdown_header";
@import "plugins/dropdown_input";
@import "plugins/input_autogrow";
@import "plugins/optgroup_columns";
@import "plugins/remove_button";
```

The folder structure of the published package has the plugins folder as a sibling to the `tom-select.sccs` folder not one level up as it is in source here. So I don't think the commit that has been made will fix it.

**Comment by oyejorge** [comment]
@Banner-Keith The folder structure is different in /src and /dist and the gruntfile fixes those paths during the build process (note, if you're building on local, new files will be in /build and not /dist).

**Comment by glaszig** [comment]
> the gruntfile fixes those paths during the build process 

no, it doesn't. this is current version 2.2.3 as downloaded from npm:

<img width="838" alt="screenshot" src="https://github.com/orchidjs/tom-select/assets/201135/be99b1fd-c560-4bb0-98d7-f758ead1b419">

**Comment by glaszig** [comment]
> no, it doesn't.

i stand corrected, the current grunt build does. but that's not what's in the release on npm. see screenshot.
