### ISSUE TITLE
[Bug]: Type 'string' is not assignable to type 'RecursivePartial<any>'.

### ISSUE THREAD

**Issue by harkor** [orchidjs/tom-select#643]
### Bug description

If we want to add options when we instanciate a new TomSelect component, we have errors on each options from typescript.

```js
new TomSelect(document.querySelector<HTMLSelectElement>('#mySelect')!, {
    options: [
        {
            value: `option_1`,
            text: `Option 1`,
        },
    ],
    placeholder: 'Choose an option',
});
```

Type 'string' is not assignable to type 'RecursivePartial<any>'.

![image](https://github.com/orchidjs/tom-select/assets/1044182/14ceb46d-ac7a-4335-a9ce-877aa51b147e)

### Expected behavior

Get no error

#### On your computer
1. Go to https://github.com/harkor/tomselect-recursive-partial
2. Clone project
3. yarn
4. yarn dev

#### On stackblitz
1. Go to https://github.com/harkor/tomselect-recursive-partial
2. Click on link Open in Stackblitz

Errors will be in terminal and browser with two methods

### Additional context

- IDE: PHPStorm
- Builders: vite and webpack 5

**Comment by jmsche** [comment]
Hi @oyejorge, a big thank you for the quick patch! :smile: 

Would you mind tagging a new version of Tom Select? Thanks!
