### ISSUE TITLE
[Bug]: Wrong number of arguments (4 for 3) for `rgb'

### ISSUE THREAD

**Issue by fsevestre** [orchidjs/tom-select#647]
### Bug description

Hello, I'm having compilation errors importing the scss files:

```
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
wrong number of arguments (4 for 3) for `rgb'
        on line 18 of node_modules/tom-select/src/plugins/remove_button/plugin.scss
        from line 81 of node_modules/tom-select/src/scss/tom-select.scss
        from line 23 of assets/styles/app.scss
>> 		background: rgb(0, 0, 0, 5%);
```

### Expected behavior

No compilation error when importing the scss files.

### Steps to reproduce

```
@import '~tom-select/src/scss/tom-select';
@import '~tom-select/src/scss/tom-select.bootstrap5';
```

### Additional context

- node-sass@^9.0.0:
  version "9.0.0"
- sass-loader@^13.3.2:
  version "13.3.2"
- tom-select@^2.3.0:
  version "2.3.0"

**Comment by oyejorge** [comment]
I'm not going to say this shouldn't be changed but I would also recommend moving from node-sass (since it's deprecated) to [Dart Sass](https://www.npmjs.com/package/sass)
