### ISSUE TITLE
[Bug]: Issue in Bootstrap5 Modal 

### ISSUE THREAD

**Issue by Huangzc88** [orchidjs/tom-select#675]
### Bug description

When using tom-select in bootstrap5 modal, the drop-down box data will be blocked when selecting it. Setting z-index cannot solve the problem.

![image](https://github.com/orchidjs/tom-select/assets/31158857/da751174-a322-4bd9-ac2a-f3076e4f0472)

![image](https://github.com/orchidjs/tom-select/assets/31158857/f6932d48-fe66-4b4b-ae5c-046702c39285)

Can you help fix this problem?

### Expected behavior

The expected behavior should be no problem.

### Steps to reproduce

used in bootstrap5 modal

### Additional context

Bootstrap ver.5.3.1
Microsoft Edge ver.120.0.2210.6
tom-select ver.2.3.0

**Comment by THenkeDE** [comment]
you may add something like this to break out of the scrollable bs5 modal:

            document.querySelectorAll('[data-bs-toggle="dropdown"]').forEach( (dropdownToggleEl) => {
                bootstrap.Dropdown.getOrCreateInstance(dropdownToggleEl, { popperConfig() { return { strategy: 'fixed' } } });
            });

at least it worked for me.

**Comment by Huangzc88** [comment]
> you may add something like this to break out of the scrollable bs5 modal:
> 
> ```
>         document.querySelectorAll('[data-bs-toggle="dropdown"]').forEach( (dropdownToggleEl) => {
>             bootstrap.Dropdown.getOrCreateInstance(dropdownToggleEl, { popperConfig() { return { strategy: 'fixed' } } });
>         });
> ```
> 
> at least it worked for me.
> 
> and you need to add popper to be used by TomSelect
> 
> ```
>                 new TomSelect(e, {
>                     onInitialize:function(){
>                         this.popper = Popper.createPopper(this.control,this.dropdown);
>                     },
>                     onDropdownOpen:function(){
>                         this.popper.update();
>                     },
> ```

Thank you very much for your answer, I'll see if it works.
