### ISSUE TITLE
[Bug]: Dropdown input plugin puts id on wrong element

### ISSUE THREAD

**Issue by scott-8** [orchidjs/tom-select#679]
### Bug description

When the dropdown input plugin is used, it puts the label on the `ts-control` div rather than the input field. This causes issues when the field is labelled, as divs aren't allowed to have labels.

### Expected behavior

I would expect the id (for example, `ex-dropdown-input-ts-control`) to be on the input field.

### Steps to reproduce

1. Go to the example for dropdown input in the docs (https://tom-select.js.org/plugins/).
2. Inspect element.
3. The id `ex-dropdown-input-ts-control` is on the `ts-control` div, rather than the input in the div.
4. For the rest of the examples, the id is on the input as it should be.

### Additional context

- OS: Windows
- Browser: Chrome

**Comment by Ikpixel** [comment]
@oyejorge Hope that this will be fix ASAP.

I have a label with for="example" and the id="example" is set to the div with class ts-control instead of the input in it.

**Comment by scott-8** [comment]
> This issue has not been active in 120 days and has been marked "stale". Remove stale label or comment or this will be closed in 15 days

Issue still exists
