### ISSUE TITLE
[Bug]: raw --ts-pr-min: $padding-x SASS variable present in css dist files

### ISSUE THREAD

**Issue by a-maas** [orchidjs/tom-select#683]
### Bug description

I noticed that in the package's `dist/css/tom-select.default.css` file, the following CSS was present, which I believe is invalid:
```
.ts-wrapper.multi.has-items .ts-control {
  padding-left: 5px;
  --ts-pr-min: $padding-x;
}
```
Specifically `$padding-x;`, which I think is a SASS variable that didn't get properly replaced. 

Looking at the[ source code](https://github.com/orchidjs/tom-select/blob/69180fa9e79060060f1824fbde85537579d0005d/src/scss/tom-select.default.scss#L24), I believe the SASS variable should be wrapped in `#{}`, as referenced from [here](https://sass-lang.com/documentation/breaking-changes/css-vars/). 

### Expected behavior

The value of `--ts-pr-min` should be the value of the `$padding-x` sass variable, not a string `$padding-x`.

### Steps to reproduce

1. View dist file in the page from [npm](https://www.npmjs.com/package/tom-select?activeTab=code)
2. Look in `dist/css/tom-select.default.css` on line 449.

### Additional context

Using tom-select 2.3.1 with vite 4.3

**Comment by lolaslade** [comment]
I am experiencing this issue when using Symfony UX autocomplete
