### ISSUE TITLE
Questionable behavior when the user clicks on an optgroup header

### ISSUE THREAD

**Issue by kaihu** [orchidjs/tom-select#7]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo in the documentation)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

### Questionable behavior when the user clicks on an optgroup header

Steps to reproduce:

1. Initialize tom-select with option groups and options for them
2. Click the input to open dropdown
3. Click on an optgroup header

**Expected result**: Dropdown remains as is OR All items in the clicked group are selected.

**Actual result**: Dropdown is closed

That the dropdown is simply closed, is bad usability IMO.

optgroup demos:
https://tom-select.js.org/examples/optgroups/

There is an existing bug report about this in selectize repo:
https://github.com/selectize/selectize.js/issues/1382
And PR that supposedly fixes the issue:
https://github.com/selectize/selectize.js/pull/762

I've also included a feature suggestion as second item in the "Expected result" -field above; Clicking the optgroup header could select all items in the optgroup. Perhaps this could be implemented in a plugin?

**Comment by oyejorge** [comment]
Thanks. 
I'll get that fixed shortly along with a test to make sure it's not a problem again.

**Comment by oyejorge** [comment]
I like the feature idea. I think it would work well as a plugin.
