### ISSUE TITLE
[Bug]: The select won't open on click

### ISSUE THREAD

**Issue by Raven0us** [orchidjs/tom-select#701]
### Bug description

If `openOnFocus: false`, clicks don't open the select, neither does the key Space.

Auto focus events are noise to a screen reader (jumping from document to element back to document).

### Expected behavior

Clicking the control or hitting Space should open the select.

### Steps to reproduce

https://codepen.io/Raven0us/pen/GRLKNGX

### Additional context

Latest version

**Comment by vilinicz** [comment]
Confirming, with `openOnFocus: false` options dropdown doesn't open at all.

**Comment by pereorga** [comment]
I think this is by design? With `openOnFocus: false` it opens only when the user types something and the search matches. I actually use this.
