### ISSUE TITLE
[Bug]: alignment issue when selecting and deselecting items

### ISSUE THREAD

**Issue by lovasoa** [orchidjs/tom-select#712]
### Bug description

When selecting an item with ctrl+click, the 1px grey border around it disappears, which makes the entire list of options jump by 2px

![image](https://github.com/orchidjs/tom-select/assets/552629/7292f7bf-a1b1-4fca-b498-8eb151504ef1)
![image](https://github.com/orchidjs/tom-select/assets/552629/f349e9e7-7051-405f-bb3a-9d43be249aba)

### Expected behavior

selecting an option shouldn't change the position of other options

### Steps to reproduce

1. In a multiselect, select two options
2. click on the first one to make it become blue
3. expected result: the other option doesn't move
4. actual result: the other option moves by 2px because the border around the first one disappeared

### Additional context

- OS: all
- Browser all
- Version latest (2.3.1)
- Device: all

found while trying to integrate TomSelect with [SQLPage](https://sql.ophir.dev/)

**Comment by lovasoa** [comment]
still a problem

**Comment by nwalters512** [comment]
@lovasoa I think the border here might be coming from either your own CSS or another project. Your screenshot shows `var(--tblr-...)` for some CSS property values, which isn't coming from this library. I also can't see the border on https://tom-select.js.org/examples/, nor can I reproduce any layout shifting when following your instructions. Could you provide an isolated reproduction, ideally with one of the examples on the docs site?

**Comment by nwalters512** [comment]
Per a comment on #713, it seems like this may indeed have been an issue with third-party conflicting styles.
