### ISSUE TITLE
[Bug]: Error in vanila.ts file

### ISSUE THREAD

**Issue by CyrilleTanguay** [orchidjs/tom-select#760]
### Bug description

Hello,

Every time I type `npm run build`, I have this error:

```
./node_modules/tom-select/src/vanilla.ts:100:39
Type error: Octal escape sequences and backreferences are not allowed in a character class. If this was intended as an escape sequence, use the syntax '\x09' instead.

   98 |         iterate( args, (_classes) =>{
   99 |                 if( typeof _classes === 'string' ){
> 100 |                         _classes = _classes.trim().split(/[\11\12\14\15\40]/);
      |                                                            ^
  101 |                 }
  102 |                 if( Array.isArray(_classes) ){
  103 |                         classes = classes.concat(_classes);
```

(BTW, I noticed a [pull request](https://github.com/orchidjs/tom-select/pull/748) that should fix that)

### Expected behavior

I expected that there would be no errors

### Steps to reproduce

1. Install tom-select
2. type `npm run build`

### Additional context

From the `package.json` file:

- "typescript": "^5.5.4"
-  "tom-select": "^2.3.1"

**Comment by nwalters512** [comment]
This should have been resolved by #777. Thanks for the report!
