### ISSUE TITLE
[Bug]: dist CSS is not mapped in package.json

### ISSUE THREAD

**Issue by Jean85** [orchidjs/tom-select#771]
### Bug description

I'm trying to use this package with the [Symfony Asset Mapper](https://symfony.com/doc/6.4/frontend/asset_mapper.html), which leverages ESM loading to avoid Node/npm as a requirement. This seems to work well with your package, except for the fact that the CSS dist file is not mapped in the `package.json`, so ESM does not see that.

### Expected behavior

CSS is included in the package, so that CDNs like [jsDelivr](https://www.jsdelivr.com/package/npm/tom-select?path=dist) will consider it and add to the needed files.

### Steps to reproduce

1. Go to [jsDelivr](https://www.jsdelivr.com/package/npm/tom-select?path=dist)
2. Click on ESM mode button
3. See that only the JS file is imported:
```html
<script type="module"> 
    import tomSelect from 'https://cdn.jsdelivr.net/npm/tom-select@2.3.1/+esm'
</script>
```

### Additional context

The Symfony docs refer to the [package.json configuration file](https://docs.npmjs.com/creating-a-package-json-file) as a way to fix this; we probably need to add keys like `sass` or `style` to the root of the `package.json`, like Bootstrap does: https://github.com/twbs/bootstrap/blob/e3e00b5002139adb0d5dadd6002e15b7b6cd371f/package.json#L40

**Comment by nwalters512** [comment]
I'm not understanding the relationship between jsDelivr and Symphony Asset Mapper. Can you explain more?

You cite Bootstrap as an example of something that's working correctly. However, the ESM "type" on jsDeliver (https://www.jsdelivr.com/package/npm/bootstrap) also doesn't include any CSS:

<img width="825" alt="Screenshot 2024-11-18 at 14 05 45" src="https://github.com/user-attachments/assets/9bcd4363-bc58-417b-ac52-d8823df25f22">

I'm happy to add a `"style"` property to `package.json` if you think that'll fix things.

**Comment by Jean85** [comment]
The Symfony Asset Mapper uses jsDelivr to download precompiled ESM assets, hence avoiding the need for NodeJS locally.

For Bootstrap, there's no explicit CSS import, but I can add it manually into the Symfony Asset Manager configuration, importing `dist/css/bootstrap.min.css`, which is present inside the compiled package. For your package, you have the SCSS inside `src/scss`, but since it's not exposed in the package.json, is not compiled by jsDelivr.

As of now, I'm using your package without CSS, but if I would want to add it, I would need it; I don't know how to handle the different versions though...

**Comment by nwalters512** [comment]
If manually adding a path is an option, have you tried that with `tom-select`? They're all available on jsDelivr, there's no need for jsDelivr to "compile" them on its own: https://www.jsdelivr.com/package/npm/tom-select?path=dist%2Fcss&tab=files

**Comment by nwalters512** [comment]
Given that we added a `style` property to `package.json` as requested above, I'm going to close this issue. Feel free to comment if something is still not working quite right!

**Comment by Jean85** [comment]
2.4.0 is now showing with the CSS URL :tada: 

https://www.jsdelivr.com/package/npm/tom-select

It's fixed, thanks!
