### ISSUE TITLE
Is there a way to disable searchField from filtering results?

### ISSUE THREAD

**Issue by acetinick** [orchidjs/tom-select#78]
**Describe the bug**
I have API endpoint that is doing remote full text search on query, and the results are getting filtered unless I specify all the search fields that should be found in the columns.

Is there a way to disable this feature?  I have tried setting searchField: [] and null but not working.   Basically just want to show all the results from API, without filtering.

https://tom-select.js.org/examples/remote/

**Comment by oyejorge** [comment]
I actually just ran into this yesterday while working on the virtual scroll feature. I don't have a solution yet...

**Comment by oyejorge** [comment]
Ok. Here's how:

1. Update to version 1.6.2 which fixes a regression effecting the sortField setting
2. Add ```sortField: [{field:'$order'},{field:'$score'}]``` to your configuration
3. Add ```this.clearOptions()``` inside your load() function so that only the newest remote data is displayed in the dropdown

Example: https://jsfiddle.net/jevctaL4/

**Comment by acetinick** [comment]
Just upgraded and tried this out, but didnt work for me.  Not sure if its the same issue I having.

This is the code Im using,  but its returning no results because searchField is expecting to see matching text in this field.  In my case I just want to show all options whatever returned from server with no filtering,  the only way I can get this to work is specifying all fields in the searchField, like in my example ["text", "code"]

![image](https://user-images.githubusercontent.com/571649/117649940-c862de00-b198-11eb-817a-b3657ec8be60.png)

![image](https://user-images.githubusercontent.com/571649/117650076-ee887e00-b198-11eb-9afc-7a565e915a14.png)

**Comment by oyejorge** [comment]
>  the only way I can get this to work is specifying all fields in the searchField, like in my example ["text", "code"]

Yeah, that shouldn't be necessary. I just pushed out 1.6.3 with an updated sifter.js to fix that.

[Here's a working example](https://jsfiddle.net/0ktng7j6/)

**Comment by acetinick** [comment]
Hi worked great) thanks

**Comment by ve3** [comment]
The document ( https://tom-select.js.org/docs/ ) said

> To completely disable the client side filtering (if youre getting the search results from an external source), set the searchField to an empty array. 

But did not mentioned about calling ...

```js
this.clearOptions();
```

Which is important. Otherwise the old result will be stuck.

Please update the doc.

**Comment by NicolasCARPi** [comment]
@ve3 feel free to open a PR with the documentation change you'd like to see, or open a new issue.
