### ISSUE TITLE
[Bug]: Octal escape sequences in vanilla.ts cause TypeScript errors

### ISSUE THREAD

**Issue by arshadazaad3** [orchidjs/tom-select#786]
### Bug description

I'm experiencing a TypeScript build error related to octal escape sequences in the `vanilla.ts` file of the `tom-select` library. The issue occurs in the regular expression used for splitting classes in the `iterate` function. The error message states:

```
Octal escape sequences and backreferences are not allowed in a character class. If this was intended as an escape sequence, use the syntax '\x09' instead.
```

The problematic code is located at line 100 in `vanilla.ts`:

```ts
_classes = _classes.trim().split(/[\11\12\14\15\40]/);
```

This causes issues when building with TypeScript, as octal escape sequences are not allowed in character classes.

---

### Expected behavior

The TypeScript build should succeed without any errors. The octal escape sequences in the regular expression should be replaced with their hexadecimal equivalents, as follows:

```ts
_classes = _classes.trim().split(/[\x09\x0a\x0c\x0d\x20]/);
```

This will resolve the issue and allow TypeScript to build without errors.

---

### Steps to reproduce

1. Install the `tom-select` library in a TypeScript project.
2. Include any component that uses `tom-select`.
3. Attempt to build the project with `tsc`.
4. The build will fail with the TS1536 error.

You can also test this using the following steps:
1. Create a minimal TypeScript setup.
2. Add `tom-select` and use a component that triggers the `vanilla.ts` code.
3. Run `tsc` to reproduce the error.

### Additional context

- **OS**: Windows 11
- **Browser**: Chrome (though this is a TypeScript build error, not a runtime error)
- **TomSelect Version**: 2.0.0
- **Node.js Version**: 20.x
- **Device**: Desktop

This issue affects TypeScript users in particular, and fixing the regular expression with hex escape sequences will ensure better compatibility.

**Comment by nwalters512** [comment]
This was resolved by #777. The fix will go out with the next release. Thanks for the detailed report!
