### ISSUE TITLE
Bootstrap v5: disabled select not grayed out

### ISSUE THREAD

**Issue by joostdebruijn** [orchidjs/tom-select#86]
**Describe the bug**
When I disable a tom-select element, I expect it would be grayed-out. See the example in the Bootstrap-documentation: https://getbootstrap.com/docs/5.0/forms/select/#disabled.

**To Reproduce**
1. Create a disabled tom-select (either by using the `disabled`-attribute or `disable()` in the Javascript API)
2. The select is not grayed out.

**Expected behavior**
I would expect that it looks grayed out.

**Additional context**
 - OS: Windows 10.0.19043.985
 - Browser: Chrome 
 - Version: 90.0.4430.212
 - Device: Desktop
 - Bootstrap: 5.0.1
 - Tom-select: 1.7.0

<!--
Thanks for taking the time to submit your bug report,
anbd don't forget to star our repo!

**Comment by oyejorge** [comment]
Thanks! Will have an updated release out shortly

**Comment by samlachance** [comment]
Was this ever added? I'm experiencing the same but it's possible that I'm doing something wrong :joy:
