### ISSUE TITLE
Dropdown doesn't scroll to active option

### ISSUE THREAD

**Issue by oyejorge** [orchidjs/tom-select#88]
**Describe the bug**
Dropdown doesn't scroll to active option. See https://github.com/compiler-explorer/compiler-explorer/pull/2666

**Comment by mattgodbolt** [comment]
Oh sweet, do you think this, plus #87 will fix the Compiler Explorer issues? I'd love to get that PR merged and live on the site! :)

**Comment by oyejorge** [comment]
I think there are two things on your list that won't be covered.

>   Same width issues as the OG thing ("clang assertions" very wide etc)

Possible solution:
```css
 .ts-dropdown{
width: 500px; // or whatever width you want
}
```

> Ideally adding stuff to favorite should keep everything scrolled as it was (confusing to have things slip down)

The slip down is caused by new options (the new favorite) being added to the top of the dropdown list. To prevent the slip, there would have to be some additional code to adjust the dropdown scroll position after new options are added to the top of the dropdown.

>  I'd love to get that PR merged and live on the site! :)

I would too! I've found a few other things that need to get fixed but I'm almost done
