### ISSUE TITLE
Minimized JS file tom-select.complete.min.js doesn't work.

### ISSUE THREAD

**Issue by anandphulwani** [orchidjs/tom-select#9]
**Describe the bug**
tom-select.complete.min.js doesn't work, it gives **ReferenceError: tomSelect is not defined**, where as tom-select.complete.js works completely.

**To Reproduce**
1. Go to https://codepen.io/anandphulwani/pen/LYRMeLy, open Console to check error.
2. Click on "Gear" icon in the JS section, top open "Open JS Settings".
3. Scroll down to 4th library it has **min.js** file loaded
``https://cdn.jsdelivr.net/npm/tom-select@1.1/dist/js/tom-select.complete.min.js``
when you change to **.js** file, it works
``https://cdn.jsdelivr.net/npm/tom-select@1.1/dist/js/tom-select.complete.js``

**Expected behavior**
tom-select.complete.min.js should work.

**Additional context**
 - Windows 10
 - Firefox Developer Edition
 - 85.0b7
 - PC

**Comment by oyejorge** [comment]
Thanks! This fix is ready to go for the next release.
