### ISSUE TITLE
TomSelect 1.7 & bootstrap 5 styles doesn't apply to input-group

### ISSUE THREAD

**Issue by martinbarilik** [orchidjs/tom-select#91]
When using tom-select 1.7 and bootstrap 5 styles, input-group doesn't group the select ( tom-select has radius on both sides )

difference between working and not working down bellow

https://jsfiddle.net/mArtinko5MB/5jo2xc8u/14/

**Comment by martinbarilik** [comment]
One small thingy, three cases with input group. 

Text / button prepends or appends, or both. In 1.7.1 works only for last case.

**Comment by oyejorge** [comment]
Looks like the problem there is TomSelect not being initialized on a couple examples. Here's an updated example: https://jsfiddle.net/bsae1df7/

```new TomSelect('.tom-select');``` will only initialize the first DOM node with the ```.tom-select``` class.

**Comment by martinbarilik** [comment]
Okay, that is one thing. 

as i was mentioning 

https://jsfiddle.net/mArtinko5MB/rbdcwm86/2/

- the second example has no radius on the left side, probably missing some styles
- the selected option has padding top a pixel or two more then needed
- the more complicated thing is that when you click on select, it fills parent and therefore moves input-group elements to the next row, can we make it the same size whatever we are doing with it ?

**Comment by oyejorge** [comment]
> the second example has no radius on the left side, probably missing some styles

gotcha. Should be fixed now

> the selected option has padding top a pixel or two more then needed

sorry, I'm not seeing it?

> the more complicated thing is that when you click on select, it fills parent and therefore moves input-group elements to the next row, can we make it the same size whatever we are doing with it ?

In this situation, I'd probably use the [dropdown_input plugin](https://tom-select.js.org/plugins/dropdown-input/)

**Comment by martinbarilik** [comment]
![image](https://user-images.githubusercontent.com/58255651/119090566-10d99180-ba0c-11eb-80cd-80993378b590.png)

padding top is causing the issue, it's like a very small space under the text when value is selected

with padding-top and without:

![image](https://user-images.githubusercontent.com/58255651/119090699-39618b80-ba0c-11eb-92d1-858afb83bfed.png) ![image](https://user-images.githubusercontent.com/58255651/119090721-41b9c680-ba0c-11eb-9a07-a5a783ef82c8.png)

**Comment by oyejorge** [comment]
Well, now I know I need to get my eyes checked. It's clear as day now.

**Comment by martinbarilik** [comment]
No worries

**Comment by oyejorge** [comment]
ok, these should be all set with 1.7.2
