### ISSUE TITLE
Select box smooth scrolls to current item when opening

### ISSUE THREAD

**Issue by mattgodbolt** [orchidjs/tom-select#93]
**Describe the bug**
In a long dropdown, the currently selected item is scrolled-to when opening the dropdown. This is wanted behaviour, but if the dropdown was previously scrolled there's an animation from the old position to the selected item position.

**To Reproduce**
1. Make a large list (~200)
2. Select an element at the top
3. Reopen the list
4. Scroll to the bottom
5. Close the list (without picking anything)
6. Reopen the list and observe the dizzzying zoom-scroll from the bottom all the way to the top

**Expected behavior**
Open opening at step 6 the dropdown should be centred about the selected item already without any motion.

**Additional context**
Version: 1.7.1

**Comment by oyejorge** [comment]
It looks like calling ```this.scrollToOption(this.activeOption);``` in the close() method will fix this but I'm gonna test it out some more

**Comment by mattgodbolt** [comment]
Thanks!

**Comment by oyejorge** [comment]
I didn't like my previous idea. Went with the above change. This also uses a new ```scroll(scrollTop, behavior)``` method that you could use. So instead of

```js
this.tomSelect.dropdown_content.style.scrollBehavior = 'auto';
optionElement = this.tomSelect.getOption(value);
this.tomSelect.dropdown_content.scrollTop += (optionElement.offsetTop - elemTop);
this.tomSelect.dropdown_content.style.scrollBehavior = 'smooth';
```
you could do this

```js
var scrollTop = this.tomSelect.dropdown_content.scrollTop + (optionElement.offsetTop - elemTop);
this.tomSelect.scroll( scrollTop, 'auto');
```

Gonna test a little more tomorrow

**Comment by oyejorge** [comment]
ok, I like how things are working. Should be all set with 1.7.2!

**Comment by mattgodbolt** [comment]
fab; thanks. We'll give it a go!
