### ISSUE TITLE
tomselect.clearOptions() doesn't work twice on the same select when using JS API

### ISSUE THREAD

**Issue by martinbarilik** [orchidjs/tom-select#94]
Hi again,

if using JS API, clearOptions() doesn't work as intended ( i think ). First time it works, but then everytime you change the first select, previous value stays with the options as well.

(just change 1st select multiple times and check options in 2nd select everytime )

https://jsfiddle.net/mArtinko5MB/ovub8m6e/7/

**Comment by oyejorge** [comment]
Looks like the documentation for clearOptions() needs to be updated. It should be:

> Removes all *unselected* options from the control. *To clear selection options, call clear() before calling clearOptions()*

https://jsfiddle.net/rkyngebv/

**Comment by martinbarilik** [comment]
Working, closing ;)
